export const combos = [
  {
    letters: 'eeqwrl',
    words: ['were', 'reel', 'lee', 'wee', 'eel'],
    grid: [
      [
        null,
        { letter: 'r', partOfWord: 'reel' },
        null,
        { letter: 'l', partOfWord: 'lee' },
        null,
        null,
      ],
      [
        { letter: 'w', partOfWord: 'were' },
        { letter: 'e', partOfWord: 'reel' },
        { letter: 'r', partOfWord: 'were' },
        { letter: 'e', partOfWord: 'lee' },
        null,
        null,
      ],
      [
        null,
        { letter: 'e', partOfWord: 'reel' },
        null,
        { letter: 'e', partOfWord: 'eel' },
        { letter: 'e', partOfWord: 'eel' },
        { letter: 'l', partOfWord: 'eel' },
      ],
      [null, { letter: 'l', partOfWord: 'reel' }, null, null, null, null],
    ],
    placedWords: 4,
  },
  {
    letters: 'uubrvn',
    words: ['burn', 'run', 'rub', 'bun', 'urn'],
    grid: [
      [null, null, null, { letter: 'b', partOfWord: 'bun' }, null, null],
      [
        null,
        { letter: 'r', partOfWord: 'run' },
        null,
        { letter: 'u', partOfWord: 'urn' },
        { letter: 'r', partOfWord: 'urn' },
        { letter: 'n', partOfWord: 'urn' },
      ],
      [
        { letter: 'b', partOfWord: 'burn' },
        { letter: 'u', partOfWord: 'run' },
        { letter: 'r', partOfWord: 'burn' },
        { letter: 'n', partOfWord: 'bun' },
        null,
        null,
      ],
      [null, { letter: 'n', partOfWord: 'run' }, null, null, null, null],
    ],
    placedWords: 4,
  },
  {
    letters: 'iotbkh',
    words: ['both', 'bit', 'hit', 'hot', 'kit', 'bio', 'bot'],
    grid: [
      [null, null, { letter: 'h', partOfWord: 'hit' }, null],
      [null, null, { letter: 'i', partOfWord: 'hit' }, null],
      [
        { letter: 'b', partOfWord: 'bit' },
        { letter: 'o', partOfWord: 'both' },
        { letter: 't', partOfWord: 'hit' },
        { letter: 'h', partOfWord: 'hot' },
      ],
      [
        { letter: 'i', partOfWord: 'bit' },
        null,
        null,
        { letter: 'o', partOfWord: 'hot' },
      ],
      [
        { letter: 't', partOfWord: 'bit' },
        null,
        null,
        { letter: 't', partOfWord: 'hot' },
      ],
    ],
    placedWords: 4,
  },
  {
    letters: 'eeqfpl',
    words: ['feel', 'peel', 'flee', 'fee', 'eel'],
    grid: [
      [
        null,
        { letter: 'p', partOfWord: 'peel' },
        null,
        { letter: 'f', partOfWord: 'fee' },
        { letter: 'e', partOfWord: 'fee' },
        { letter: 'e', partOfWord: 'fee' },
      ],
      [
        { letter: 'f', partOfWord: 'feel' },
        { letter: 'e', partOfWord: 'peel' },
        { letter: 'e', partOfWord: 'feel' },
        { letter: 'l', partOfWord: 'flee' },
        null,
        null,
      ],
      [
        null,
        { letter: 'e', partOfWord: 'peel' },
        null,
        { letter: 'e', partOfWord: 'eel' },
        { letter: 'e', partOfWord: 'eel' },
        { letter: 'l', partOfWord: 'eel' },
      ],
      [
        null,
        { letter: 'l', partOfWord: 'peel' },
        null,
        { letter: 'e', partOfWord: 'flee' },
        null,
        null,
      ],
    ],
    placedWords: 5,
  },
  {
    letters: 'uijbsy',
    words: ['busy', 'buys', 'buy', 'bus', 'sub'],
    grid: [
      [
        null,
        null,
        null,
        { letter: 'b', partOfWord: 'bus' },
        { letter: 'u', partOfWord: 'bus' },
        { letter: 's', partOfWord: 'bus' },
      ],
      [null, null, null, { letter: 'u', partOfWord: 'buy' }, null, null],
      [
        { letter: 'b', partOfWord: 'buys' },
        { letter: 'u', partOfWord: 'busy' },
        { letter: 's', partOfWord: 'sub' },
        { letter: 'y', partOfWord: 'buy' },
        null,
        null,
      ],
      [
        { letter: 'u', partOfWord: 'buys' },
        null,
        { letter: 'u', partOfWord: 'sub' },
        null,
        null,
        null,
      ],
      [
        { letter: 'y', partOfWord: 'buys' },
        null,
        { letter: 'b', partOfWord: 'sub' },
        null,
        null,
        null,
      ],
      [{ letter: 's', partOfWord: 'buys' }, null, null, null, null, null],
    ],
    placedWords: 5,
  },
  {
    letters: 'ionvnl',
    words: ['lion', 'oil', 'inn', 'ion', 'nil'],
    grid: [
      [
        { letter: 'o', partOfWord: 'oil' },
        null,
        null,
        { letter: 'i', partOfWord: 'ion' },
      ],
      [
        { letter: 'i', partOfWord: 'oil' },
        null,
        null,
        { letter: 'o', partOfWord: 'ion' },
      ],
      [
        { letter: 'l', partOfWord: 'oil' },
        { letter: 'i', partOfWord: 'inn' },
        { letter: 'o', partOfWord: 'lion' },
        { letter: 'n', partOfWord: 'ion' },
      ],
      [null, { letter: 'n', partOfWord: 'inn' }, null, null],
      [
        null,
        { letter: 'n', partOfWord: 'nil' },
        { letter: 'i', partOfWord: 'nil' },
        { letter: 'l', partOfWord: 'nil' },
      ],
    ],
    placedWords: 5,
  },
  {
    letters: 'uopdlc',
    words: [
      'could',
      'cloud',
      'cold',
      'loud',
      'coup',
      'old',
      'cup',
      'cop',
      'cod',
      'pod',
    ],
    grid: [
      [null, null, null, null, null, { letter: 'c', partOfWord: 'cup' }, null],
      [
        null,
        null,
        null,
        { letter: 'c', partOfWord: 'coup' },
        { letter: 'o', partOfWord: 'coup' },
        { letter: 'u', partOfWord: 'cup' },
        { letter: 'p', partOfWord: 'coup' },
      ],
      [
        null,
        null,
        null,
        { letter: 'o', partOfWord: 'cold' },
        null,
        { letter: 'p', partOfWord: 'cup' },
        null,
      ],
      [
        { letter: 'c', partOfWord: 'cloud' },
        { letter: 'o', partOfWord: 'could' },
        { letter: 'u', partOfWord: 'could' },
        { letter: 'l', partOfWord: 'cold' },
        { letter: 'd', partOfWord: 'could' },
        null,
        null,
      ],
      [
        { letter: 'l', partOfWord: 'cloud' },
        null,
        null,
        { letter: 'd', partOfWord: 'cold' },
        null,
        null,
        null,
      ],
      [
        { letter: 'o', partOfWord: 'old' },
        { letter: 'l', partOfWord: 'old' },
        { letter: 'd', partOfWord: 'old' },
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'u', partOfWord: 'cloud' },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'd', partOfWord: 'cloud' },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    ],
    placedWords: 6,
  },
  {
    letters: 'iebfhl',
    words: ['life', 'file', 'bile', 'lie'],
    grid: [
      [null, null, null, { letter: 'b', partOfWord: 'bile' }, null],
      [
        { letter: 'f', partOfWord: 'file' },
        null,
        { letter: 'l', partOfWord: 'lie' },
        { letter: 'i', partOfWord: 'lie' },
        { letter: 'e', partOfWord: 'lie' },
      ],
      [
        { letter: 'i', partOfWord: 'file' },
        null,
        null,
        { letter: 'l', partOfWord: 'bile' },
        null,
      ],
      [
        { letter: 'l', partOfWord: 'file' },
        { letter: 'i', partOfWord: 'life' },
        { letter: 'f', partOfWord: 'life' },
        { letter: 'e', partOfWord: 'bile' },
        null,
      ],
      [{ letter: 'e', partOfWord: 'file' }, null, null, null, null],
    ],
    placedWords: 4,
  },
  {
    letters: 'iuftsf',
    words: ['stuff', 'stiff', 'suit', 'fist', 'fits', 'its', 'fit', 'sit'],
    grid: [
      [
        null,
        { letter: 's', partOfWord: 'sit' },
        { letter: 'i', partOfWord: 'sit' },
        { letter: 't', partOfWord: 'sit' },
        null,
      ],
      [null, { letter: 'u', partOfWord: 'suit' }, null, null, null],
      [null, { letter: 'i', partOfWord: 'suit' }, null, null, null],
      [
        { letter: 's', partOfWord: 'stiff' },
        { letter: 't', partOfWord: 'suit' },
        { letter: 'u', partOfWord: 'stuff' },
        { letter: 'f', partOfWord: 'fist' },
        { letter: 'f', partOfWord: 'stuff' },
      ],
      [
        { letter: 't', partOfWord: 'stiff' },
        null,
        null,
        { letter: 'i', partOfWord: 'fist' },
        null,
      ],
      [
        { letter: 'i', partOfWord: 'stiff' },
        null,
        null,
        { letter: 's', partOfWord: 'fist' },
        null,
      ],
      [
        { letter: 'f', partOfWord: 'stiff' },
        null,
        { letter: 'i', partOfWord: 'its' },
        { letter: 't', partOfWord: 'its' },
        { letter: 's', partOfWord: 'its' },
      ],
      [{ letter: 'f', partOfWord: 'stiff' }, null, null, null, null],
    ],
    placedWords: 6,
  },
  {
    letters: 'eiyrtq',
    words: ['tier', 'tire', 'rite', 'yet', 'try', 'tie', 'rye'],
    grid: [
      [
        null,
        { letter: 't', partOfWord: 'try' },
        { letter: 'r', partOfWord: 'try' },
        { letter: 'y', partOfWord: 'try' },
      ],
      [null, null, { letter: 'i', partOfWord: 'rite' }, null],
      [null, null, { letter: 't', partOfWord: 'rite' }, null],
      [
        { letter: 't', partOfWord: 'tire' },
        { letter: 'i', partOfWord: 'tier' },
        { letter: 'e', partOfWord: 'rite' },
        { letter: 'r', partOfWord: 'rye' },
      ],
      [
        { letter: 'i', partOfWord: 'tire' },
        null,
        null,
        { letter: 'y', partOfWord: 'rye' },
      ],
      [
        { letter: 'r', partOfWord: 'tire' },
        null,
        null,
        { letter: 'e', partOfWord: 'rye' },
      ],
      [{ letter: 'e', partOfWord: 'tire' }, null, null, null],
    ],
    placedWords: 5,
  },
  {
    letters: 'eudlkx',
    words: ['duke', 'duel', 'led', 'due', 'elk'],
    grid: [
      [null, null, null, { letter: 'l', partOfWord: 'led' }, null, null],
      [
        { letter: 'd', partOfWord: 'duel' },
        { letter: 'u', partOfWord: 'duke' },
        { letter: 'k', partOfWord: 'duke' },
        { letter: 'e', partOfWord: 'led' },
        null,
        null,
      ],
      [
        { letter: 'u', partOfWord: 'duel' },
        null,
        null,
        { letter: 'd', partOfWord: 'due' },
        { letter: 'u', partOfWord: 'due' },
        { letter: 'e', partOfWord: 'due' },
      ],
      [
        { letter: 'e', partOfWord: 'elk' },
        { letter: 'l', partOfWord: 'elk' },
        { letter: 'k', partOfWord: 'elk' },
        null,
        null,
        null,
      ],
      [{ letter: 'l', partOfWord: 'duel' }, null, null, null, null, null],
    ],
    placedWords: 5,
  },
  {
    letters: 'eomjhd',
    words: ['home', 'mode', 'dome', 'doe', 'hem', 'ode'],
    grid: [
      [null, null, null, null, null, { letter: 'o', partOfWord: 'ode' }],
      [null, null, null, null, null, { letter: 'd', partOfWord: 'ode' }],
      [
        null,
        null,
        null,
        { letter: 'd', partOfWord: 'doe' },
        { letter: 'o', partOfWord: 'doe' },
        { letter: 'e', partOfWord: 'ode' },
      ],
      [null, null, null, { letter: 'o', partOfWord: 'dome' }, null, null],
      [
        null,
        { letter: 'm', partOfWord: 'mode' },
        null,
        { letter: 'm', partOfWord: 'dome' },
        null,
        null,
      ],
      [
        { letter: 'h', partOfWord: 'home' },
        { letter: 'o', partOfWord: 'mode' },
        { letter: 'm', partOfWord: 'home' },
        { letter: 'e', partOfWord: 'dome' },
        null,
        null,
      ],
      [null, { letter: 'd', partOfWord: 'mode' }, null, null, null, null],
      [
        { letter: 'h', partOfWord: 'hem' },
        { letter: 'e', partOfWord: 'hem' },
        { letter: 'm', partOfWord: 'hem' },
        null,
        null,
        null,
      ],
    ],
    placedWords: 6,
  },
  {
    letters: 'aowtgv',
    words: ['goat', 'two', 'got', 'ago', 'tag', 'vat', 'tow', 'vow', 'oat'],
    grid: [
      [
        null,
        { letter: 't', partOfWord: 'tag' },
        { letter: 'a', partOfWord: 'tag' },
        { letter: 'g', partOfWord: 'tag' },
        null,
      ],
      [null, { letter: 'w', partOfWord: 'two' }, null, null, null],
      [
        { letter: 'g', partOfWord: 'got' },
        { letter: 'o', partOfWord: 'two' },
        { letter: 'a', partOfWord: 'ago' },
        { letter: 't', partOfWord: 'goat' },
        null,
      ],
      [
        { letter: 'o', partOfWord: 'got' },
        null,
        { letter: 'g', partOfWord: 'ago' },
        null,
        null,
      ],
      [
        { letter: 't', partOfWord: 'got' },
        null,
        { letter: 'o', partOfWord: 'oat' },
        { letter: 'a', partOfWord: 'oat' },
        { letter: 't', partOfWord: 'oat' },
      ],
    ],
    placedWords: 6,
  },
  {
    letters: 'oiwcvt',
    words: ['two', 'cow', 'wit', 'tow', 'cot', 'vow', 'tic'],
    grid: [
      [
        null,
        { letter: 'c', partOfWord: 'cot' },
        { letter: 'o', partOfWord: 'cot' },
        { letter: 't', partOfWord: 'cot' },
      ],
      [null, { letter: 'o', partOfWord: 'cow' }, null, null],
      [
        { letter: 't', partOfWord: 'tow' },
        { letter: 'w', partOfWord: 'cow' },
        { letter: 'o', partOfWord: 'two' },
        null,
      ],
      [{ letter: 'o', partOfWord: 'tow' }, null, null, null],
      [{ letter: 'w', partOfWord: 'tow' }, null, null, null],
    ],
    placedWords: 4,
  },
  {
    letters: 'oalxyl',
    words: ['loyal', 'alloy', 'ally', 'all', 'lay'],
    grid: [
      [
        null,
        { letter: 'l', partOfWord: 'lay' },
        { letter: 'a', partOfWord: 'lay' },
        { letter: 'y', partOfWord: 'lay' },
      ],
      [null, null, { letter: 'l', partOfWord: 'ally' }, null],
      [
        { letter: 'a', partOfWord: 'alloy' },
        null,
        { letter: 'l', partOfWord: 'ally' },
        null,
      ],
      [
        { letter: 'l', partOfWord: 'alloy' },
        { letter: 'o', partOfWord: 'loyal' },
        { letter: 'y', partOfWord: 'ally' },
        { letter: 'a', partOfWord: 'all' },
      ],
      [
        { letter: 'l', partOfWord: 'alloy' },
        null,
        null,
        { letter: 'l', partOfWord: 'all' },
      ],
      [
        { letter: 'o', partOfWord: 'alloy' },
        null,
        null,
        { letter: 'l', partOfWord: 'all' },
      ],
      [{ letter: 'y', partOfWord: 'alloy' }, null, null, null],
    ],
    placedWords: 5,
  },
  {
    letters: 'aoclvc',
    words: ['vocal', 'coal', 'cola', 'coca', 'oval'],
    grid: [
      [null, null, null, null, null, null, { letter: 'o', partOfWord: 'oval' }],
      [null, null, null, null, null, null, { letter: 'v', partOfWord: 'oval' }],
      [
        null,
        null,
        null,
        { letter: 'c', partOfWord: 'coca' },
        { letter: 'o', partOfWord: 'coca' },
        { letter: 'c', partOfWord: 'coca' },
        { letter: 'a', partOfWord: 'oval' },
      ],
      [
        null,
        null,
        null,
        { letter: 'o', partOfWord: 'cola' },
        null,
        null,
        { letter: 'l', partOfWord: 'oval' },
      ],
      [
        null,
        { letter: 'c', partOfWord: 'coal' },
        null,
        { letter: 'l', partOfWord: 'cola' },
        null,
        null,
        null,
      ],
      [
        { letter: 'v', partOfWord: 'vocal' },
        { letter: 'o', partOfWord: 'coal' },
        { letter: 'c', partOfWord: 'vocal' },
        { letter: 'a', partOfWord: 'cola' },
        { letter: 'l', partOfWord: 'vocal' },
        null,
        null,
      ],
      [null, { letter: 'a', partOfWord: 'coal' }, null, null, null, null, null],
      [null, { letter: 'l', partOfWord: 'coal' }, null, null, null, null, null],
    ],
    placedWords: 5,
  },
  {
    letters: 'auphlc',
    words: ['haul', 'chap', 'clap', 'cup', 'cap', 'lap', 'pal'],
    grid: [
      [null, null, null, null, null, { letter: 'c', partOfWord: 'cap' }],
      [null, null, null, null, null, { letter: 'a', partOfWord: 'cap' }],
      [
        { letter: 'c', partOfWord: 'chap' },
        null,
        null,
        { letter: 'c', partOfWord: 'cup' },
        { letter: 'u', partOfWord: 'cup' },
        { letter: 'p', partOfWord: 'cap' },
      ],
      [
        { letter: 'h', partOfWord: 'chap' },
        { letter: 'a', partOfWord: 'haul' },
        { letter: 'u', partOfWord: 'haul' },
        { letter: 'l', partOfWord: 'clap' },
        null,
        null,
      ],
      [
        { letter: 'a', partOfWord: 'chap' },
        null,
        null,
        { letter: 'a', partOfWord: 'clap' },
        null,
        null,
      ],
      [
        { letter: 'p', partOfWord: 'chap' },
        null,
        null,
        { letter: 'p', partOfWord: 'pal' },
        { letter: 'a', partOfWord: 'pal' },
        { letter: 'l', partOfWord: 'pal' },
      ],
    ],
    placedWords: 6,
  },
  {
    letters: 'oemhmz',
    words: ['home', 'memo', 'mom', 'hem'],
    grid: [
      [null, { letter: 'm', partOfWord: 'memo' }, null],
      [null, { letter: 'e', partOfWord: 'memo' }, null],
      [null, { letter: 'm', partOfWord: 'memo' }, null],
      [
        { letter: 'h', partOfWord: 'hem' },
        { letter: 'o', partOfWord: 'memo' },
        { letter: 'm', partOfWord: 'mom' },
      ],
      [
        { letter: 'e', partOfWord: 'hem' },
        null,
        { letter: 'o', partOfWord: 'mom' },
      ],
      [
        { letter: 'm', partOfWord: 'hem' },
        null,
        { letter: 'm', partOfWord: 'mom' },
      ],
    ],
    placedWords: 4,
  },
  {
    letters: 'iotycx',
    words: ['toxic', 'city', 'toy', 'icy', 'cot', 'tic'],
    grid: [
      [
        { letter: 'c', partOfWord: 'cot' },
        { letter: 'o', partOfWord: 'cot' },
        { letter: 't', partOfWord: 'cot' },
        null,
        { letter: 't', partOfWord: 'tic' },
      ],
      [
        { letter: 'i', partOfWord: 'city' },
        null,
        null,
        null,
        { letter: 'i', partOfWord: 'tic' },
      ],
      [
        { letter: 't', partOfWord: 'city' },
        { letter: 'o', partOfWord: 'toxic' },
        { letter: 'x', partOfWord: 'toxic' },
        { letter: 'i', partOfWord: 'icy' },
        { letter: 'c', partOfWord: 'tic' },
      ],
      [
        { letter: 'y', partOfWord: 'city' },
        null,
        null,
        { letter: 'c', partOfWord: 'icy' },
        null,
      ],
      [null, null, null, { letter: 'y', partOfWord: 'icy' }, null],
    ],
    placedWords: 5,
  },
  {
    letters: 'uegzld',
    words: ['glued', 'glue', 'duel', 'due', 'leg', 'gel', 'dug'],
    grid: [
      [null, { letter: 'd', partOfWord: 'duel' }, null, null, null],
      [
        null,
        { letter: 'u', partOfWord: 'duel' },
        null,
        { letter: 'd', partOfWord: 'due' },
        null,
      ],
      [
        null,
        { letter: 'e', partOfWord: 'duel' },
        null,
        { letter: 'u', partOfWord: 'due' },
        null,
      ],
      [
        { letter: 'g', partOfWord: 'glue' },
        { letter: 'l', partOfWord: 'duel' },
        { letter: 'u', partOfWord: 'glued' },
        { letter: 'e', partOfWord: 'due' },
        { letter: 'd', partOfWord: 'dug' },
      ],
      [
        { letter: 'l', partOfWord: 'glue' },
        null,
        null,
        null,
        { letter: 'u', partOfWord: 'dug' },
      ],
      [
        { letter: 'u', partOfWord: 'glue' },
        null,
        null,
        null,
        { letter: 'g', partOfWord: 'dug' },
      ],
      [{ letter: 'e', partOfWord: 'glue' }, null, null, null, null],
    ],
    placedWords: 5,
  },
  {
    letters: 'oaggjn',
    words: ['gang', 'gong', 'ago', 'gag'],
    grid: [
      [null, null, null, { letter: 'a', partOfWord: 'ago' }],
      [
        { letter: 'g', partOfWord: 'gong' },
        { letter: 'a', partOfWord: 'gang' },
        { letter: 'n', partOfWord: 'gang' },
        { letter: 'g', partOfWord: 'ago' },
      ],
      [
        { letter: 'o', partOfWord: 'gong' },
        null,
        null,
        { letter: 'o', partOfWord: 'ago' },
      ],
      [{ letter: 'n', partOfWord: 'gong' }, null, null, null],
      [
        { letter: 'g', partOfWord: 'gag' },
        { letter: 'a', partOfWord: 'gag' },
        { letter: 'g', partOfWord: 'gag' },
        null,
      ],
    ],
    placedWords: 4,
  },
  {
    letters: 'iublpr',
    words: ['blur', 'pub', 'lip', 'rip', 'rub', 'rib'],
    grid: [
      [{ letter: 'p', partOfWord: 'pub' }, null, null, null],
      [{ letter: 'u', partOfWord: 'pub' }, null, null, null],
      [
        { letter: 'b', partOfWord: 'pub' },
        { letter: 'l', partOfWord: 'lip' },
        { letter: 'u', partOfWord: 'blur' },
        { letter: 'r', partOfWord: 'rip' },
      ],
      [
        null,
        { letter: 'i', partOfWord: 'lip' },
        null,
        { letter: 'i', partOfWord: 'rip' },
      ],
      [
        null,
        { letter: 'p', partOfWord: 'lip' },
        null,
        { letter: 'p', partOfWord: 'rip' },
      ],
    ],
    placedWords: 4,
  },
  {
    letters: 'aikytc',
    words: ['city', 'tick', 'tack', 'act', 'cat', 'icy', 'tic'],
    grid: [
      [
        { letter: 't', partOfWord: 'tick' },
        null,
        { letter: 't', partOfWord: 'tic' },
        { letter: 'i', partOfWord: 'tic' },
        { letter: 'c', partOfWord: 'tic' },
      ],
      [
        { letter: 'i', partOfWord: 'tick' },
        null,
        null,
        { letter: 'c', partOfWord: 'icy' },
        null,
      ],
      [
        { letter: 'c', partOfWord: 'tick' },
        { letter: 'i', partOfWord: 'city' },
        { letter: 't', partOfWord: 'tack' },
        { letter: 'y', partOfWord: 'icy' },
        null,
      ],
      [
        { letter: 'k', partOfWord: 'tick' },
        null,
        { letter: 'a', partOfWord: 'tack' },
        null,
        null,
      ],
      [
        null,
        { letter: 'a', partOfWord: 'act' },
        { letter: 'c', partOfWord: 'act' },
        { letter: 't', partOfWord: 'act' },
        null,
      ],
      [null, null, { letter: 'k', partOfWord: 'tack' }, null, null],
    ],
    placedWords: 6,
  },
  {
    letters: 'uatbrx',
    words: [
      'but',
      'tax',
      'art',
      'bar',
      'bat',
      'rat',
      'tab',
      'rub',
      'tub',
      'tar',
      'bra',
    ],
    grid: [
      [
        null,
        null,
        null,
        null,
        { letter: 'b', partOfWord: 'bra' },
        { letter: 'r', partOfWord: 'bra' },
        { letter: 'a', partOfWord: 'bra' },
      ],
      [
        { letter: 'b', partOfWord: 'bar' },
        { letter: 'u', partOfWord: 'but' },
        { letter: 't', partOfWord: 'tax' },
        null,
        { letter: 'a', partOfWord: 'bat' },
        null,
        null,
      ],
      [
        { letter: 'a', partOfWord: 'bar' },
        null,
        { letter: 'a', partOfWord: 'art' },
        { letter: 'r', partOfWord: 'art' },
        { letter: 't', partOfWord: 'bat' },
        null,
        null,
      ],
      [
        { letter: 'r', partOfWord: 'bar' },
        null,
        { letter: 'x', partOfWord: 'tax' },
        null,
        null,
        null,
        null,
      ],
    ],
    placedWords: 6,
  },
  {
    letters: 'aedwqx',
    words: ['waxed', 'wade', 'wax', 'awe', 'axe', 'dew'],
    grid: [
      [null, null, null, { letter: 'a', partOfWord: 'axe' }, null],
      [null, null, null, { letter: 'x', partOfWord: 'axe' }, null],
      [
        null,
        { letter: 'a', partOfWord: 'awe' },
        { letter: 'w', partOfWord: 'awe' },
        { letter: 'e', partOfWord: 'axe' },
        null,
      ],
      [null, null, { letter: 'a', partOfWord: 'wax' }, null, null],
      [
        { letter: 'w', partOfWord: 'wade' },
        { letter: 'a', partOfWord: 'waxed' },
        { letter: 'x', partOfWord: 'wax' },
        { letter: 'e', partOfWord: 'waxed' },
        { letter: 'd', partOfWord: 'dew' },
      ],
      [
        { letter: 'a', partOfWord: 'wade' },
        null,
        null,
        null,
        { letter: 'e', partOfWord: 'dew' },
      ],
      [
        { letter: 'd', partOfWord: 'wade' },
        null,
        null,
        null,
        { letter: 'w', partOfWord: 'dew' },
      ],
      [{ letter: 'e', partOfWord: 'wade' }, null, null, null, null],
    ],
    placedWords: 6,
  },
  {
    letters: 'aeljsv',
    words: ['slave', 'sale', 'save', 'seal', 'vale', 'vase', 'sea', 'ale'],
    grid: [
      [
        null,
        null,
        { letter: 's', partOfWord: 'save' },
        null,
        { letter: 's', partOfWord: 'sea' },
        { letter: 'e', partOfWord: 'sea' },
        { letter: 'a', partOfWord: 'sea' },
      ],
      [
        { letter: 's', partOfWord: 'sale' },
        { letter: 'l', partOfWord: 'slave' },
        { letter: 'a', partOfWord: 'save' },
        { letter: 'v', partOfWord: 'slave' },
        { letter: 'e', partOfWord: 'seal' },
        null,
        null,
      ],
      [
        { letter: 'a', partOfWord: 'sale' },
        null,
        { letter: 'v', partOfWord: 'save' },
        null,
        { letter: 'a', partOfWord: 'ale' },
        { letter: 'l', partOfWord: 'ale' },
        { letter: 'e', partOfWord: 'ale' },
      ],
      [
        { letter: 'l', partOfWord: 'sale' },
        null,
        { letter: 'e', partOfWord: 'save' },
        null,
        { letter: 'l', partOfWord: 'seal' },
        null,
        null,
      ],
      [{ letter: 'e', partOfWord: 'sale' }, null, null, null, null, null, null],
    ],
    placedWords: 6,
  },
  {
    letters: 'eurvtg',
    words: ['true', 'urge', 'get', 'gut', 'vet', 'rug', 'tug'],
    grid: [
      [
        null,
        { letter: 'u', partOfWord: 'urge' },
        null,
        { letter: 'g', partOfWord: 'gut' },
        { letter: 'u', partOfWord: 'gut' },
        { letter: 't', partOfWord: 'gut' },
      ],
      [
        { letter: 't', partOfWord: 'true' },
        { letter: 'r', partOfWord: 'urge' },
        { letter: 'u', partOfWord: 'true' },
        { letter: 'e', partOfWord: 'get' },
        null,
        null,
      ],
      [
        null,
        { letter: 'g', partOfWord: 'urge' },
        null,
        { letter: 't', partOfWord: 'tug' },
        { letter: 'u', partOfWord: 'tug' },
        { letter: 'g', partOfWord: 'tug' },
      ],
      [
        { letter: 'v', partOfWord: 'vet' },
        { letter: 'e', partOfWord: 'vet' },
        { letter: 't', partOfWord: 'vet' },
        null,
        null,
        null,
      ],
    ],
    placedWords: 6,
  },
  {
    letters: 'eotmsm',
    words: ['some', 'most', 'stem', 'memo', 'toes', 'set', 'met', 'mom', 'toe'],
    grid: [
      [
        null,
        null,
        { letter: 's', partOfWord: 'stem' },
        null,
        { letter: 's', partOfWord: 'set' },
        null,
      ],
      [
        { letter: 'm', partOfWord: 'most' },
        null,
        { letter: 't', partOfWord: 'toes' },
        { letter: 'o', partOfWord: 'toes' },
        { letter: 'e', partOfWord: 'set' },
        { letter: 's', partOfWord: 'toes' },
      ],
      [
        { letter: 'o', partOfWord: 'most' },
        null,
        { letter: 'e', partOfWord: 'stem' },
        null,
        { letter: 't', partOfWord: 'set' },
        null,
      ],
      [
        { letter: 's', partOfWord: 'most' },
        { letter: 'o', partOfWord: 'some' },
        { letter: 'm', partOfWord: 'stem' },
        { letter: 'e', partOfWord: 'some' },
        null,
        null,
      ],
      [{ letter: 't', partOfWord: 'most' }, null, null, null, null, null],
    ],
    placedWords: 5,
  },
  {
    letters: 'oubnpn',
    words: ['upon', 'noun', 'pub', 'nun', 'bun', 'pun'],
    grid: [
      [{ letter: 'n', partOfWord: 'noun' }, null, null, null],
      [{ letter: 'o', partOfWord: 'noun' }, null, null, null],
      [
        { letter: 'u', partOfWord: 'noun' },
        { letter: 'p', partOfWord: 'upon' },
        { letter: 'o', partOfWord: 'upon' },
        { letter: 'n', partOfWord: 'nun' },
      ],
      [
        { letter: 'n', partOfWord: 'noun' },
        null,
        null,
        { letter: 'u', partOfWord: 'nun' },
      ],
      [
        null,
        { letter: 'b', partOfWord: 'bun' },
        { letter: 'u', partOfWord: 'bun' },
        { letter: 'n', partOfWord: 'bun' },
      ],
    ],
    placedWords: 4,
  },
  {
    letters: 'iudqht',
    words: ['quit', 'quid', 'hit', 'hut', 'hid'],
    grid: [
      [null, null, { letter: 'h', partOfWord: 'hit' }],
      [
        { letter: 'q', partOfWord: 'quid' },
        { letter: 'u', partOfWord: 'quit' },
        { letter: 'i', partOfWord: 'hit' },
      ],
      [
        { letter: 'u', partOfWord: 'quid' },
        null,
        { letter: 't', partOfWord: 'hit' },
      ],
      [{ letter: 'i', partOfWord: 'quid' }, null, null],
      [{ letter: 'd', partOfWord: 'quid' }, null, null],
    ],
    placedWords: 3,
  },
  {
    letters: 'oavbrf',
    words: [
      'favor',
      'bravo',
      'boar',
      'afro',
      'for',
      'far',
      'bar',
      'rob',
      'bra',
      'oar',
    ],
    grid: [
      [
        null,
        { letter: 'b', partOfWord: 'bravo' },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 'r', partOfWord: 'bravo' },
        null,
        { letter: 'b', partOfWord: 'boar' },
        null,
        null,
        null,
      ],
      [
        { letter: 'f', partOfWord: 'favor' },
        { letter: 'a', partOfWord: 'bravo' },
        { letter: 'v', partOfWord: 'favor' },
        { letter: 'o', partOfWord: 'boar' },
        { letter: 'r', partOfWord: 'favor' },
        null,
        null,
      ],
      [
        null,
        { letter: 'v', partOfWord: 'bravo' },
        null,
        { letter: 'a', partOfWord: 'boar' },
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 'o', partOfWord: 'bravo' },
        null,
        { letter: 'r', partOfWord: 'rob' },
        { letter: 'o', partOfWord: 'rob' },
        { letter: 'b', partOfWord: 'bra' },
        null,
      ],
      [null, null, null, null, null, { letter: 'r', partOfWord: 'bra' }, null],
      [
        null,
        null,
        null,
        null,
        { letter: 'o', partOfWord: 'oar' },
        { letter: 'a', partOfWord: 'oar' },
        { letter: 'r', partOfWord: 'oar' },
      ],
    ],
    placedWords: 6,
  },
  {
    letters: 'iavfnd',
    words: [
      'find',
      'avid',
      'vain',
      'and',
      'via',
      'aid',
      'van',
      'fan',
      'fin',
      'fad',
    ],
    grid: [
      [null, null, null, { letter: 'v', partOfWord: 'van' }],
      [null, null, null, { letter: 'a', partOfWord: 'van' }],
      [
        { letter: 'v', partOfWord: 'vain' },
        { letter: 'a', partOfWord: 'vain' },
        { letter: 'i', partOfWord: 'vain' },
        { letter: 'n', partOfWord: 'van' },
      ],
      [null, { letter: 'v', partOfWord: 'avid' }, null, null],
      [
        { letter: 'f', partOfWord: 'find' },
        { letter: 'i', partOfWord: 'avid' },
        { letter: 'n', partOfWord: 'find' },
        { letter: 'd', partOfWord: 'find' },
      ],
      [null, { letter: 'd', partOfWord: 'avid' }, null, null],
    ],
    placedWords: 4,
  },
]
