export const combos = [
  {
    letters: 'eagxdn',
    grid: [
      [null, null, null, null, null, { letter: 'a', partOfWords: ['axe'] }],
      [null, null, null, null, null, { letter: 'x', partOfWords: ['axe'] }],
      [
        { letter: 'd', partOfWords: ['dean'] },
        null,
        null,
        { letter: 'a', partOfWords: ['and', 'age'] },
        { letter: 'g', partOfWords: ['age'] },
        { letter: 'e', partOfWords: ['age', 'axe'] },
      ],
      [
        { letter: 'e', partOfWords: ['dean'] },
        null,
        null,
        { letter: 'n', partOfWords: ['and'] },
        null,
        null,
      ],
      [
        { letter: 'a', partOfWords: ['aged', 'dean'] },
        { letter: 'g', partOfWords: ['aged'] },
        { letter: 'e', partOfWords: ['aged', 'end'] },
        { letter: 'd', partOfWords: ['aged', 'and'] },
        null,
        null,
      ],
      [
        { letter: 'n', partOfWords: ['dean'] },
        null,
        { letter: 'n', partOfWords: ['end'] },
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'd', partOfWords: ['end', 'den'] },
        { letter: 'e', partOfWords: ['den'] },
        { letter: 'n', partOfWords: ['den'] },
        null,
      ],
    ],
    placedWords: ['aged', 'dean', 'and', 'end', 'age', 'den', 'axe'],
  },
  {
    letters: 'oapbdt',
    grid: [
      [
        null,
        null,
        null,
        { letter: 'b', partOfWords: ['bot'] },
        { letter: 'o', partOfWords: ['oat', 'bot'] },
        { letter: 't', partOfWords: ['bot'] },
      ],
      [null, null, null, null, { letter: 'a', partOfWords: ['oat'] }, null],
      [
        { letter: 'b', partOfWords: ['boat'] },
        null,
        { letter: 'a', partOfWords: ['atop', 'apt'] },
        { letter: 'p', partOfWords: ['apt'] },
        { letter: 't', partOfWords: ['apt', 'oat'] },
        null,
      ],
      [
        { letter: 'o', partOfWords: ['boat'] },
        null,
        { letter: 't', partOfWords: ['atop'] },
        null,
        null,
        null,
      ],
      [
        { letter: 'a', partOfWords: ['adopt', 'boat'] },
        { letter: 'd', partOfWords: ['adopt'] },
        { letter: 'o', partOfWords: ['adopt', 'atop'] },
        { letter: 'p', partOfWords: ['adopt'] },
        { letter: 't', partOfWords: ['adopt', 'toad'] },
        null,
      ],
      [
        { letter: 't', partOfWords: ['boat'] },
        null,
        { letter: 'p', partOfWords: ['atop'] },
        null,
        { letter: 'o', partOfWords: ['toad'] },
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'b', partOfWords: ['bad'] },
        { letter: 'a', partOfWords: ['toad', 'bad'] },
        { letter: 'd', partOfWords: ['bad'] },
      ],
      [null, null, null, null, { letter: 'd', partOfWords: ['toad'] }, null],
    ],
    placedWords: ['adopt', 'boat', 'atop', 'toad', 'bad', 'apt', 'oat', 'bot'],
  },
  {
    letters: 'oexphn',
    grid: [
      [
        null,
        null,
        null,
        { letter: 'h', partOfWords: ['hop'] },
        { letter: 'o', partOfWords: ['hop'] },
        { letter: 'p', partOfWords: ['pen', 'hop'] },
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 'e', partOfWords: ['pen'] },
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'o', partOfWords: ['oxen', 'one'] },
        { letter: 'n', partOfWords: ['one', 'pen'] },
        { letter: 'e', partOfWords: ['one'] },
      ],
      [
        { letter: 'o', partOfWords: ['open'] },
        null,
        { letter: 'h', partOfWords: ['hope'] },
        null,
        { letter: 'x', partOfWords: ['oxen'] },
        null,
        null,
      ],
      [
        { letter: 'p', partOfWords: ['phone', 'open'] },
        { letter: 'h', partOfWords: ['phone'] },
        { letter: 'o', partOfWords: ['phone', 'hope'] },
        { letter: 'n', partOfWords: ['phone'] },
        { letter: 'e', partOfWords: ['phone', 'oxen'] },
        null,
        null,
      ],
      [
        { letter: 'e', partOfWords: ['open'] },
        null,
        { letter: 'p', partOfWords: ['hope'] },
        null,
        { letter: 'n', partOfWords: ['oxen'] },
        null,
        null,
      ],
      [
        { letter: 'n', partOfWords: ['open'] },
        null,
        { letter: 'e', partOfWords: ['hope'] },
        null,
        null,
        null,
        null,
      ],
    ],
    placedWords: ['phone', 'open', 'hope', 'oxen', 'one', 'pen', 'hop'],
  },
  {
    letters: 'eehrtp',
    grid: [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'p', partOfWords: ['per', 'pet'] },
        { letter: 'e', partOfWords: ['pet'] },
        { letter: 't', partOfWords: ['pet', 'tee'] },
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'e', partOfWords: ['per'] },
        null,
        { letter: 'e', partOfWords: ['tee'] },
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'h', partOfWords: ['here', 'her'] },
        { letter: 'e', partOfWords: ['her'] },
        { letter: 'r', partOfWords: ['her', 'per'] },
        null,
        { letter: 'e', partOfWords: ['tee'] },
      ],
      [
        { letter: 't', partOfWords: ['there', 'three'] },
        { letter: 'h', partOfWords: ['there'] },
        { letter: 'e', partOfWords: ['there', 'ether'] },
        { letter: 'r', partOfWords: ['there'] },
        { letter: 'e', partOfWords: ['there', 'here'] },
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'h', partOfWords: ['three'] },
        null,
        { letter: 't', partOfWords: ['ether'] },
        null,
        { letter: 'r', partOfWords: ['here'] },
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'r', partOfWords: ['three'] },
        null,
        { letter: 'h', partOfWords: ['ether'] },
        null,
        { letter: 'e', partOfWords: ['here'] },
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'e', partOfWords: ['three'] },
        null,
        { letter: 'e', partOfWords: ['ether'] },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'e', partOfWords: ['three'] },
        null,
        { letter: 'r', partOfWords: ['ether'] },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    ],
    placedWords: [
      'there',
      'three',
      'ether',
      'here',
      'her',
      'per',
      'pet',
      'tee',
    ],
  },
  {
    letters: 'uotpvw',
    grid: [
      [null, null, null, null, null, { letter: 'v', partOfWords: ['vow'] }],
      [null, null, null, null, null, { letter: 'o', partOfWords: ['vow'] }],
      [
        null,
        null,
        null,
        { letter: 't', partOfWords: ['tow'] },
        { letter: 'o', partOfWords: ['opt', 'tow'] },
        { letter: 'w', partOfWords: ['tow', 'vow'] },
      ],
      [null, null, null, null, { letter: 'p', partOfWords: ['opt'] }, null],
      [
        { letter: 't', partOfWords: ['two'] },
        null,
        { letter: 'p', partOfWords: ['put', 'pot'] },
        { letter: 'o', partOfWords: ['pot'] },
        { letter: 't', partOfWords: ['pot', 'opt'] },
        null,
      ],
      [
        { letter: 'w', partOfWords: ['two'] },
        null,
        { letter: 'u', partOfWords: ['put'] },
        null,
        null,
        null,
      ],
      [
        { letter: 'o', partOfWords: ['out', 'two'] },
        { letter: 'u', partOfWords: ['out'] },
        { letter: 't', partOfWords: ['out', 'put'] },
        null,
        null,
        null,
      ],
    ],
    placedWords: ['out', 'two', 'put', 'pot', 'opt', 'tow', 'vow'],
  },
  {
    letters: 'oetnjg',
    grid: [
      [
        null,
        null,
        { letter: 't', partOfWords: ['ton'] },
        { letter: 'o', partOfWords: ['ton'] },
        { letter: 'n', partOfWords: ['net', 'ton'] },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'e', partOfWords: ['net', 'ego'] },
        { letter: 'g', partOfWords: ['ego'] },
        { letter: 'o', partOfWords: ['ego'] },
      ],
      [
        { letter: 'g', partOfWords: ['gone'] },
        null,
        { letter: 'g', partOfWords: ['got'] },
        { letter: 'o', partOfWords: ['one', 'got'] },
        { letter: 't', partOfWords: ['got', 'net'] },
        null,
        null,
      ],
      [
        { letter: 'o', partOfWords: ['gone'] },
        null,
        null,
        { letter: 'n', partOfWords: ['one'] },
        null,
        null,
        null,
      ],
      [
        { letter: 'n', partOfWords: ['note', 'gone'] },
        { letter: 'o', partOfWords: ['note'] },
        { letter: 't', partOfWords: ['note', 'tone'] },
        { letter: 'e', partOfWords: ['note', 'one'] },
        null,
        null,
        null,
      ],
      [
        { letter: 'e', partOfWords: ['gone'] },
        null,
        { letter: 'o', partOfWords: ['tone'] },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'n', partOfWords: ['tone', 'not'] },
        { letter: 'o', partOfWords: ['not'] },
        { letter: 't', partOfWords: ['not', 'ten'] },
        null,
        null,
      ],
      [
        { letter: 't', partOfWords: ['toe'] },
        { letter: 'o', partOfWords: ['toe'] },
        { letter: 'e', partOfWords: ['tone', 'toe'] },
        null,
        { letter: 'e', partOfWords: ['ten'] },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'n', partOfWords: ['ten'] },
        null,
        null,
      ],
    ],
    placedWords: [
      'note',
      'gone',
      'tone',
      'not',
      'one',
      'got',
      'net',
      'ten',
      'ton',
      'ego',
      'toe',
    ],
  },
  {
    letters: 'eorrlw',
    grid: [
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 'o', partOfWords: ['owl'] },
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'l', partOfWords: ['lore', 'low'] },
        { letter: 'o', partOfWords: ['low'] },
        { letter: 'w', partOfWords: ['low', 'owl'] },
        null,
      ],
      [
        { letter: 'r', partOfWords: ['role'] },
        null,
        null,
        { letter: 'o', partOfWords: ['lore'] },
        null,
        { letter: 'l', partOfWords: ['owl'] },
        null,
      ],
      [
        { letter: 'o', partOfWords: ['role'] },
        null,
        null,
        { letter: 'r', partOfWords: ['lore'] },
        null,
        null,
        null,
      ],
      [
        { letter: 'l', partOfWords: ['lower', 'role'] },
        { letter: 'o', partOfWords: ['lower'] },
        { letter: 'w', partOfWords: ['lower', 'wore'] },
        { letter: 'e', partOfWords: ['lower', 'lore'] },
        { letter: 'r', partOfWords: ['lower', 'row'] },
        null,
        null,
      ],
      [
        { letter: 'e', partOfWords: ['role'] },
        null,
        { letter: 'o', partOfWords: ['wore'] },
        null,
        { letter: 'o', partOfWords: ['row'] },
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'r', partOfWords: ['wore'] },
        null,
        { letter: 'w', partOfWords: ['row', 'woe'] },
        { letter: 'o', partOfWords: ['woe'] },
        { letter: 'e', partOfWords: ['woe'] },
      ],
      [
        { letter: 'o', partOfWords: ['ore'] },
        { letter: 'r', partOfWords: ['ore'] },
        { letter: 'e', partOfWords: ['wore', 'ore'] },
        null,
        null,
        null,
        null,
      ],
    ],
    placedWords: [
      'lower',
      'role',
      'wore',
      'lore',
      'low',
      'row',
      'ore',
      'owl',
      'woe',
    ],
  },
  {
    letters: 'oakwht',
    grid: [
      [
        { letter: 'h', partOfWords: ['hawk'] },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'a', partOfWords: ['hawk'] },
        null,
        { letter: 'o', partOfWords: ['oath'] },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'w', partOfWords: ['what', 'hawk'] },
        { letter: 'h', partOfWords: ['what'] },
        { letter: 'a', partOfWords: ['what', 'oath'] },
        { letter: 't', partOfWords: ['what'] },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'k', partOfWords: ['hawk'] },
        null,
        { letter: 't', partOfWords: ['oath'] },
        null,
        null,
        null,
        { letter: 't', partOfWords: ['tow'] },
        null,
        null,
      ],
      [
        null,
        { letter: 't', partOfWords: ['thaw', 'two'] },
        { letter: 'h', partOfWords: ['oath', 'thaw'] },
        { letter: 'a', partOfWords: ['thaw'] },
        { letter: 'w', partOfWords: ['thaw', 'who'] },
        null,
        { letter: 'o', partOfWords: ['tow', 'oat'] },
        { letter: 'a', partOfWords: ['oat'] },
        { letter: 't', partOfWords: ['oat'] },
      ],
      [
        null,
        { letter: 'w', partOfWords: ['two'] },
        null,
        null,
        { letter: 'h', partOfWords: ['who', 'how'] },
        { letter: 'o', partOfWords: ['how'] },
        { letter: 'w', partOfWords: ['how', 'tow'] },
        null,
        null,
      ],
      [
        { letter: 'h', partOfWords: ['hot', 'hat'] },
        { letter: 'o', partOfWords: ['two', 'hot'] },
        { letter: 't', partOfWords: ['hot'] },
        null,
        { letter: 'o', partOfWords: ['who'] },
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'a', partOfWords: ['hat'] },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 't', partOfWords: ['hat'] },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    ],
    placedWords: [
      'what',
      'hawk',
      'oath',
      'thaw',
      'who',
      'two',
      'how',
      'hot',
      'hat',
      'tow',
      'oat',
    ],
  },
  {
    letters: 'aicxrs',
    grid: [
      [
        null,
        null,
        null,
        null,
        { letter: 'a', partOfWords: ['arc'] },
        null,
        { letter: 's', partOfWords: ['sir'] },
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'r', partOfWords: ['arc'] },
        null,
        { letter: 'i', partOfWords: ['sir'] },
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'c', partOfWords: ['car', 'arc'] },
        { letter: 'a', partOfWords: ['air', 'car'] },
        { letter: 'r', partOfWords: ['car', 'sir'] },
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 'i', partOfWords: ['air'] },
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'a', partOfWords: ['arcs', 'airs'] },
        { letter: 'i', partOfWords: ['airs'] },
        { letter: 'r', partOfWords: ['airs', 'air'] },
        { letter: 's', partOfWords: ['airs'] },
      ],
      [
        { letter: 's', partOfWords: ['scar'] },
        null,
        null,
        { letter: 'r', partOfWords: ['arcs'] },
        null,
        null,
        null,
      ],
      [
        { letter: 'c', partOfWords: ['scar'] },
        null,
        null,
        { letter: 'c', partOfWords: ['arcs', 'cars'] },
        { letter: 'a', partOfWords: ['cars'] },
        { letter: 'r', partOfWords: ['cars'] },
        { letter: 's', partOfWords: ['cars', 'six'] },
      ],
      [
        { letter: 'a', partOfWords: ['axis', 'scar'] },
        { letter: 'x', partOfWords: ['axis'] },
        { letter: 'i', partOfWords: ['axis'] },
        { letter: 's', partOfWords: ['axis', 'arcs'] },
        null,
        null,
        { letter: 'i', partOfWords: ['six'] },
      ],
      [
        { letter: 'r', partOfWords: ['scar'] },
        null,
        null,
        null,
        null,
        null,
        { letter: 'x', partOfWords: ['six'] },
      ],
    ],
    placedWords: [
      'axis',
      'scar',
      'arcs',
      'airs',
      'cars',
      'six',
      'air',
      'car',
      'sir',
      'arc',
    ],
  },
  {
    letters: 'aiwnrk',
    grid: [
      [
        null,
        { letter: 'r', partOfWords: ['raw'] },
        { letter: 'a', partOfWords: ['raw'] },
        { letter: 'w', partOfWords: ['warn', 'raw'] },
        null,
        { letter: 'w', partOfWords: ['wink'] },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'a', partOfWords: ['warn', 'akin'] },
        { letter: 'k', partOfWords: ['akin'] },
        { letter: 'i', partOfWords: ['akin', 'wink'] },
        { letter: 'n', partOfWords: ['akin'] },
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'r', partOfWords: ['warn'] },
        null,
        { letter: 'n', partOfWords: ['wink'] },
        null,
        null,
      ],
      [
        { letter: 'r', partOfWords: ['rain', 'rank'] },
        { letter: 'a', partOfWords: ['rain'] },
        { letter: 'i', partOfWords: ['rain', 'ink'] },
        { letter: 'n', partOfWords: ['rain', 'warn'] },
        null,
        { letter: 'k', partOfWords: ['wink', 'kin'] },
        { letter: 'i', partOfWords: ['kin'] },
        { letter: 'n', partOfWords: ['kin'] },
      ],
      [
        { letter: 'a', partOfWords: ['rank'] },
        null,
        { letter: 'n', partOfWords: ['ink'] },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'n', partOfWords: ['rank'] },
        null,
        { letter: 'k', partOfWords: ['ink'] },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'k', partOfWords: ['rank'] },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    ],
    placedWords: ['rain', 'rank', 'warn', 'akin', 'wink', 'raw', 'ink', 'kin'],
  },
  {
    letters: 'eivjfl',
    grid: [
      [
        null,
        null,
        null,
        null,
        { letter: 'v', partOfWords: ['vile'] },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'i', partOfWords: ['vile'] },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'l', partOfWords: ['vile'] },
        null,
        null,
      ],
      [
        null,
        { letter: 'f', partOfWords: ['file'] },
        { letter: 'i', partOfWords: ['file'] },
        { letter: 'l', partOfWords: ['live', 'file'] },
        { letter: 'e', partOfWords: ['file', 'vile'] },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'i', partOfWords: ['live'] },
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 'f', partOfWords: ['five'] },
        null,
        { letter: 'v', partOfWords: ['live', 'veil'] },
        { letter: 'e', partOfWords: ['veil'] },
        { letter: 'i', partOfWords: ['veil'] },
        { letter: 'l', partOfWords: ['veil'] },
      ],
      [
        { letter: 'l', partOfWords: ['life'] },
        { letter: 'i', partOfWords: ['life', 'five'] },
        { letter: 'f', partOfWords: ['life'] },
        { letter: 'e', partOfWords: ['life', 'live'] },
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 'v', partOfWords: ['five'] },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 'e', partOfWords: ['five', 'evil'] },
        { letter: 'v', partOfWords: ['evil', 'vie'] },
        { letter: 'i', partOfWords: ['evil'] },
        { letter: 'l', partOfWords: ['evil', 'lie'] },
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'i', partOfWords: ['vie'] },
        null,
        { letter: 'i', partOfWords: ['lie'] },
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'e', partOfWords: ['vie'] },
        null,
        { letter: 'e', partOfWords: ['lie'] },
        null,
        null,
      ],
    ],
    placedWords: [
      'life',
      'five',
      'live',
      'file',
      'evil',
      'veil',
      'vile',
      'lie',
      'vie',
    ],
  },
  {
    letters: 'eowxfd',
    grid: [
      [
        null,
        { letter: 'f', partOfWords: ['few', 'fox'] },
        { letter: 'o', partOfWords: ['fox'] },
        { letter: 'x', partOfWords: ['fox'] },
        null,
        null,
      ],
      [null, { letter: 'e', partOfWords: ['few'] }, null, null, null, null],
      [
        { letter: 'o', partOfWords: ['owed', 'owe'] },
        { letter: 'w', partOfWords: ['owed', 'few'] },
        { letter: 'e', partOfWords: ['owed'] },
        { letter: 'd', partOfWords: ['owed', 'dew'] },
        null,
        null,
      ],
      [
        { letter: 'w', partOfWords: ['owe'] },
        null,
        null,
        { letter: 'e', partOfWords: ['dew'] },
        null,
        null,
      ],
      [
        { letter: 'e', partOfWords: ['owe'] },
        null,
        null,
        { letter: 'w', partOfWords: ['dew', 'woe'] },
        { letter: 'o', partOfWords: ['woe', 'ode'] },
        { letter: 'e', partOfWords: ['woe'] },
      ],
      [null, null, null, null, { letter: 'd', partOfWords: ['ode'] }, null],
      [null, null, null, null, { letter: 'e', partOfWords: ['ode'] }, null],
    ],
    placedWords: ['owed', 'few', 'fox', 'owe', 'dew', 'woe', 'ode'],
  },
  {
    letters: 'aefszc',
    grid: [
      [
        null,
        null,
        null,
        null,
        { letter: 's', partOfWords: ['sea'] },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'e', partOfWords: ['sea'] },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'c', partOfWords: ['case', 'cafe'] },
        { letter: 'a', partOfWords: ['cafe', 'sea'] },
        { letter: 'f', partOfWords: ['cafe'] },
        { letter: 'e', partOfWords: ['cafe'] },
      ],
      [
        { letter: 'f', partOfWords: ['faces'] },
        null,
        null,
        { letter: 'a', partOfWords: ['case'] },
        null,
        null,
        null,
      ],
      [
        { letter: 'a', partOfWords: ['faces'] },
        null,
        null,
        { letter: 's', partOfWords: ['case'] },
        null,
        null,
        null,
      ],
      [
        { letter: 'c', partOfWords: ['cafes', 'faces'] },
        { letter: 'a', partOfWords: ['cafes'] },
        { letter: 'f', partOfWords: ['cafes', 'face'] },
        { letter: 'e', partOfWords: ['cafes', 'case'] },
        { letter: 's', partOfWords: ['cafes', 'safe'] },
        null,
        null,
      ],
      [
        { letter: 'e', partOfWords: ['faces'] },
        null,
        { letter: 'a', partOfWords: ['face'] },
        null,
        { letter: 'a', partOfWords: ['safe', 'ace'] },
        { letter: 'c', partOfWords: ['ace'] },
        { letter: 'e', partOfWords: ['ace'] },
      ],
      [
        { letter: 's', partOfWords: ['faces'] },
        null,
        { letter: 'c', partOfWords: ['face'] },
        null,
        { letter: 'f', partOfWords: ['safe'] },
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'e', partOfWords: ['face'] },
        null,
        { letter: 'e', partOfWords: ['safe'] },
        null,
        null,
      ],
    ],
    placedWords: [
      'cafes',
      'faces',
      'case',
      'face',
      'safe',
      'cafe',
      'sea',
      'ace',
    ],
  },
  {
    letters: 'aigdfp',
    grid: [
      [{ letter: 'g', partOfWords: ['gap'] }, null, null, null, null, null],
      [{ letter: 'a', partOfWords: ['gap'] }, null, null, null, null, null],
      [
        { letter: 'p', partOfWords: ['paid', 'gap'] },
        { letter: 'a', partOfWords: ['paid', 'aid'] },
        { letter: 'i', partOfWords: ['paid'] },
        { letter: 'd', partOfWords: ['paid', 'dip'] },
        null,
        null,
      ],
      [
        null,
        { letter: 'i', partOfWords: ['aid'] },
        null,
        { letter: 'i', partOfWords: ['dip'] },
        null,
        null,
      ],
      [
        null,
        { letter: 'd', partOfWords: ['aid'] },
        null,
        { letter: 'p', partOfWords: ['dip', 'pad'] },
        { letter: 'a', partOfWords: ['pad'] },
        { letter: 'd', partOfWords: ['pad', 'dig'] },
      ],
      [null, null, null, null, null, { letter: 'i', partOfWords: ['dig'] }],
      [
        null,
        null,
        null,
        { letter: 'f', partOfWords: ['fig', 'fad'] },
        { letter: 'i', partOfWords: ['fig'] },
        { letter: 'g', partOfWords: ['dig', 'fig'] },
      ],
      [null, null, null, { letter: 'a', partOfWords: ['fad'] }, null, null],
      [null, null, null, { letter: 'd', partOfWords: ['fad'] }, null, null],
    ],
    placedWords: ['paid', 'aid', 'gap', 'dip', 'pad', 'dig', 'fig', 'fad'],
  },
  {
    letters: 'aessxp',
    grid: [
      [
        { letter: 's', partOfWords: ['sap'] },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'a', partOfWords: ['sap'] },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'p', partOfWords: ['peas', 'sap'] },
        { letter: 'e', partOfWords: ['peas'] },
        { letter: 'a', partOfWords: ['axes', 'peas'] },
        { letter: 's', partOfWords: ['peas'] },
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'x', partOfWords: ['axes'] },
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'a', partOfWords: ['apex'] },
        null,
        { letter: 'e', partOfWords: ['axes'] },
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'p', partOfWords: ['pass', 'apex'] },
        { letter: 'a', partOfWords: ['pass'] },
        { letter: 's', partOfWords: ['pass', 'axes'] },
        { letter: 's', partOfWords: ['pass', 'seas'] },
        null,
        null,
        null,
      ],
      [
        { letter: 'e', partOfWords: ['apex'] },
        null,
        null,
        { letter: 'e', partOfWords: ['seas'] },
        null,
        { letter: 's', partOfWords: ['sea'] },
        null,
      ],
      [
        { letter: 'x', partOfWords: ['apex'] },
        null,
        null,
        { letter: 'a', partOfWords: ['seas', 'apes'] },
        { letter: 'p', partOfWords: ['apes'] },
        { letter: 'e', partOfWords: ['apes', 'sea'] },
        { letter: 's', partOfWords: ['apes'] },
      ],
      [
        null,
        null,
        null,
        { letter: 's', partOfWords: ['seas'] },
        null,
        { letter: 'a', partOfWords: ['sea'] },
        null,
      ],
    ],
    placedWords: ['pass', 'apex', 'axes', 'seas', 'peas', 'apes', 'sea', 'sap'],
  },
  {
    letters: 'aoxgft',
    grid: [
      [
        null,
        null,
        { letter: 'f', partOfWords: ['fox', 'fat'] },
        { letter: 'a', partOfWords: ['fat'] },
        { letter: 't', partOfWords: ['fat', 'tag'] },
      ],
      [
        null,
        null,
        { letter: 'o', partOfWords: ['fox'] },
        null,
        { letter: 'a', partOfWords: ['tag'] },
      ],
      [
        { letter: 'f', partOfWords: ['fax'] },
        { letter: 'a', partOfWords: ['ago', 'fax'] },
        { letter: 'x', partOfWords: ['fax', 'fox'] },
        null,
        { letter: 'g', partOfWords: ['tag'] },
      ],
      [null, { letter: 'g', partOfWords: ['ago'] }, null, null, null],
      [
        { letter: 'g', partOfWords: ['goat', 'got'] },
        { letter: 'o', partOfWords: ['goat', 'ago'] },
        { letter: 'a', partOfWords: ['goat'] },
        { letter: 't', partOfWords: ['goat', 'tax'] },
        null,
      ],
      [
        { letter: 'o', partOfWords: ['got'] },
        null,
        null,
        { letter: 'a', partOfWords: ['tax'] },
        null,
      ],
      [
        { letter: 't', partOfWords: ['got'] },
        null,
        null,
        { letter: 'x', partOfWords: ['tax'] },
        null,
      ],
    ],
    placedWords: ['goat', 'got', 'ago', 'tax', 'fax', 'fox', 'fat', 'tag'],
  },
  {
    letters: 'eicdbh',
    grid: [
      [null, null, null, null, null, { letter: 'h', partOfWords: ['hid'] }],
      [null, null, null, null, null, { letter: 'i', partOfWords: ['hid'] }],
      [
        null,
        { letter: 'd', partOfWords: ['dice'] },
        null,
        { letter: 'b', partOfWords: ['bed', 'bid'] },
        { letter: 'i', partOfWords: ['bid'] },
        { letter: 'd', partOfWords: ['bid', 'hid'] },
      ],
      [
        { letter: 'h', partOfWords: ['hide'] },
        { letter: 'i', partOfWords: ['hide', 'dice'] },
        { letter: 'd', partOfWords: ['hide'] },
        { letter: 'e', partOfWords: ['hide', 'bed'] },
        null,
        null,
      ],
      [
        null,
        { letter: 'c', partOfWords: ['dice'] },
        null,
        { letter: 'd', partOfWords: ['bed', 'die'] },
        { letter: 'i', partOfWords: ['die', 'ice'] },
        { letter: 'e', partOfWords: ['die'] },
      ],
      [
        null,
        { letter: 'e', partOfWords: ['dice'] },
        null,
        null,
        { letter: 'c', partOfWords: ['ice'] },
        null,
      ],
      [null, null, null, null, { letter: 'e', partOfWords: ['ice'] }, null],
    ],
    placedWords: ['hide', 'dice', 'bed', 'die', 'bid', 'ice', 'hid'],
  },
  {
    letters: 'eaxvrh',
    grid: [
      [null, null, null, null, null, { letter: 'e', partOfWords: ['ear'] }],
      [null, null, null, null, null, { letter: 'a', partOfWords: ['ear'] }],
      [
        null,
        { letter: 'v', partOfWords: ['vera'] },
        null,
        { letter: 'h', partOfWords: ['hare', 'her'] },
        { letter: 'e', partOfWords: ['her'] },
        { letter: 'r', partOfWords: ['her', 'ear'] },
      ],
      [
        null,
        { letter: 'e', partOfWords: ['vera'] },
        null,
        { letter: 'a', partOfWords: ['hare'] },
        null,
        null,
      ],
      [
        null,
        { letter: 'r', partOfWords: ['vera'] },
        null,
        { letter: 'r', partOfWords: ['hare'] },
        null,
        null,
      ],
      [
        { letter: 'h', partOfWords: ['have', 'hear'] },
        { letter: 'a', partOfWords: ['have', 'vera'] },
        { letter: 'v', partOfWords: ['have'] },
        { letter: 'e', partOfWords: ['have', 'hare'] },
        null,
        null,
      ],
      [{ letter: 'e', partOfWords: ['hear'] }, null, null, null, null, null],
      [
        { letter: 'a', partOfWords: ['hear', 'are'] },
        { letter: 'r', partOfWords: ['are'] },
        { letter: 'e', partOfWords: ['are', 'era'] },
        null,
        null,
        null,
      ],
      [
        { letter: 'r', partOfWords: ['hear'] },
        null,
        { letter: 'r', partOfWords: ['era'] },
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'a', partOfWords: ['era', 'axe'] },
        { letter: 'x', partOfWords: ['axe'] },
        { letter: 'e', partOfWords: ['axe'] },
        null,
      ],
    ],
    placedWords: [
      'have',
      'hear',
      'hare',
      'vera',
      'are',
      'her',
      'era',
      'ear',
      'axe',
    ],
  },
  {
    letters: 'audsnm',
    grid: [
      [null, null, null, null, { letter: 'm', partOfWords: ['mud'] }],
      [
        { letter: 'd', partOfWords: ['dams'] },
        null,
        null,
        null,
        { letter: 'u', partOfWords: ['mud'] },
      ],
      [
        { letter: 'a', partOfWords: ['dams'] },
        null,
        { letter: 'm', partOfWords: ['man', 'mad'] },
        { letter: 'a', partOfWords: ['mad'] },
        { letter: 'd', partOfWords: ['mad', 'mud'] },
      ],
      [
        { letter: 'm', partOfWords: ['dams'] },
        null,
        { letter: 'a', partOfWords: ['man'] },
        null,
        null,
      ],
      [
        { letter: 's', partOfWords: ['sand', 'dams'] },
        { letter: 'a', partOfWords: ['sand', 'and'] },
        { letter: 'n', partOfWords: ['sand', 'man'] },
        { letter: 'd', partOfWords: ['sand', 'dam'] },
        null,
      ],
      [
        null,
        { letter: 'n', partOfWords: ['and'] },
        null,
        { letter: 'a', partOfWords: ['dam'] },
        null,
      ],
      [
        null,
        { letter: 'd', partOfWords: ['and'] },
        null,
        { letter: 'm', partOfWords: ['dam'] },
        null,
      ],
    ],
    placedWords: ['sand', 'dams', 'and', 'man', 'mad', 'mud', 'dam'],
  },
  {
    letters: 'aerxhz',
    grid: [
      [null, { letter: 'h', partOfWords: ['haze'] }, null, null, null, null],
      [
        null,
        { letter: 'a', partOfWords: ['haze'] },
        null,
        { letter: 'h', partOfWords: ['her'] },
        null,
        null,
      ],
      [
        null,
        { letter: 'z', partOfWords: ['haze'] },
        null,
        { letter: 'e', partOfWords: ['her', 'ear'] },
        { letter: 'a', partOfWords: ['ear'] },
        { letter: 'r', partOfWords: ['ear'] },
      ],
      [
        { letter: 'h', partOfWords: ['hear', 'hare'] },
        { letter: 'e', partOfWords: ['hear', 'haze'] },
        { letter: 'a', partOfWords: ['hear', 'are'] },
        { letter: 'r', partOfWords: ['hear', 'her'] },
        null,
        null,
      ],
      [
        { letter: 'a', partOfWords: ['hare'] },
        null,
        { letter: 'r', partOfWords: ['are'] },
        null,
        null,
        null,
      ],
      [
        { letter: 'r', partOfWords: ['hare'] },
        null,
        { letter: 'e', partOfWords: ['are', 'era'] },
        { letter: 'r', partOfWords: ['era'] },
        { letter: 'a', partOfWords: ['era', 'axe'] },
        null,
      ],
      [
        { letter: 'e', partOfWords: ['hare'] },
        null,
        null,
        null,
        { letter: 'x', partOfWords: ['axe'] },
        null,
      ],
      [null, null, null, null, { letter: 'e', partOfWords: ['axe'] }, null],
    ],
    placedWords: ['hear', 'hare', 'haze', 'are', 'her', 'era', 'ear', 'axe'],
  },
  {
    letters: 'iakrzm',
    grid: [
      [null, null, { letter: 'r', partOfWords: ['rim'] }, null],
      [null, null, { letter: 'i', partOfWords: ['rim'] }, null],
      [
        { letter: 'a', partOfWords: ['arm', 'aim'] },
        { letter: 'i', partOfWords: ['aim'] },
        { letter: 'm', partOfWords: ['aim', 'rim'] },
        null,
      ],
      [{ letter: 'r', partOfWords: ['arm'] }, null, null, null],
      [
        { letter: 'm', partOfWords: ['mark', 'arm'] },
        { letter: 'a', partOfWords: ['mark', 'air'] },
        { letter: 'r', partOfWords: ['mark'] },
        { letter: 'k', partOfWords: ['mark'] },
      ],
      [null, { letter: 'i', partOfWords: ['air'] }, null, null],
      [
        null,
        { letter: 'r', partOfWords: ['air', 'ram'] },
        { letter: 'a', partOfWords: ['ram'] },
        { letter: 'm', partOfWords: ['ram', 'mar'] },
      ],
      [null, null, null, { letter: 'a', partOfWords: ['mar'] }],
      [null, null, null, { letter: 'r', partOfWords: ['mar'] }],
    ],
    placedWords: ['mark', 'air', 'arm', 'aim', 'ram', 'rim', 'mar'],
  },
  {
    letters: 'aibxdl',
    grid: [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'b', partOfWords: ['bid'] },
      ],
      [
        null,
        null,
        null,
        { letter: 'l', partOfWords: ['lab'] },
        { letter: 'a', partOfWords: ['lab'] },
        { letter: 'b', partOfWords: ['bad', 'lab'] },
        null,
        { letter: 'i', partOfWords: ['bid'] },
      ],
      [
        { letter: 'd', partOfWords: ['dial'] },
        null,
        null,
        null,
        null,
        { letter: 'a', partOfWords: ['bad', 'aid'] },
        { letter: 'i', partOfWords: ['aid'] },
        { letter: 'd', partOfWords: ['aid', 'bid'] },
      ],
      [
        { letter: 'i', partOfWords: ['dial'] },
        null,
        { letter: 'b', partOfWords: ['bail', 'bald'] },
        { letter: 'a', partOfWords: ['bald'] },
        { letter: 'l', partOfWords: ['bald'] },
        { letter: 'd', partOfWords: ['bald', 'bad'] },
        null,
        null,
      ],
      [
        { letter: 'a', partOfWords: ['dial'] },
        null,
        { letter: 'a', partOfWords: ['bail'] },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'l', partOfWords: ['laid', 'dial'] },
        { letter: 'a', partOfWords: ['laid'] },
        { letter: 'i', partOfWords: ['laid', 'bail'] },
        { letter: 'd', partOfWords: ['laid'] },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'l', partOfWords: ['bail'] },
        null,
        null,
        null,
        null,
        null,
      ],
    ],
    placedWords: ['laid', 'dial', 'bail', 'bald', 'bad', 'aid', 'bid', 'lab'],
  },
  {
    letters: 'oanfdv',
    grid: [
      [
        null,
        null,
        { letter: 'f', partOfWords: ['fan'] },
        { letter: 'a', partOfWords: ['and', 'fan'] },
        { letter: 'n', partOfWords: ['fan'] },
      ],
      [
        null,
        { letter: 'n', partOfWords: ['nova'] },
        null,
        { letter: 'n', partOfWords: ['and'] },
        null,
      ],
      [
        { letter: 'f', partOfWords: ['fond'] },
        { letter: 'o', partOfWords: ['fond', 'nova'] },
        { letter: 'n', partOfWords: ['fond'] },
        { letter: 'd', partOfWords: ['fond', 'and'] },
        null,
      ],
      [null, { letter: 'v', partOfWords: ['nova'] }, null, null, null],
      [
        { letter: 'v', partOfWords: ['van'] },
        { letter: 'a', partOfWords: ['nova', 'van'] },
        { letter: 'n', partOfWords: ['van', 'nod'] },
        null,
        null,
      ],
      [null, null, { letter: 'o', partOfWords: ['nod'] }, null, null],
      [
        { letter: 'f', partOfWords: ['fad'] },
        { letter: 'a', partOfWords: ['fad', 'ado'] },
        { letter: 'd', partOfWords: ['nod', 'fad'] },
        null,
        null,
      ],
      [null, { letter: 'd', partOfWords: ['ado'] }, null, null, null],
      [null, { letter: 'o', partOfWords: ['ado'] }, null, null, null],
    ],
    placedWords: ['fond', 'nova', 'and', 'van', 'fan', 'nod', 'fad', 'ado'],
  },
  {
    letters: 'eaqsyl',
    grid: [
      [
        { letter: 's', partOfWords: ['sale'] },
        null,
        null,
        { letter: 's', partOfWords: ['slay', 'say'] },
        { letter: 'a', partOfWords: ['say'] },
        { letter: 'y', partOfWords: ['say', 'yes'] },
        null,
        null,
      ],
      [
        { letter: 'a', partOfWords: ['sale'] },
        null,
        null,
        { letter: 'l', partOfWords: ['slay'] },
        null,
        { letter: 'e', partOfWords: ['yes'] },
        null,
        null,
      ],
      [
        { letter: 'l', partOfWords: ['sale'] },
        null,
        null,
        { letter: 'a', partOfWords: ['slay'] },
        null,
        { letter: 's', partOfWords: ['yes', 'sly'] },
        { letter: 'l', partOfWords: ['sly'] },
        { letter: 'y', partOfWords: ['sly'] },
      ],
      [
        { letter: 'e', partOfWords: ['easy', 'sale'] },
        { letter: 'a', partOfWords: ['easy'] },
        { letter: 's', partOfWords: ['easy', 'seal'] },
        { letter: 'y', partOfWords: ['easy', 'slay'] },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'e', partOfWords: ['seal'] },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 'l', partOfWords: ['lays'] },
        { letter: 'a', partOfWords: ['seal', 'lays'] },
        { letter: 'y', partOfWords: ['lays'] },
        { letter: 's', partOfWords: ['lays', 'sea'] },
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'l', partOfWords: ['seal'] },
        null,
        { letter: 'e', partOfWords: ['sea'] },
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'l', partOfWords: ['lay'] },
        { letter: 'a', partOfWords: ['sea', 'lay'] },
        { letter: 'y', partOfWords: ['lay'] },
        null,
        null,
      ],
    ],
    placedWords: [
      'easy',
      'sale',
      'seal',
      'slay',
      'lays',
      'say',
      'yes',
      'sea',
      'lay',
      'sly',
    ],
  },
  {
    letters: 'oeprkk',
    grid: [
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 'p', partOfWords: ['pore', 'per'] },
        { letter: 'e', partOfWords: ['per'] },
        { letter: 'r', partOfWords: ['per'] },
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 'o', partOfWords: ['pore'] },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 'r', partOfWords: ['pore'] },
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'p', partOfWords: ['pork', 'poke'] },
        { letter: 'o', partOfWords: ['poke'] },
        { letter: 'k', partOfWords: ['poke'] },
        { letter: 'e', partOfWords: ['poke', 'pore'] },
        null,
        null,
      ],
      [
        { letter: 'r', partOfWords: ['rope'] },
        null,
        { letter: 'o', partOfWords: ['pork'] },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'o', partOfWords: ['rope'] },
        null,
        { letter: 'r', partOfWords: ['pork'] },
        null,
        { letter: 'o', partOfWords: ['ore'] },
        null,
        null,
        null,
      ],
      [
        { letter: 'p', partOfWords: ['poker', 'rope'] },
        { letter: 'o', partOfWords: ['poker'] },
        { letter: 'k', partOfWords: ['poker', 'pork'] },
        { letter: 'e', partOfWords: ['poker'] },
        { letter: 'r', partOfWords: ['poker', 'ore'] },
        null,
        null,
        null,
      ],
      [
        { letter: 'e', partOfWords: ['rope'] },
        null,
        null,
        null,
        { letter: 'e', partOfWords: ['ore'] },
        null,
        null,
        null,
      ],
    ],
    placedWords: ['poker', 'rope', 'pork', 'poke', 'pore', 'per', 'ore'],
  },
]
