export const combos = [
  {
    letters: 'eeqwrl',
    grid: [
      [
        null,
        { letter: 'r', partOfWords: ['reel'] },
        null,
        { letter: 'l', partOfWords: ['lee'] },
        null,
        null,
      ],
      [
        { letter: 'w', partOfWords: ['were'] },
        { letter: 'e', partOfWords: ['were', 'reel'] },
        { letter: 'r', partOfWords: ['were'] },
        { letter: 'e', partOfWords: ['were', 'lee'] },
        null,
        null,
      ],
      [
        null,
        { letter: 'e', partOfWords: ['reel'] },
        null,
        { letter: 'e', partOfWords: ['lee', 'eel'] },
        { letter: 'e', partOfWords: ['eel'] },
        { letter: 'l', partOfWords: ['eel'] },
      ],
      [null, { letter: 'l', partOfWords: ['reel'] }, null, null, null, null],
    ],
    placedWords: ['were', 'reel', 'lee', 'eel'],
  },
  {
    letters: 'uubrvn',
    grid: [
      [null, null, null, { letter: 'b', partOfWords: ['bun'] }, null, null],
      [
        null,
        { letter: 'r', partOfWords: ['run'] },
        null,
        { letter: 'u', partOfWords: ['bun', 'urn'] },
        { letter: 'r', partOfWords: ['urn'] },
        { letter: 'n', partOfWords: ['urn'] },
      ],
      [
        { letter: 'b', partOfWords: ['burn'] },
        { letter: 'u', partOfWords: ['burn', 'run'] },
        { letter: 'r', partOfWords: ['burn'] },
        { letter: 'n', partOfWords: ['burn', 'bun'] },
        null,
        null,
      ],
      [null, { letter: 'n', partOfWords: ['run'] }, null, null, null, null],
    ],
    placedWords: ['burn', 'run', 'bun', 'urn'],
  },
  {
    letters: 'iotbkh',
    grid: [
      [null, null, { letter: 'h', partOfWords: ['hit'] }, null],
      [null, null, { letter: 'i', partOfWords: ['hit'] }, null],
      [
        { letter: 'b', partOfWords: ['both', 'bit'] },
        { letter: 'o', partOfWords: ['both'] },
        { letter: 't', partOfWords: ['both', 'hit'] },
        { letter: 'h', partOfWords: ['both', 'hot'] },
      ],
      [
        { letter: 'i', partOfWords: ['bit'] },
        null,
        null,
        { letter: 'o', partOfWords: ['hot'] },
      ],
      [
        { letter: 't', partOfWords: ['bit'] },
        null,
        null,
        { letter: 't', partOfWords: ['hot'] },
      ],
    ],
    placedWords: ['both', 'bit', 'hit', 'hot'],
  },
  {
    letters: 'eeqfpl',
    grid: [
      [
        null,
        { letter: 'p', partOfWords: ['peel'] },
        null,
        { letter: 'f', partOfWords: ['flee', 'fee'] },
        { letter: 'e', partOfWords: ['fee'] },
        { letter: 'e', partOfWords: ['fee'] },
      ],
      [
        { letter: 'f', partOfWords: ['feel'] },
        { letter: 'e', partOfWords: ['feel', 'peel'] },
        { letter: 'e', partOfWords: ['feel'] },
        { letter: 'l', partOfWords: ['feel', 'flee'] },
        null,
        null,
      ],
      [
        null,
        { letter: 'e', partOfWords: ['peel'] },
        null,
        { letter: 'e', partOfWords: ['flee', 'eel'] },
        { letter: 'e', partOfWords: ['eel'] },
        { letter: 'l', partOfWords: ['eel'] },
      ],
      [
        null,
        { letter: 'l', partOfWords: ['peel'] },
        null,
        { letter: 'e', partOfWords: ['flee'] },
        null,
        null,
      ],
    ],
    placedWords: ['feel', 'peel', 'flee', 'fee', 'eel'],
  },
  {
    letters: 'uijbsy',
    grid: [
      [
        null,
        null,
        null,
        { letter: 'b', partOfWords: ['buy', 'bus'] },
        { letter: 'u', partOfWords: ['bus'] },
        { letter: 's', partOfWords: ['bus'] },
      ],
      [null, null, null, { letter: 'u', partOfWords: ['buy'] }, null, null],
      [
        { letter: 'b', partOfWords: ['busy', 'buys'] },
        { letter: 'u', partOfWords: ['busy'] },
        { letter: 's', partOfWords: ['busy', 'sub'] },
        { letter: 'y', partOfWords: ['busy', 'buy'] },
        null,
        null,
      ],
      [
        { letter: 'u', partOfWords: ['buys'] },
        null,
        { letter: 'u', partOfWords: ['sub'] },
        null,
        null,
        null,
      ],
      [
        { letter: 'y', partOfWords: ['buys'] },
        null,
        { letter: 'b', partOfWords: ['sub'] },
        null,
        null,
        null,
      ],
      [{ letter: 's', partOfWords: ['buys'] }, null, null, null, null, null],
    ],
    placedWords: ['busy', 'buys', 'buy', 'bus', 'sub'],
  },
  {
    letters: 'ionvnl',
    grid: [
      [
        { letter: 'o', partOfWords: ['oil'] },
        null,
        null,
        { letter: 'i', partOfWords: ['ion'] },
      ],
      [
        { letter: 'i', partOfWords: ['oil'] },
        null,
        null,
        { letter: 'o', partOfWords: ['ion'] },
      ],
      [
        { letter: 'l', partOfWords: ['lion', 'oil'] },
        { letter: 'i', partOfWords: ['lion', 'inn'] },
        { letter: 'o', partOfWords: ['lion'] },
        { letter: 'n', partOfWords: ['lion', 'ion'] },
      ],
      [null, { letter: 'n', partOfWords: ['inn'] }, null, null],
      [
        null,
        { letter: 'n', partOfWords: ['inn', 'nil'] },
        { letter: 'i', partOfWords: ['nil'] },
        { letter: 'l', partOfWords: ['nil'] },
      ],
    ],
    placedWords: ['lion', 'oil', 'inn', 'ion', 'nil'],
  },
  {
    letters: 'uopdlc',
    grid: [
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 'c', partOfWords: ['cup'] },
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'c', partOfWords: ['cold', 'coup'] },
        { letter: 'o', partOfWords: ['coup'] },
        { letter: 'u', partOfWords: ['coup', 'cup'] },
        { letter: 'p', partOfWords: ['coup'] },
      ],
      [
        null,
        null,
        null,
        { letter: 'o', partOfWords: ['cold'] },
        null,
        { letter: 'p', partOfWords: ['cup'] },
        null,
      ],
      [
        { letter: 'c', partOfWords: ['could', 'cloud'] },
        { letter: 'o', partOfWords: ['could'] },
        { letter: 'u', partOfWords: ['could'] },
        { letter: 'l', partOfWords: ['could', 'cold'] },
        { letter: 'd', partOfWords: ['could'] },
        null,
        null,
      ],
      [
        { letter: 'l', partOfWords: ['cloud'] },
        null,
        null,
        { letter: 'd', partOfWords: ['cold'] },
        null,
        null,
        null,
      ],
      [
        { letter: 'o', partOfWords: ['cloud', 'old'] },
        { letter: 'l', partOfWords: ['old'] },
        { letter: 'd', partOfWords: ['old'] },
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'u', partOfWords: ['cloud'] },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'd', partOfWords: ['cloud'] },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    ],
    placedWords: ['could', 'cloud', 'cold', 'coup', 'old', 'cup'],
  },
  {
    letters: 'iebfhl',
    grid: [
      [null, null, null, { letter: 'b', partOfWords: ['bile'] }, null],
      [
        { letter: 'f', partOfWords: ['file'] },
        null,
        { letter: 'l', partOfWords: ['lie'] },
        { letter: 'i', partOfWords: ['bile', 'lie'] },
        { letter: 'e', partOfWords: ['lie'] },
      ],
      [
        { letter: 'i', partOfWords: ['file'] },
        null,
        null,
        { letter: 'l', partOfWords: ['bile'] },
        null,
      ],
      [
        { letter: 'l', partOfWords: ['life', 'file'] },
        { letter: 'i', partOfWords: ['life'] },
        { letter: 'f', partOfWords: ['life'] },
        { letter: 'e', partOfWords: ['life', 'bile'] },
        null,
      ],
      [{ letter: 'e', partOfWords: ['file'] }, null, null, null, null],
    ],
    placedWords: ['life', 'file', 'bile', 'lie'],
  },
  {
    letters: 'iuftsf',
    grid: [
      [
        null,
        { letter: 's', partOfWords: ['suit', 'sit'] },
        { letter: 'i', partOfWords: ['sit'] },
        { letter: 't', partOfWords: ['sit'] },
        null,
      ],
      [null, { letter: 'u', partOfWords: ['suit'] }, null, null, null],
      [null, { letter: 'i', partOfWords: ['suit'] }, null, null, null],
      [
        { letter: 's', partOfWords: ['stuff', 'stiff'] },
        { letter: 't', partOfWords: ['stuff', 'suit'] },
        { letter: 'u', partOfWords: ['stuff'] },
        { letter: 'f', partOfWords: ['stuff', 'fist'] },
        { letter: 'f', partOfWords: ['stuff'] },
      ],
      [
        { letter: 't', partOfWords: ['stiff'] },
        null,
        null,
        { letter: 'i', partOfWords: ['fist'] },
        null,
      ],
      [
        { letter: 'i', partOfWords: ['stiff'] },
        null,
        null,
        { letter: 's', partOfWords: ['fist'] },
        null,
      ],
      [
        { letter: 'f', partOfWords: ['stiff'] },
        null,
        { letter: 'i', partOfWords: ['its'] },
        { letter: 't', partOfWords: ['fist', 'its'] },
        { letter: 's', partOfWords: ['its'] },
      ],
      [{ letter: 'f', partOfWords: ['stiff'] }, null, null, null, null],
    ],
    placedWords: ['stuff', 'stiff', 'suit', 'fist', 'its', 'sit'],
  },
  {
    letters: 'eiyrtq',
    grid: [
      [
        null,
        { letter: 't', partOfWords: ['try'] },
        { letter: 'r', partOfWords: ['rite', 'try'] },
        { letter: 'y', partOfWords: ['try'] },
      ],
      [null, null, { letter: 'i', partOfWords: ['rite'] }, null],
      [null, null, { letter: 't', partOfWords: ['rite'] }, null],
      [
        { letter: 't', partOfWords: ['tier', 'tire'] },
        { letter: 'i', partOfWords: ['tier'] },
        { letter: 'e', partOfWords: ['tier', 'rite'] },
        { letter: 'r', partOfWords: ['tier', 'rye'] },
      ],
      [
        { letter: 'i', partOfWords: ['tire'] },
        null,
        null,
        { letter: 'y', partOfWords: ['rye'] },
      ],
      [
        { letter: 'r', partOfWords: ['tire'] },
        null,
        null,
        { letter: 'e', partOfWords: ['rye'] },
      ],
      [{ letter: 'e', partOfWords: ['tire'] }, null, null, null],
    ],
    placedWords: ['tier', 'tire', 'rite', 'try', 'rye'],
  },
  {
    letters: 'eudlkx',
    grid: [
      [null, null, null, { letter: 'l', partOfWords: ['led'] }, null, null],
      [
        { letter: 'd', partOfWords: ['duke', 'duel'] },
        { letter: 'u', partOfWords: ['duke'] },
        { letter: 'k', partOfWords: ['duke'] },
        { letter: 'e', partOfWords: ['duke', 'led'] },
        null,
        null,
      ],
      [
        { letter: 'u', partOfWords: ['duel'] },
        null,
        null,
        { letter: 'd', partOfWords: ['led', 'due'] },
        { letter: 'u', partOfWords: ['due'] },
        { letter: 'e', partOfWords: ['due'] },
      ],
      [
        { letter: 'e', partOfWords: ['duel', 'elk'] },
        { letter: 'l', partOfWords: ['elk'] },
        { letter: 'k', partOfWords: ['elk'] },
        null,
        null,
        null,
      ],
      [{ letter: 'l', partOfWords: ['duel'] }, null, null, null, null, null],
    ],
    placedWords: ['duke', 'duel', 'led', 'due', 'elk'],
  },
  {
    letters: 'eomjhd',
    grid: [
      [null, null, null, null, null, { letter: 'o', partOfWords: ['ode'] }],
      [null, null, null, null, null, { letter: 'd', partOfWords: ['ode'] }],
      [
        null,
        null,
        null,
        { letter: 'd', partOfWords: ['dome', 'doe'] },
        { letter: 'o', partOfWords: ['doe'] },
        { letter: 'e', partOfWords: ['doe', 'ode'] },
      ],
      [null, null, null, { letter: 'o', partOfWords: ['dome'] }, null, null],
      [
        null,
        { letter: 'm', partOfWords: ['mode'] },
        null,
        { letter: 'm', partOfWords: ['dome'] },
        null,
        null,
      ],
      [
        { letter: 'h', partOfWords: ['home'] },
        { letter: 'o', partOfWords: ['home', 'mode'] },
        { letter: 'm', partOfWords: ['home'] },
        { letter: 'e', partOfWords: ['home', 'dome'] },
        null,
        null,
      ],
      [null, { letter: 'd', partOfWords: ['mode'] }, null, null, null, null],
      [
        { letter: 'h', partOfWords: ['hem'] },
        { letter: 'e', partOfWords: ['mode', 'hem'] },
        { letter: 'm', partOfWords: ['hem'] },
        null,
        null,
        null,
      ],
    ],
    placedWords: ['home', 'mode', 'dome', 'doe', 'hem', 'ode'],
  },
  {
    letters: 'aowtgv',
    grid: [
      [
        null,
        { letter: 't', partOfWords: ['two', 'tag'] },
        { letter: 'a', partOfWords: ['tag'] },
        { letter: 'g', partOfWords: ['tag'] },
        null,
      ],
      [null, { letter: 'w', partOfWords: ['two'] }, null, null, null],
      [
        { letter: 'g', partOfWords: ['goat', 'got'] },
        { letter: 'o', partOfWords: ['goat', 'two'] },
        { letter: 'a', partOfWords: ['goat', 'ago'] },
        { letter: 't', partOfWords: ['goat'] },
        null,
      ],
      [
        { letter: 'o', partOfWords: ['got'] },
        null,
        { letter: 'g', partOfWords: ['ago'] },
        null,
        null,
      ],
      [
        { letter: 't', partOfWords: ['got'] },
        null,
        { letter: 'o', partOfWords: ['ago', 'oat'] },
        { letter: 'a', partOfWords: ['oat'] },
        { letter: 't', partOfWords: ['oat'] },
      ],
    ],
    placedWords: ['goat', 'two', 'got', 'ago', 'tag', 'oat'],
  },
  {
    letters: 'oiwcvt',
    grid: [
      [
        null,
        { letter: 'c', partOfWords: ['cow', 'cot'] },
        { letter: 'o', partOfWords: ['cot'] },
        { letter: 't', partOfWords: ['cot'] },
      ],
      [null, { letter: 'o', partOfWords: ['cow'] }, null, null],
      [
        { letter: 't', partOfWords: ['two', 'tow'] },
        { letter: 'w', partOfWords: ['two', 'cow'] },
        { letter: 'o', partOfWords: ['two'] },
        null,
      ],
      [{ letter: 'o', partOfWords: ['tow'] }, null, null, null],
      [{ letter: 'w', partOfWords: ['tow'] }, null, null, null],
    ],
    placedWords: ['two', 'cow', 'tow', 'cot'],
  },
  {
    letters: 'oalxyl',
    grid: [
      [
        null,
        { letter: 'l', partOfWords: ['lay'] },
        { letter: 'a', partOfWords: ['ally', 'lay'] },
        { letter: 'y', partOfWords: ['lay'] },
      ],
      [null, null, { letter: 'l', partOfWords: ['ally'] }, null],
      [
        { letter: 'a', partOfWords: ['alloy'] },
        null,
        { letter: 'l', partOfWords: ['ally'] },
        null,
      ],
      [
        { letter: 'l', partOfWords: ['loyal', 'alloy'] },
        { letter: 'o', partOfWords: ['loyal'] },
        { letter: 'y', partOfWords: ['loyal', 'ally'] },
        { letter: 'a', partOfWords: ['loyal', 'all'] },
      ],
      [
        { letter: 'l', partOfWords: ['alloy'] },
        null,
        null,
        { letter: 'l', partOfWords: ['all'] },
      ],
      [
        { letter: 'o', partOfWords: ['alloy'] },
        null,
        null,
        { letter: 'l', partOfWords: ['all'] },
      ],
      [{ letter: 'y', partOfWords: ['alloy'] }, null, null, null],
    ],
    placedWords: ['loyal', 'alloy', 'ally', 'all', 'lay'],
  },
  {
    letters: 'aoclvc',
    grid: [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'o', partOfWords: ['oval'] },
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'v', partOfWords: ['oval'] },
      ],
      [
        null,
        null,
        null,
        { letter: 'c', partOfWords: ['cola', 'coca'] },
        { letter: 'o', partOfWords: ['coca'] },
        { letter: 'c', partOfWords: ['coca'] },
        { letter: 'a', partOfWords: ['coca', 'oval'] },
      ],
      [
        null,
        null,
        null,
        { letter: 'o', partOfWords: ['cola'] },
        null,
        null,
        { letter: 'l', partOfWords: ['oval'] },
      ],
      [
        null,
        { letter: 'c', partOfWords: ['coal'] },
        null,
        { letter: 'l', partOfWords: ['cola'] },
        null,
        null,
        null,
      ],
      [
        { letter: 'v', partOfWords: ['vocal'] },
        { letter: 'o', partOfWords: ['vocal', 'coal'] },
        { letter: 'c', partOfWords: ['vocal'] },
        { letter: 'a', partOfWords: ['vocal', 'cola'] },
        { letter: 'l', partOfWords: ['vocal'] },
        null,
        null,
      ],
      [
        null,
        { letter: 'a', partOfWords: ['coal'] },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 'l', partOfWords: ['coal'] },
        null,
        null,
        null,
        null,
        null,
      ],
    ],
    placedWords: ['vocal', 'coal', 'cola', 'coca', 'oval'],
  },
  {
    letters: 'auphlc',
    grid: [
      [null, null, null, null, null, { letter: 'c', partOfWords: ['cap'] }],
      [null, null, null, null, null, { letter: 'a', partOfWords: ['cap'] }],
      [
        { letter: 'c', partOfWords: ['chap'] },
        null,
        null,
        { letter: 'c', partOfWords: ['clap', 'cup'] },
        { letter: 'u', partOfWords: ['cup'] },
        { letter: 'p', partOfWords: ['cup', 'cap'] },
      ],
      [
        { letter: 'h', partOfWords: ['haul', 'chap'] },
        { letter: 'a', partOfWords: ['haul'] },
        { letter: 'u', partOfWords: ['haul'] },
        { letter: 'l', partOfWords: ['haul', 'clap'] },
        null,
        null,
      ],
      [
        { letter: 'a', partOfWords: ['chap'] },
        null,
        null,
        { letter: 'a', partOfWords: ['clap'] },
        null,
        null,
      ],
      [
        { letter: 'p', partOfWords: ['chap'] },
        null,
        null,
        { letter: 'p', partOfWords: ['clap', 'pal'] },
        { letter: 'a', partOfWords: ['pal'] },
        { letter: 'l', partOfWords: ['pal'] },
      ],
    ],
    placedWords: ['haul', 'chap', 'clap', 'cup', 'cap', 'pal'],
  },
  {
    letters: 'oemhmz',
    grid: [
      [null, { letter: 'm', partOfWords: ['memo'] }, null],
      [null, { letter: 'e', partOfWords: ['memo'] }, null],
      [null, { letter: 'm', partOfWords: ['memo'] }, null],
      [
        { letter: 'h', partOfWords: ['home', 'hem'] },
        { letter: 'o', partOfWords: ['home', 'memo'] },
        { letter: 'm', partOfWords: ['home', 'mom'] },
      ],
      [
        { letter: 'e', partOfWords: ['hem'] },
        null,
        { letter: 'o', partOfWords: ['mom'] },
      ],
      [
        { letter: 'm', partOfWords: ['hem'] },
        null,
        { letter: 'm', partOfWords: ['mom'] },
      ],
    ],
    placedWords: ['home', 'memo', 'mom', 'hem'],
  },
  {
    letters: 'iotycx',
    grid: [
      [
        { letter: 'c', partOfWords: ['city', 'cot'] },
        { letter: 'o', partOfWords: ['cot'] },
        { letter: 't', partOfWords: ['cot'] },
        null,
        { letter: 't', partOfWords: ['tic'] },
      ],
      [
        { letter: 'i', partOfWords: ['city'] },
        null,
        null,
        null,
        { letter: 'i', partOfWords: ['tic'] },
      ],
      [
        { letter: 't', partOfWords: ['toxic', 'city'] },
        { letter: 'o', partOfWords: ['toxic'] },
        { letter: 'x', partOfWords: ['toxic'] },
        { letter: 'i', partOfWords: ['toxic', 'icy'] },
        { letter: 'c', partOfWords: ['toxic', 'tic'] },
      ],
      [
        { letter: 'y', partOfWords: ['city'] },
        null,
        null,
        { letter: 'c', partOfWords: ['icy'] },
        null,
      ],
      [null, null, null, { letter: 'y', partOfWords: ['icy'] }, null],
    ],
    placedWords: ['toxic', 'city', 'icy', 'cot', 'tic'],
  },
  {
    letters: 'uegzld',
    grid: [
      [null, { letter: 'd', partOfWords: ['duel'] }, null, null, null],
      [
        null,
        { letter: 'u', partOfWords: ['duel'] },
        null,
        { letter: 'd', partOfWords: ['due'] },
        null,
      ],
      [
        null,
        { letter: 'e', partOfWords: ['duel'] },
        null,
        { letter: 'u', partOfWords: ['due'] },
        null,
      ],
      [
        { letter: 'g', partOfWords: ['glued', 'glue'] },
        { letter: 'l', partOfWords: ['glued', 'duel'] },
        { letter: 'u', partOfWords: ['glued'] },
        { letter: 'e', partOfWords: ['glued', 'due'] },
        { letter: 'd', partOfWords: ['glued', 'dug'] },
      ],
      [
        { letter: 'l', partOfWords: ['glue'] },
        null,
        null,
        null,
        { letter: 'u', partOfWords: ['dug'] },
      ],
      [
        { letter: 'u', partOfWords: ['glue'] },
        null,
        null,
        null,
        { letter: 'g', partOfWords: ['dug'] },
      ],
      [{ letter: 'e', partOfWords: ['glue'] }, null, null, null, null],
    ],
    placedWords: ['glued', 'glue', 'duel', 'due', 'dug'],
  },
  {
    letters: 'oaggjn',
    grid: [
      [null, null, null, { letter: 'a', partOfWords: ['ago'] }],
      [
        { letter: 'g', partOfWords: ['gang', 'gong'] },
        { letter: 'a', partOfWords: ['gang'] },
        { letter: 'n', partOfWords: ['gang'] },
        { letter: 'g', partOfWords: ['gang', 'ago'] },
      ],
      [
        { letter: 'o', partOfWords: ['gong'] },
        null,
        null,
        { letter: 'o', partOfWords: ['ago'] },
      ],
      [{ letter: 'n', partOfWords: ['gong'] }, null, null, null],
      [
        { letter: 'g', partOfWords: ['gong', 'gag'] },
        { letter: 'a', partOfWords: ['gag'] },
        { letter: 'g', partOfWords: ['gag'] },
        null,
      ],
    ],
    placedWords: ['gang', 'gong', 'ago', 'gag'],
  },
  {
    letters: 'iublpr',
    grid: [
      [{ letter: 'p', partOfWords: ['pub'] }, null, null, null],
      [{ letter: 'u', partOfWords: ['pub'] }, null, null, null],
      [
        { letter: 'b', partOfWords: ['blur', 'pub'] },
        { letter: 'l', partOfWords: ['blur', 'lip'] },
        { letter: 'u', partOfWords: ['blur'] },
        { letter: 'r', partOfWords: ['blur', 'rip'] },
      ],
      [
        null,
        { letter: 'i', partOfWords: ['lip'] },
        null,
        { letter: 'i', partOfWords: ['rip'] },
      ],
      [
        null,
        { letter: 'p', partOfWords: ['lip'] },
        null,
        { letter: 'p', partOfWords: ['rip'] },
      ],
    ],
    placedWords: ['blur', 'pub', 'lip', 'rip'],
  },
  {
    letters: 'aikytc',
    grid: [
      [
        { letter: 't', partOfWords: ['tick'] },
        null,
        { letter: 't', partOfWords: ['tic'] },
        { letter: 'i', partOfWords: ['icy', 'tic'] },
        { letter: 'c', partOfWords: ['tic'] },
      ],
      [
        { letter: 'i', partOfWords: ['tick'] },
        null,
        null,
        { letter: 'c', partOfWords: ['icy'] },
        null,
      ],
      [
        { letter: 'c', partOfWords: ['city', 'tick'] },
        { letter: 'i', partOfWords: ['city'] },
        { letter: 't', partOfWords: ['city', 'tack'] },
        { letter: 'y', partOfWords: ['city', 'icy'] },
        null,
      ],
      [
        { letter: 'k', partOfWords: ['tick'] },
        null,
        { letter: 'a', partOfWords: ['tack'] },
        null,
        null,
      ],
      [
        null,
        { letter: 'a', partOfWords: ['act'] },
        { letter: 'c', partOfWords: ['tack', 'act'] },
        { letter: 't', partOfWords: ['act'] },
        null,
      ],
      [null, null, { letter: 'k', partOfWords: ['tack'] }, null, null],
    ],
    placedWords: ['city', 'tick', 'tack', 'act', 'icy', 'tic'],
  },
  {
    letters: 'uatbrx',
    grid: [
      [
        null,
        null,
        null,
        null,
        { letter: 'b', partOfWords: ['bat', 'bra'] },
        { letter: 'r', partOfWords: ['bra'] },
        { letter: 'a', partOfWords: ['bra'] },
      ],
      [
        { letter: 'b', partOfWords: ['but', 'bar'] },
        { letter: 'u', partOfWords: ['but'] },
        { letter: 't', partOfWords: ['but', 'tax'] },
        null,
        { letter: 'a', partOfWords: ['bat'] },
        null,
        null,
      ],
      [
        { letter: 'a', partOfWords: ['bar'] },
        null,
        { letter: 'a', partOfWords: ['tax', 'art'] },
        { letter: 'r', partOfWords: ['art'] },
        { letter: 't', partOfWords: ['art', 'bat'] },
        null,
        null,
      ],
      [
        { letter: 'r', partOfWords: ['bar'] },
        null,
        { letter: 'x', partOfWords: ['tax'] },
        null,
        null,
        null,
        null,
      ],
    ],
    placedWords: ['but', 'tax', 'art', 'bar', 'bat', 'bra'],
  },
  {
    letters: 'aedwqx',
    grid: [
      [null, null, null, { letter: 'a', partOfWords: ['axe'] }, null],
      [null, null, null, { letter: 'x', partOfWords: ['axe'] }, null],
      [
        null,
        { letter: 'a', partOfWords: ['awe'] },
        { letter: 'w', partOfWords: ['wax', 'awe'] },
        { letter: 'e', partOfWords: ['awe', 'axe'] },
        null,
      ],
      [null, null, { letter: 'a', partOfWords: ['wax'] }, null, null],
      [
        { letter: 'w', partOfWords: ['waxed', 'wade'] },
        { letter: 'a', partOfWords: ['waxed'] },
        { letter: 'x', partOfWords: ['waxed', 'wax'] },
        { letter: 'e', partOfWords: ['waxed'] },
        { letter: 'd', partOfWords: ['waxed', 'dew'] },
      ],
      [
        { letter: 'a', partOfWords: ['wade'] },
        null,
        null,
        null,
        { letter: 'e', partOfWords: ['dew'] },
      ],
      [
        { letter: 'd', partOfWords: ['wade'] },
        null,
        null,
        null,
        { letter: 'w', partOfWords: ['dew'] },
      ],
      [{ letter: 'e', partOfWords: ['wade'] }, null, null, null, null],
    ],
    placedWords: ['waxed', 'wade', 'wax', 'awe', 'axe', 'dew'],
  },
  {
    letters: 'aeljsv',
    grid: [
      [
        null,
        null,
        { letter: 's', partOfWords: ['save'] },
        null,
        { letter: 's', partOfWords: ['seal', 'sea'] },
        { letter: 'e', partOfWords: ['sea'] },
        { letter: 'a', partOfWords: ['sea'] },
      ],
      [
        { letter: 's', partOfWords: ['slave', 'sale'] },
        { letter: 'l', partOfWords: ['slave'] },
        { letter: 'a', partOfWords: ['slave', 'save'] },
        { letter: 'v', partOfWords: ['slave'] },
        { letter: 'e', partOfWords: ['slave', 'seal'] },
        null,
        null,
      ],
      [
        { letter: 'a', partOfWords: ['sale'] },
        null,
        { letter: 'v', partOfWords: ['save'] },
        null,
        { letter: 'a', partOfWords: ['seal', 'ale'] },
        { letter: 'l', partOfWords: ['ale'] },
        { letter: 'e', partOfWords: ['ale'] },
      ],
      [
        { letter: 'l', partOfWords: ['sale'] },
        null,
        { letter: 'e', partOfWords: ['save'] },
        null,
        { letter: 'l', partOfWords: ['seal'] },
        null,
        null,
      ],
      [
        { letter: 'e', partOfWords: ['sale'] },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    ],
    placedWords: ['slave', 'sale', 'save', 'seal', 'sea', 'ale'],
  },
  {
    letters: 'eurvtg',
    grid: [
      [
        null,
        { letter: 'u', partOfWords: ['urge'] },
        null,
        { letter: 'g', partOfWords: ['get', 'gut'] },
        { letter: 'u', partOfWords: ['gut'] },
        { letter: 't', partOfWords: ['gut'] },
      ],
      [
        { letter: 't', partOfWords: ['true'] },
        { letter: 'r', partOfWords: ['true', 'urge'] },
        { letter: 'u', partOfWords: ['true'] },
        { letter: 'e', partOfWords: ['true', 'get'] },
        null,
        null,
      ],
      [
        null,
        { letter: 'g', partOfWords: ['urge'] },
        null,
        { letter: 't', partOfWords: ['get', 'tug'] },
        { letter: 'u', partOfWords: ['tug'] },
        { letter: 'g', partOfWords: ['tug'] },
      ],
      [
        { letter: 'v', partOfWords: ['vet'] },
        { letter: 'e', partOfWords: ['urge', 'vet'] },
        { letter: 't', partOfWords: ['vet'] },
        null,
        null,
        null,
      ],
    ],
    placedWords: ['true', 'urge', 'get', 'gut', 'vet', 'tug'],
  },
  {
    letters: 'eotmsm',
    grid: [
      [
        null,
        null,
        { letter: 's', partOfWords: ['stem'] },
        null,
        { letter: 's', partOfWords: ['set'] },
        null,
      ],
      [
        { letter: 'm', partOfWords: ['most'] },
        null,
        { letter: 't', partOfWords: ['stem', 'toes'] },
        { letter: 'o', partOfWords: ['toes'] },
        { letter: 'e', partOfWords: ['toes', 'set'] },
        { letter: 's', partOfWords: ['toes'] },
      ],
      [
        { letter: 'o', partOfWords: ['most'] },
        null,
        { letter: 'e', partOfWords: ['stem'] },
        null,
        { letter: 't', partOfWords: ['set'] },
        null,
      ],
      [
        { letter: 's', partOfWords: ['some', 'most'] },
        { letter: 'o', partOfWords: ['some'] },
        { letter: 'm', partOfWords: ['some', 'stem'] },
        { letter: 'e', partOfWords: ['some'] },
        null,
        null,
      ],
      [{ letter: 't', partOfWords: ['most'] }, null, null, null, null, null],
    ],
    placedWords: ['some', 'most', 'stem', 'toes', 'set'],
  },
  {
    letters: 'oubnpn',
    grid: [
      [{ letter: 'n', partOfWords: ['noun'] }, null, null, null],
      [{ letter: 'o', partOfWords: ['noun'] }, null, null, null],
      [
        { letter: 'u', partOfWords: ['upon', 'noun'] },
        { letter: 'p', partOfWords: ['upon'] },
        { letter: 'o', partOfWords: ['upon'] },
        { letter: 'n', partOfWords: ['upon', 'nun'] },
      ],
      [
        { letter: 'n', partOfWords: ['noun'] },
        null,
        null,
        { letter: 'u', partOfWords: ['nun'] },
      ],
      [
        null,
        { letter: 'b', partOfWords: ['bun'] },
        { letter: 'u', partOfWords: ['bun'] },
        { letter: 'n', partOfWords: ['nun', 'bun'] },
      ],
    ],
    placedWords: ['upon', 'noun', 'nun', 'bun'],
  },
  {
    letters: 'iudqht',
    grid: [
      [null, null, { letter: 'h', partOfWords: ['hit'] }],
      [
        { letter: 'q', partOfWords: ['quit', 'quid'] },
        { letter: 'u', partOfWords: ['quit'] },
        { letter: 'i', partOfWords: ['quit', 'hit'] },
      ],
      [
        { letter: 'u', partOfWords: ['quid'] },
        null,
        { letter: 't', partOfWords: ['hit'] },
      ],
      [{ letter: 'i', partOfWords: ['quid'] }, null, null],
      [{ letter: 'd', partOfWords: ['quid'] }, null, null],
    ],
    placedWords: ['quit', 'quid', 'hit'],
  },
  {
    letters: 'oavbrf',
    grid: [
      [
        null,
        { letter: 'b', partOfWords: ['bravo'] },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 'r', partOfWords: ['bravo'] },
        null,
        { letter: 'b', partOfWords: ['boar'] },
        null,
        null,
        null,
      ],
      [
        { letter: 'f', partOfWords: ['favor'] },
        { letter: 'a', partOfWords: ['favor', 'bravo'] },
        { letter: 'v', partOfWords: ['favor'] },
        { letter: 'o', partOfWords: ['favor', 'boar'] },
        { letter: 'r', partOfWords: ['favor'] },
        null,
        null,
      ],
      [
        null,
        { letter: 'v', partOfWords: ['bravo'] },
        null,
        { letter: 'a', partOfWords: ['boar'] },
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 'o', partOfWords: ['bravo'] },
        null,
        { letter: 'r', partOfWords: ['boar', 'rob'] },
        { letter: 'o', partOfWords: ['rob'] },
        { letter: 'b', partOfWords: ['rob', 'bra'] },
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 'r', partOfWords: ['bra'] },
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'o', partOfWords: ['oar'] },
        { letter: 'a', partOfWords: ['bra', 'oar'] },
        { letter: 'r', partOfWords: ['oar'] },
      ],
    ],
    placedWords: ['favor', 'bravo', 'boar', 'rob', 'bra', 'oar'],
  },
  {
    letters: 'iavfnd',
    grid: [
      [null, null, null, { letter: 'v', partOfWords: ['van'] }],
      [null, null, null, { letter: 'a', partOfWords: ['van'] }],
      [
        { letter: 'v', partOfWords: ['vain'] },
        { letter: 'a', partOfWords: ['avid', 'vain'] },
        { letter: 'i', partOfWords: ['vain'] },
        { letter: 'n', partOfWords: ['vain', 'van'] },
      ],
      [null, { letter: 'v', partOfWords: ['avid'] }, null, null],
      [
        { letter: 'f', partOfWords: ['find'] },
        { letter: 'i', partOfWords: ['find', 'avid'] },
        { letter: 'n', partOfWords: ['find'] },
        { letter: 'd', partOfWords: ['find'] },
      ],
      [null, { letter: 'd', partOfWords: ['avid'] }, null, null],
    ],
    placedWords: ['find', 'avid', 'vain', 'van'],
  },
]
