export const combos = [
  {
    letters: 'iartpl',
    grid: [
      [
        null,
        null,
        { letter: 'a', partOfWords: ['apt'] },
        { letter: 'p', partOfWords: ['pit', 'apt'] },
        { letter: 't', partOfWords: ['apt'] },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'i', partOfWords: ['pit'] },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 'p', partOfWords: ['pair', 'pat'] },
        { letter: 'a', partOfWords: ['pat'] },
        { letter: 't', partOfWords: ['pat', 'pit'] },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 'a', partOfWords: ['pair'] },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 'i', partOfWords: ['pair'] },
        null,
        { letter: 'p', partOfWords: ['part'] },
        null,
        null,
        { letter: 't', partOfWords: ['trap'] },
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 't', partOfWords: ['trial', 'trail'] },
        { letter: 'r', partOfWords: ['trial', 'pair'] },
        { letter: 'i', partOfWords: ['trial'] },
        { letter: 'a', partOfWords: ['trial', 'part'] },
        { letter: 'l', partOfWords: ['trial'] },
        null,
        { letter: 'r', partOfWords: ['trap'] },
        null,
        { letter: 'a', partOfWords: ['art'] },
        null,
        { letter: 'l', partOfWords: ['lip'] },
      ],
      [
        { letter: 'r', partOfWords: ['trail'] },
        null,
        null,
        { letter: 'r', partOfWords: ['part'] },
        null,
        null,
        { letter: 'a', partOfWords: ['trap', 'air'] },
        { letter: 'i', partOfWords: ['air'] },
        { letter: 'r', partOfWords: ['air', 'art'] },
        null,
        { letter: 'i', partOfWords: ['lip'] },
      ],
      [
        { letter: 'a', partOfWords: ['trail'] },
        null,
        null,
        { letter: 't', partOfWords: ['part', 'trip'] },
        { letter: 'r', partOfWords: ['trip', 'rail'] },
        { letter: 'i', partOfWords: ['trip'] },
        { letter: 'p', partOfWords: ['trip', 'trap'] },
        null,
        { letter: 't', partOfWords: ['art', 'tip'] },
        { letter: 'i', partOfWords: ['tip'] },
        { letter: 'p', partOfWords: ['tip', 'lip'] },
      ],
      [
        { letter: 'i', partOfWords: ['trail'] },
        null,
        null,
        null,
        { letter: 'a', partOfWords: ['rail'] },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'l', partOfWords: ['trail'] },
        null,
        { letter: 't', partOfWords: ['tail', 'tap'] },
        { letter: 'a', partOfWords: ['tail'] },
        { letter: 'i', partOfWords: ['rail', 'tail'] },
        { letter: 'l', partOfWords: ['tail'] },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'a', partOfWords: ['tap'] },
        null,
        { letter: 'l', partOfWords: ['rail'] },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'l', partOfWords: ['lap'] },
        { letter: 'a', partOfWords: ['lap', 'alt'] },
        { letter: 'p', partOfWords: ['tap', 'lap'] },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 'l', partOfWords: ['alt'] },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 't', partOfWords: ['alt'] },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    ],
    placedWords: [
      'trial',
      'trail',
      'part',
      'trip',
      'pair',
      'rail',
      'tail',
      'trap',
      'air',
      'art',
      'pat',
      'tap',
      'tip',
      'pit',
      'lap',
      'lip',
      'apt',
      'alt',
    ],
  },
  {
    letters: 'aeztsn',
    grid: [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'a', partOfWords: ['ants'] },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 't', partOfWords: ['tens'] },
        { letter: 'e', partOfWords: ['tens'] },
        { letter: 'n', partOfWords: ['ants', 'tens'] },
        { letter: 's', partOfWords: ['tens'] },
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 't', partOfWords: ['ants'] },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'z', partOfWords: ['zest'] },
        { letter: 'e', partOfWords: ['eats', 'zest'] },
        { letter: 's', partOfWords: ['zest', 'ants'] },
        { letter: 't', partOfWords: ['zest', 'ten'] },
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 'a', partOfWords: ['eats'] },
        null,
        { letter: 'e', partOfWords: ['ten'] },
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 't', partOfWords: ['eats'] },
        null,
        { letter: 'n', partOfWords: ['ten'] },
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'n', partOfWords: ['neat', 'nest'] },
        { letter: 'e', partOfWords: ['nest'] },
        { letter: 's', partOfWords: ['nest', 'eats'] },
        { letter: 't', partOfWords: ['nest'] },
        null,
        null,
      ],
      [
        null,
        { letter: 'a', partOfWords: ['ate'] },
        { letter: 't', partOfWords: ['ate'] },
        { letter: 'e', partOfWords: ['neat', 'ate'] },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 's', partOfWords: ['seat'] },
        null,
        null,
        { letter: 'a', partOfWords: ['neat', 'ante'] },
        { letter: 'n', partOfWords: ['ante'] },
        { letter: 't', partOfWords: ['ante'] },
        { letter: 'e', partOfWords: ['ante', 'eat'] },
        null,
        null,
      ],
      [
        { letter: 'e', partOfWords: ['east', 'seat'] },
        { letter: 'a', partOfWords: ['east'] },
        { letter: 's', partOfWords: ['east', 'sane'] },
        { letter: 't', partOfWords: ['east', 'neat'] },
        null,
        null,
        { letter: 'a', partOfWords: ['eat'] },
        null,
        { letter: 't', partOfWords: ['tan'] },
      ],
      [
        { letter: 'a', partOfWords: ['seat'] },
        null,
        { letter: 'a', partOfWords: ['sane'] },
        null,
        null,
        null,
        { letter: 't', partOfWords: ['eat', 'tea'] },
        { letter: 'e', partOfWords: ['tea'] },
        { letter: 'a', partOfWords: ['tea', 'tan'] },
      ],
      [
        { letter: 't', partOfWords: ['seat'] },
        null,
        { letter: 'n', partOfWords: ['sane', 'nets'] },
        { letter: 'e', partOfWords: ['nets'] },
        { letter: 't', partOfWords: ['nets'] },
        { letter: 's', partOfWords: ['nets', 'set'] },
        null,
        null,
        { letter: 'n', partOfWords: ['tan'] },
      ],
      [
        null,
        null,
        { letter: 'e', partOfWords: ['sane'] },
        null,
        null,
        { letter: 'e', partOfWords: ['set'] },
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'n', partOfWords: ['net'] },
        { letter: 'e', partOfWords: ['net'] },
        { letter: 't', partOfWords: ['set', 'net'] },
        null,
        null,
        null,
      ],
    ],
    placedWords: [
      'east',
      'seat',
      'neat',
      'nest',
      'eats',
      'sane',
      'ante',
      'zest',
      'ants',
      'nets',
      'tens',
      'set',
      'net',
      'ten',
      'eat',
      'tea',
      'ate',
      'tan',
    ],
  },
  {
    letters: 'eaycps',
    grid: [
      [
        null,
        null,
        null,
        null,
        { letter: 's', partOfWords: ['say'] },
        { letter: 'a', partOfWords: ['apes', 'say'] },
        { letter: 'y', partOfWords: ['say'] },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 'p', partOfWords: ['apes'] },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'c', partOfWords: ['cape'] },
        null,
        { letter: 'e', partOfWords: ['apes'] },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'p', partOfWords: ['pays'] },
        { letter: 'a', partOfWords: ['cape', 'pays'] },
        { letter: 'y', partOfWords: ['pays'] },
        { letter: 's', partOfWords: ['pays', 'apes'] },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'p', partOfWords: ['cape'] },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'p', partOfWords: ['paces', 'pace'] },
        { letter: 'a', partOfWords: ['pace'] },
        { letter: 'c', partOfWords: ['pace'] },
        { letter: 'e', partOfWords: ['pace', 'cape'] },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'a', partOfWords: ['paces'] },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'c', partOfWords: ['paces'] },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'e', partOfWords: ['paces'] },
        null,
        { letter: 'c', partOfWords: ['case'] },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 's', partOfWords: ['space', 'paces'] },
        { letter: 'p', partOfWords: ['space'] },
        { letter: 'a', partOfWords: ['space', 'case'] },
        { letter: 'c', partOfWords: ['space'] },
        { letter: 'e', partOfWords: ['space', 'easy'] },
        null,
        { letter: 'a', partOfWords: ['ape'] },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 's', partOfWords: ['case'] },
        null,
        { letter: 'a', partOfWords: ['easy'] },
        null,
        { letter: 'p', partOfWords: ['ape'] },
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'a', partOfWords: ['ace'] },
        { letter: 'c', partOfWords: ['ace'] },
        { letter: 'e', partOfWords: ['case', 'ace'] },
        null,
        { letter: 's', partOfWords: ['easy', 'spec'] },
        { letter: 'p', partOfWords: ['spec'] },
        { letter: 'e', partOfWords: ['spec', 'ape'] },
        { letter: 'c', partOfWords: ['spec', 'caps'] },
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'y', partOfWords: ['easy'] },
        null,
        null,
        { letter: 'a', partOfWords: ['caps'] },
        null,
        { letter: 'p', partOfWords: ['pay'] },
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'p', partOfWords: ['caps', 'peas'] },
        { letter: 'e', partOfWords: ['peas'] },
        { letter: 'a', partOfWords: ['peas', 'pay'] },
        { letter: 's', partOfWords: ['peas'] },
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 'y', partOfWords: ['yes'] },
        { letter: 'e', partOfWords: ['yes'] },
        { letter: 's', partOfWords: ['caps', 'yes'] },
        null,
        { letter: 'y', partOfWords: ['pay'] },
        null,
      ],
    ],
    placedWords: [
      'space',
      'paces',
      'case',
      'easy',
      'pace',
      'cape',
      'spec',
      'pays',
      'caps',
      'apes',
      'peas',
      'say',
      'pay',
      'yes',
      'ace',
      'ape',
    ],
  },
  {
    letters: 'aognyr',
    grid: [
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 'r', partOfWords: ['ray'] },
        { letter: 'a', partOfWords: ['ray'] },
        { letter: 'y', partOfWords: ['yoga', 'ray'] },
        null,
        null,
      ],
      [
        { letter: 'o', partOfWords: ['organ'] },
        null,
        { letter: 'r', partOfWords: ['rag'] },
        { letter: 'a', partOfWords: ['rag'] },
        { letter: 'g', partOfWords: ['gray', 'rag'] },
        null,
        null,
        { letter: 'o', partOfWords: ['yoga', 'oar'] },
        { letter: 'a', partOfWords: ['oar'] },
        { letter: 'r', partOfWords: ['oar'] },
      ],
      [
        { letter: 'r', partOfWords: ['organ'] },
        null,
        null,
        null,
        { letter: 'r', partOfWords: ['gray', 'rang'] },
        { letter: 'a', partOfWords: ['rang'] },
        { letter: 'n', partOfWords: ['rang'] },
        { letter: 'g', partOfWords: ['rang', 'yoga'] },
        null,
        null,
      ],
      [
        { letter: 'g', partOfWords: ['organ'] },
        null,
        { letter: 'a', partOfWords: ['agony'] },
        null,
        { letter: 'a', partOfWords: ['gray'] },
        null,
        null,
        { letter: 'a', partOfWords: ['yoga', 'ago'] },
        { letter: 'g', partOfWords: ['ago'] },
        { letter: 'o', partOfWords: ['ago'] },
      ],
      [
        { letter: 'a', partOfWords: ['angry', 'organ'] },
        { letter: 'n', partOfWords: ['angry'] },
        { letter: 'g', partOfWords: ['angry', 'agony'] },
        { letter: 'r', partOfWords: ['angry'] },
        { letter: 'y', partOfWords: ['angry', 'gray'] },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'n', partOfWords: ['organ'] },
        null,
        { letter: 'o', partOfWords: ['agony'] },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'n', partOfWords: ['agony'] },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'y', partOfWords: ['agony', 'yarn'] },
        { letter: 'a', partOfWords: ['yarn', 'any'] },
        { letter: 'r', partOfWords: ['yarn'] },
        { letter: 'n', partOfWords: ['yarn', 'nor'] },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'n', partOfWords: ['any'] },
        null,
        { letter: 'o', partOfWords: ['nor'] },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'y', partOfWords: ['any'] },
        null,
        { letter: 'r', partOfWords: ['nor', 'ran'] },
        { letter: 'a', partOfWords: ['ran'] },
        { letter: 'n', partOfWords: ['ran'] },
        null,
        null,
      ],
    ],
    placedWords: [
      'angry',
      'organ',
      'agony',
      'gray',
      'rang',
      'yarn',
      'yoga',
      'any',
      'ago',
      'nor',
      'ran',
      'ray',
      'rag',
      'oar',
    ],
  },
  {
    letters: 'aemtss',
    grid: [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'e', partOfWords: ['eat'] },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'm', partOfWords: ['meta'] },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'a', partOfWords: ['eat'] },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 't', partOfWords: ['tea'] },
        { letter: 'e', partOfWords: ['meta', 'tea'] },
        { letter: 'a', partOfWords: ['tea'] },
        null,
        null,
        null,
        null,
        { letter: 'm', partOfWords: ['mesa', 'mats'] },
        { letter: 'a', partOfWords: ['mats'] },
        { letter: 't', partOfWords: ['mats', 'eat'] },
        { letter: 's', partOfWords: ['mats'] },
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 't', partOfWords: ['meta'] },
        null,
        { letter: 's', partOfWords: ['seat'] },
        null,
        null,
        null,
        { letter: 'e', partOfWords: ['mesa'] },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 'm', partOfWords: ['mate'] },
        { letter: 'a', partOfWords: ['mate', 'meta'] },
        { letter: 't', partOfWords: ['mate'] },
        { letter: 'e', partOfWords: ['seat', 'mate'] },
        null,
        { letter: 'm', partOfWords: ['mass', 'mess'] },
        { letter: 'e', partOfWords: ['mess'] },
        { letter: 's', partOfWords: ['mess', 'mesa'] },
        { letter: 's', partOfWords: ['mess'] },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 's', partOfWords: ['steam'] },
        null,
        null,
        null,
        { letter: 'a', partOfWords: ['seat'] },
        null,
        { letter: 'a', partOfWords: ['mass'] },
        null,
        { letter: 'a', partOfWords: ['mesa'] },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 't', partOfWords: ['steam'] },
        null,
        { letter: 'm', partOfWords: ['masse', 'mates'] },
        { letter: 'a', partOfWords: ['mates'] },
        { letter: 't', partOfWords: ['mates', 'seat'] },
        { letter: 'e', partOfWords: ['mates'] },
        { letter: 's', partOfWords: ['mates', 'mass'] },
        null,
        null,
        null,
        { letter: 'm', partOfWords: ['mast', 'met'] },
        { letter: 'e', partOfWords: ['met'] },
        { letter: 't', partOfWords: ['met'] },
        null,
        null,
      ],
      [
        { letter: 'e', partOfWords: ['steam'] },
        null,
        { letter: 'a', partOfWords: ['masse'] },
        null,
        null,
        null,
        { letter: 's', partOfWords: ['mass'] },
        null,
        null,
        null,
        { letter: 'a', partOfWords: ['mast'] },
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'a', partOfWords: ['asset', 'steam'] },
        { letter: 's', partOfWords: ['asset'] },
        { letter: 's', partOfWords: ['asset', 'masse'] },
        { letter: 'e', partOfWords: ['asset'] },
        { letter: 't', partOfWords: ['asset'] },
        null,
        null,
        null,
        { letter: 't', partOfWords: ['team'] },
        null,
        { letter: 's', partOfWords: ['mast', 'sets'] },
        { letter: 'e', partOfWords: ['sets'] },
        { letter: 't', partOfWords: ['sets'] },
        { letter: 's', partOfWords: ['sets', 'sea'] },
        null,
      ],
      [
        { letter: 'm', partOfWords: ['steam'] },
        null,
        { letter: 's', partOfWords: ['masse'] },
        null,
        null,
        null,
        null,
        { letter: 'm', partOfWords: ['meat'] },
        { letter: 'e', partOfWords: ['team', 'meat'] },
        { letter: 'a', partOfWords: ['meat'] },
        { letter: 't', partOfWords: ['meat', 'mast'] },
        null,
        null,
        { letter: 'e', partOfWords: ['sea'] },
        null,
      ],
      [
        null,
        { letter: 's', partOfWords: ['seams', 'seats'] },
        { letter: 'e', partOfWords: ['masse', 'seams'] },
        { letter: 'a', partOfWords: ['seams'] },
        { letter: 'm', partOfWords: ['seams'] },
        { letter: 's', partOfWords: ['seams', 'stems'] },
        null,
        null,
        { letter: 'a', partOfWords: ['team'] },
        null,
        null,
        null,
        null,
        { letter: 'a', partOfWords: ['sea'] },
        null,
      ],
      [
        null,
        { letter: 'e', partOfWords: ['seats'] },
        null,
        null,
        null,
        { letter: 't', partOfWords: ['stems', 'teams'] },
        { letter: 'e', partOfWords: ['teams'] },
        { letter: 'a', partOfWords: ['teams'] },
        { letter: 'm', partOfWords: ['teams', 'team'] },
        { letter: 's', partOfWords: ['teams'] },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 's', partOfWords: ['same'] },
        { letter: 'a', partOfWords: ['seats', 'same'] },
        { letter: 'm', partOfWords: ['same'] },
        { letter: 'e', partOfWords: ['same', 'eats'] },
        null,
        { letter: 'e', partOfWords: ['stems'] },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 't', partOfWords: ['seats'] },
        null,
        { letter: 'a', partOfWords: ['eats'] },
        null,
        { letter: 'm', partOfWords: ['stems', 'meats'] },
        { letter: 'e', partOfWords: ['meats'] },
        { letter: 'a', partOfWords: ['meats'] },
        { letter: 't', partOfWords: ['meats'] },
        { letter: 's', partOfWords: ['meats', 'stem'] },
        null,
        null,
        { letter: 's', partOfWords: ['seas', 'sat'] },
        { letter: 'a', partOfWords: ['sat'] },
        { letter: 't', partOfWords: ['sat'] },
      ],
      [
        null,
        { letter: 's', partOfWords: ['seats'] },
        null,
        { letter: 't', partOfWords: ['eats'] },
        null,
        { letter: 's', partOfWords: ['stems'] },
        null,
        null,
        null,
        { letter: 't', partOfWords: ['stem', 'tame'] },
        { letter: 'a', partOfWords: ['tame'] },
        { letter: 'm', partOfWords: ['tame'] },
        { letter: 'e', partOfWords: ['tame', 'seas'] },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 's', partOfWords: ['eats'] },
        null,
        null,
        null,
        null,
        null,
        { letter: 'e', partOfWords: ['stem'] },
        null,
        null,
        { letter: 'a', partOfWords: ['seas'] },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 's', partOfWords: ['seam', 'set'] },
        { letter: 'e', partOfWords: ['seam'] },
        { letter: 'a', partOfWords: ['seam', 'ate'] },
        { letter: 'm', partOfWords: ['stem', 'seam'] },
        null,
        null,
        { letter: 's', partOfWords: ['seas'] },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'e', partOfWords: ['set'] },
        null,
        { letter: 't', partOfWords: ['ate'] },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'm', partOfWords: ['mat'] },
        { letter: 'a', partOfWords: ['mat'] },
        { letter: 't', partOfWords: ['set', 'mat'] },
        null,
        { letter: 'e', partOfWords: ['ate'] },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    ],
    placedWords: [
      'asset',
      'steam',
      'masse',
      'seams',
      'seats',
      'stems',
      'mates',
      'teams',
      'meats',
      'same',
      'team',
      'mass',
      'seat',
      'meat',
      'mess',
      'stem',
      'mate',
      'mesa',
      'eats',
      'mast',
      'tame',
      'seam',
      'sets',
      'meta',
      'seas',
      'mats',
      'set',
      'met',
      'sea',
      'sat',
      'eat',
      'tea',
      'ate',
      'mat',
    ],
  },
  {
    letters: 'aeqtry',
    grid: [
      [
        null,
        null,
        null,
        null,
        { letter: 'e', partOfWords: ['ear'] },
        null,
        { letter: 't', partOfWords: ['try'] },
        null,
        { letter: 'r', partOfWords: ['rye'] },
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'a', partOfWords: ['ear'] },
        null,
        { letter: 'r', partOfWords: ['try', 'ray'] },
        { letter: 'a', partOfWords: ['ray'] },
        { letter: 'y', partOfWords: ['ray', 'rye'] },
      ],
      [
        null,
        { letter: 'r', partOfWords: ['rate'] },
        null,
        { letter: 't', partOfWords: ['tear', 'tray'] },
        { letter: 'r', partOfWords: ['tray', 'ear'] },
        { letter: 'a', partOfWords: ['tray'] },
        { letter: 'y', partOfWords: ['tray', 'try'] },
        null,
        { letter: 'e', partOfWords: ['rye'] },
      ],
      [
        null,
        { letter: 'a', partOfWords: ['rate'] },
        null,
        { letter: 'e', partOfWords: ['tear'] },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 't', partOfWords: ['rate'] },
        null,
        { letter: 'a', partOfWords: ['tear', 'art'] },
        { letter: 'r', partOfWords: ['art'] },
        { letter: 't', partOfWords: ['art', 'tea'] },
        null,
        null,
        null,
      ],
      [
        { letter: 'y', partOfWords: ['year', 'yet'] },
        { letter: 'e', partOfWords: ['year', 'rate'] },
        { letter: 'a', partOfWords: ['year', 'are'] },
        { letter: 'r', partOfWords: ['year', 'tear'] },
        null,
        { letter: 'e', partOfWords: ['tea'] },
        null,
        null,
        null,
      ],
      [
        { letter: 'e', partOfWords: ['yet'] },
        null,
        { letter: 'r', partOfWords: ['are'] },
        null,
        null,
        { letter: 'a', partOfWords: ['tea'] },
        null,
        null,
        null,
      ],
      [
        { letter: 't', partOfWords: ['yet'] },
        null,
        { letter: 'e', partOfWords: ['are', 'eat'] },
        { letter: 'a', partOfWords: ['eat', 'ate'] },
        { letter: 't', partOfWords: ['eat'] },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 't', partOfWords: ['ate'] },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'e', partOfWords: ['ate'] },
        null,
        null,
        null,
        null,
        null,
      ],
    ],
    placedWords: [
      'year',
      'rate',
      'tear',
      'tray',
      'are',
      'yet',
      'art',
      'try',
      'eat',
      'tea',
      'ray',
      'ear',
      'ate',
      'rye',
    ],
  },
  {
    letters: 'ietpfl',
    grid: [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'l', partOfWords: ['lit', 'lip'] },
        { letter: 'i', partOfWords: ['lip'] },
        { letter: 'p', partOfWords: ['lip'] },
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'i', partOfWords: ['lit'] },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'p', partOfWords: ['pet', 'pit'] },
        { letter: 'i', partOfWords: ['pit'] },
        { letter: 't', partOfWords: ['pit', 'lit'] },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 't', partOfWords: ['tile', 'tie'] },
        { letter: 'i', partOfWords: ['tie'] },
        { letter: 'e', partOfWords: ['tie', 'pet'] },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 'i', partOfWords: ['tile'] },
        null,
        { letter: 't', partOfWords: ['pet'] },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'f', partOfWords: ['file'] },
        null,
        { letter: 'l', partOfWords: ['tile'] },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'p', partOfWords: ['pile'] },
        { letter: 'i', partOfWords: ['file', 'pile'] },
        { letter: 'l', partOfWords: ['pile'] },
        { letter: 'e', partOfWords: ['pile', 'tile'] },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'l', partOfWords: ['file'] },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'l', partOfWords: ['life', 'left'] },
        { letter: 'i', partOfWords: ['life'] },
        { letter: 'f', partOfWords: ['life', 'felt'] },
        { letter: 'e', partOfWords: ['life', 'file'] },
        null,
        { letter: 'f', partOfWords: ['fit'] },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'e', partOfWords: ['left'] },
        null,
        { letter: 'e', partOfWords: ['felt'] },
        null,
        null,
        { letter: 'i', partOfWords: ['fit'] },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'f', partOfWords: ['left'] },
        null,
        { letter: 'l', partOfWords: ['felt', 'lift'] },
        { letter: 'i', partOfWords: ['lift'] },
        { letter: 'f', partOfWords: ['lift', 'flip'] },
        { letter: 't', partOfWords: ['lift', 'fit'] },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 't', partOfWords: ['left'] },
        null,
        { letter: 't', partOfWords: ['felt'] },
        null,
        { letter: 'l', partOfWords: ['flip'] },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'l', partOfWords: ['lie'] },
        { letter: 'i', partOfWords: ['flip', 'lie'] },
        { letter: 'e', partOfWords: ['lie'] },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'p', partOfWords: ['flip'] },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    ],
    placedWords: [
      'life',
      'left',
      'felt',
      'file',
      'lift',
      'pile',
      'flip',
      'tile',
      'fit',
      'lie',
      'tie',
      'pet',
      'pit',
      'lit',
      'lip',
    ],
  },
  {
    letters: 'eospdn',
    grid: [
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 's', partOfWords: ['son'] },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 'o', partOfWords: ['son'] },
        null,
        null,
        { letter: 'p', partOfWords: ['pens', 'pen'] },
        { letter: 'e', partOfWords: ['pen'] },
        { letter: 'n', partOfWords: ['pen'] },
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 'n', partOfWords: ['nose', 'son'] },
        { letter: 'o', partOfWords: ['open', 'nose'] },
        { letter: 's', partOfWords: ['nose'] },
        { letter: 'e', partOfWords: ['nose', 'pens'] },
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'p', partOfWords: ['open'] },
        null,
        { letter: 'n', partOfWords: ['pens', 'nods'] },
        { letter: 'o', partOfWords: ['nods'] },
        { letter: 'd', partOfWords: ['nods', 'den'] },
        { letter: 's', partOfWords: ['nods'] },
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'e', partOfWords: ['open'] },
        null,
        { letter: 's', partOfWords: ['pens'] },
        null,
        { letter: 'e', partOfWords: ['den'] },
        null,
      ],
      [
        { letter: 'n', partOfWords: ['nodes'] },
        null,
        null,
        { letter: 'o', partOfWords: ['opens'] },
        { letter: 'p', partOfWords: ['posed', 'opens'] },
        { letter: 'e', partOfWords: ['opens'] },
        { letter: 'n', partOfWords: ['opens', 'open'] },
        { letter: 's', partOfWords: ['opens'] },
        null,
        null,
        { letter: 'n', partOfWords: ['den'] },
        null,
      ],
      [
        { letter: 'o', partOfWords: ['nodes'] },
        null,
        { letter: 'd', partOfWords: ['done'] },
        null,
        { letter: 'o', partOfWords: ['posed'] },
        null,
        null,
        null,
        null,
        { letter: 'o', partOfWords: ['ode'] },
        null,
        null,
      ],
      [
        { letter: 'd', partOfWords: ['nodes'] },
        null,
        { letter: 'o', partOfWords: ['done'] },
        null,
        { letter: 's', partOfWords: ['posed', 'send'] },
        { letter: 'e', partOfWords: ['send'] },
        { letter: 'n', partOfWords: ['send'] },
        { letter: 'd', partOfWords: ['send', 'dose'] },
        null,
        { letter: 'd', partOfWords: ['ode'] },
        null,
        null,
      ],
      [
        { letter: 'e', partOfWords: ['nodes'] },
        null,
        { letter: 'n', partOfWords: ['done'] },
        null,
        { letter: 'e', partOfWords: ['posed'] },
        null,
        null,
        { letter: 'o', partOfWords: ['dose', 'ones'] },
        { letter: 'n', partOfWords: ['ones'] },
        { letter: 'e', partOfWords: ['ones', 'ode'] },
        { letter: 's', partOfWords: ['ones'] },
        null,
      ],
      [
        { letter: 's', partOfWords: ['spend', 'nodes'] },
        { letter: 'p', partOfWords: ['spend', 'ponds'] },
        { letter: 'e', partOfWords: ['spend', 'done'] },
        { letter: 'n', partOfWords: ['spend'] },
        { letter: 'd', partOfWords: ['spend', 'posed'] },
        null,
        null,
        { letter: 's', partOfWords: ['dose'] },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 'o', partOfWords: ['ponds'] },
        null,
        null,
        null,
        null,
        null,
        { letter: 'e', partOfWords: ['dose', 'ends'] },
        { letter: 'n', partOfWords: ['ends'] },
        { letter: 'd', partOfWords: ['ends'] },
        { letter: 's', partOfWords: ['ends'] },
        null,
      ],
      [
        null,
        { letter: 'n', partOfWords: ['ponds'] },
        null,
        null,
        null,
        null,
        { letter: 'n', partOfWords: ['nod'] },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 'd', partOfWords: ['ponds', 'does'] },
        { letter: 'o', partOfWords: ['does'] },
        { letter: 'e', partOfWords: ['does'] },
        { letter: 's', partOfWords: ['does', 'sped'] },
        null,
        { letter: 'o', partOfWords: ['nod'] },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 's', partOfWords: ['ponds'] },
        null,
        null,
        { letter: 'p', partOfWords: ['sped', 'pods'] },
        { letter: 'o', partOfWords: ['pods'] },
        { letter: 'd', partOfWords: ['pods', 'nod'] },
        { letter: 's', partOfWords: ['pods'] },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'o', partOfWords: ['one'] },
        { letter: 'n', partOfWords: ['one'] },
        { letter: 'e', partOfWords: ['sped', 'one'] },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'd', partOfWords: ['sped', 'dope'] },
        { letter: 'o', partOfWords: ['dope'] },
        { letter: 'p', partOfWords: ['dope'] },
        { letter: 'e', partOfWords: ['dope', 'end'] },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'n', partOfWords: ['end'] },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 'p', partOfWords: ['pod'] },
        { letter: 'o', partOfWords: ['pod'] },
        { letter: 'd', partOfWords: ['end', 'pod'] },
        null,
        null,
        null,
        null,
      ],
    ],
    placedWords: [
      'spend',
      'nodes',
      'ponds',
      'posed',
      'opens',
      'does',
      'open',
      'done',
      'send',
      'nose',
      'dose',
      'sped',
      'dope',
      'pens',
      'nods',
      'pods',
      'ends',
      'ones',
      'one',
      'end',
      'son',
      'pen',
      'nod',
      'den',
      'pod',
      'ode',
    ],
  },
  {
    letters: 'oedrnv',
    grid: [
      [
        null,
        null,
        null,
        null,
        { letter: 'd', partOfWords: ['den'] },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'e', partOfWords: ['den'] },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'n', partOfWords: ['nod', 'den'] },
        { letter: 'o', partOfWords: ['ore', 'nod'] },
        { letter: 'd', partOfWords: ['nod'] },
        null,
        null,
      ],
      [
        { letter: 'd', partOfWords: ['drove'] },
        null,
        null,
        null,
        null,
        { letter: 'r', partOfWords: ['ore'] },
        null,
        null,
        null,
      ],
      [
        { letter: 'r', partOfWords: ['drove'] },
        null,
        { letter: 'd', partOfWords: ['done', 'dove'] },
        { letter: 'o', partOfWords: ['dove'] },
        { letter: 'v', partOfWords: ['dove'] },
        { letter: 'e', partOfWords: ['dove', 'ore'] },
        null,
        null,
        null,
      ],
      [
        { letter: 'o', partOfWords: ['drove'] },
        null,
        { letter: 'o', partOfWords: ['done'] },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'v', partOfWords: ['vendor', 'drove'] },
        { letter: 'e', partOfWords: ['vendor'] },
        { letter: 'n', partOfWords: ['vendor', 'done'] },
        { letter: 'd', partOfWords: ['vendor'] },
        { letter: 'o', partOfWords: ['vendor', 'over'] },
        { letter: 'r', partOfWords: ['vendor'] },
        null,
        null,
        null,
      ],
      [
        { letter: 'e', partOfWords: ['drove'] },
        null,
        { letter: 'e', partOfWords: ['done'] },
        null,
        { letter: 'v', partOfWords: ['over'] },
        null,
        { letter: 'e', partOfWords: ['end'] },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'e', partOfWords: ['over'] },
        null,
        { letter: 'n', partOfWords: ['end'] },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'r', partOfWords: ['over', 'rode'] },
        { letter: 'o', partOfWords: ['rode', 'one'] },
        { letter: 'd', partOfWords: ['rode', 'end'] },
        { letter: 'e', partOfWords: ['rode'] },
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 'n', partOfWords: ['one'] },
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'r', partOfWords: ['red', 'rod'] },
        { letter: 'e', partOfWords: ['one', 'red'] },
        { letter: 'd', partOfWords: ['red', 'doe'] },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'o', partOfWords: ['rod'] },
        null,
        { letter: 'o', partOfWords: ['doe', 'ode'] },
        { letter: 'd', partOfWords: ['ode'] },
        { letter: 'e', partOfWords: ['ode'] },
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'd', partOfWords: ['rod'] },
        null,
        { letter: 'e', partOfWords: ['doe'] },
        null,
        null,
      ],
    ],
    placedWords: [
      'vendor',
      'drove',
      'over',
      'done',
      'rode',
      'dove',
      'one',
      'end',
      'red',
      'ore',
      'rod',
      'nod',
      'doe',
      'den',
      'ode',
    ],
  },
  {
    letters: 'iewdhn',
    grid: [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'w', partOfWords: ['win'] },
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'i', partOfWords: ['win'] },
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'h', partOfWords: ['hide', 'hind'] },
        { letter: 'i', partOfWords: ['hind'] },
        { letter: 'n', partOfWords: ['hind', 'win'] },
        { letter: 'd', partOfWords: ['hind'] },
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'i', partOfWords: ['hide'] },
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'd', partOfWords: ['hide', 'die'] },
        { letter: 'i', partOfWords: ['die'] },
        { letter: 'e', partOfWords: ['die'] },
        null,
      ],
      [
        { letter: 'd', partOfWords: ['dew'] },
        { letter: 'e', partOfWords: ['dew'] },
        { letter: 'w', partOfWords: ['wide', 'dew'] },
        null,
        { letter: 'w', partOfWords: ['wind', 'wine'] },
        { letter: 'i', partOfWords: ['wine'] },
        { letter: 'n', partOfWords: ['wine'] },
        { letter: 'e', partOfWords: ['wine', 'hide'] },
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'i', partOfWords: ['wide'] },
        null,
        { letter: 'i', partOfWords: ['wind'] },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'w', partOfWords: ['widen', 'when'] },
        { letter: 'i', partOfWords: ['widen'] },
        { letter: 'd', partOfWords: ['widen', 'wide'] },
        { letter: 'e', partOfWords: ['widen'] },
        { letter: 'n', partOfWords: ['widen', 'wind'] },
        null,
        { letter: 'e', partOfWords: ['end'] },
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'h', partOfWords: ['when'] },
        null,
        { letter: 'e', partOfWords: ['wide'] },
        null,
        { letter: 'd', partOfWords: ['wind', 'dine'] },
        { letter: 'i', partOfWords: ['dine'] },
        { letter: 'n', partOfWords: ['dine', 'end'] },
        { letter: 'e', partOfWords: ['dine'] },
        null,
        null,
        null,
      ],
      [
        { letter: 'e', partOfWords: ['when'] },
        null,
        null,
        null,
        null,
        null,
        { letter: 'd', partOfWords: ['end'] },
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'n', partOfWords: ['when', 'new'] },
        { letter: 'e', partOfWords: ['new'] },
        { letter: 'w', partOfWords: ['new', 'wed'] },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'e', partOfWords: ['wed'] },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'h', partOfWords: ['hid', 'hen'] },
        { letter: 'i', partOfWords: ['hid'] },
        { letter: 'd', partOfWords: ['wed', 'hid'] },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'e', partOfWords: ['hen'] },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'n', partOfWords: ['hen'] },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    ],
    placedWords: [
      'widen',
      'when',
      'wide',
      'wind',
      'wine',
      'hide',
      'dine',
      'hind',
      'new',
      'end',
      'win',
      'die',
      'wed',
      'hid',
      'hen',
      'dew',
    ],
  },
  {
    letters: 'eamdtt',
    grid: [
      [
        null,
        null,
        null,
        null,
        { letter: 'a', partOfWords: ['ate'] },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 't', partOfWords: ['ate'] },
        null,
        { letter: 'm', partOfWords: ['mad', 'mat'] },
        { letter: 'a', partOfWords: ['mat'] },
        { letter: 't', partOfWords: ['mat'] },
      ],
      [
        { letter: 't', partOfWords: ['team'] },
        null,
        null,
        { letter: 'm', partOfWords: ['mate', 'meta'] },
        { letter: 'e', partOfWords: ['meta', 'ate'] },
        { letter: 't', partOfWords: ['meta'] },
        { letter: 'a', partOfWords: ['meta', 'mad'] },
        null,
        null,
      ],
      [
        { letter: 'e', partOfWords: ['team'] },
        null,
        null,
        { letter: 'a', partOfWords: ['mate'] },
        null,
        null,
        { letter: 'd', partOfWords: ['mad', 'dam'] },
        { letter: 'a', partOfWords: ['dam'] },
        { letter: 'm', partOfWords: ['dam'] },
      ],
      [
        { letter: 'a', partOfWords: ['team'] },
        null,
        null,
        { letter: 't', partOfWords: ['mate', 'tea'] },
        { letter: 'e', partOfWords: ['tea'] },
        { letter: 'a', partOfWords: ['tea'] },
        null,
        null,
        null,
      ],
      [
        { letter: 'm', partOfWords: ['made', 'team'] },
        { letter: 'a', partOfWords: ['made'] },
        { letter: 'd', partOfWords: ['made', 'date'] },
        { letter: 'e', partOfWords: ['made', 'mate'] },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'a', partOfWords: ['date'] },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 't', partOfWords: ['date'] },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 'm', partOfWords: ['meat', 'mead'] },
        { letter: 'e', partOfWords: ['date', 'meat'] },
        { letter: 'a', partOfWords: ['meat'] },
        { letter: 't', partOfWords: ['meat', 'tame'] },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 'e', partOfWords: ['mead'] },
        null,
        null,
        { letter: 'a', partOfWords: ['tame'] },
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'e', partOfWords: ['eat'] },
        { letter: 'a', partOfWords: ['mead', 'eat'] },
        { letter: 't', partOfWords: ['eat'] },
        null,
        { letter: 'm', partOfWords: ['tame', 'met'] },
        { letter: 'e', partOfWords: ['met'] },
        { letter: 't', partOfWords: ['met', 'ted'] },
        null,
        null,
      ],
      [
        null,
        { letter: 'd', partOfWords: ['mead'] },
        null,
        null,
        { letter: 'e', partOfWords: ['tame'] },
        null,
        { letter: 'e', partOfWords: ['ted'] },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'd', partOfWords: ['ted'] },
        null,
        null,
      ],
    ],
    placedWords: [
      'made',
      'team',
      'date',
      'meat',
      'mate',
      'mead',
      'tame',
      'meta',
      'met',
      'eat',
      'tea',
      'mad',
      'ted',
      'ate',
      'dam',
      'mat',
    ],
  },
  {
    letters: 'eifldv',
    grid: [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'd', partOfWords: ['dive'] },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'v', partOfWords: ['veil'] },
        { letter: 'e', partOfWords: ['veil'] },
        { letter: 'i', partOfWords: ['dive', 'veil'] },
        { letter: 'l', partOfWords: ['veil'] },
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'v', partOfWords: ['dive'] },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'f', partOfWords: ['file'] },
        { letter: 'i', partOfWords: ['file'] },
        { letter: 'l', partOfWords: ['live', 'file'] },
        { letter: 'e', partOfWords: ['file', 'dive'] },
        null,
        null,
      ],
      [
        null,
        { letter: 'd', partOfWords: ['devil'] },
        null,
        null,
        null,
        { letter: 'i', partOfWords: ['live'] },
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 'e', partOfWords: ['devil'] },
        null,
        { letter: 'f', partOfWords: ['filed', 'five'] },
        { letter: 'i', partOfWords: ['five'] },
        { letter: 'v', partOfWords: ['five', 'live'] },
        { letter: 'e', partOfWords: ['five'] },
        null,
        null,
      ],
      [
        null,
        { letter: 'v', partOfWords: ['devil'] },
        null,
        { letter: 'i', partOfWords: ['filed'] },
        null,
        { letter: 'e', partOfWords: ['live'] },
        null,
        null,
        null,
      ],
      [
        { letter: 'f', partOfWords: ['field'] },
        { letter: 'i', partOfWords: ['field', 'devil'] },
        { letter: 'e', partOfWords: ['field'] },
        { letter: 'l', partOfWords: ['field', 'filed'] },
        { letter: 'd', partOfWords: ['field'] },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 'l', partOfWords: ['devil'] },
        null,
        { letter: 'e', partOfWords: ['filed'] },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'i', partOfWords: ['idle'] },
        { letter: 'd', partOfWords: ['filed', 'idle'] },
        { letter: 'l', partOfWords: ['idle', 'lied'] },
        { letter: 'e', partOfWords: ['idle'] },
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'i', partOfWords: ['lied'] },
        null,
        { letter: 'l', partOfWords: ['lie', 'lid'] },
        { letter: 'i', partOfWords: ['lid'] },
        { letter: 'd', partOfWords: ['lid'] },
      ],
      [
        null,
        { letter: 'v', partOfWords: ['vile'] },
        { letter: 'i', partOfWords: ['vile'] },
        { letter: 'l', partOfWords: ['vile'] },
        { letter: 'e', partOfWords: ['lied', 'vile'] },
        null,
        { letter: 'i', partOfWords: ['lie'] },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'd', partOfWords: ['lied', 'die'] },
        { letter: 'i', partOfWords: ['die'] },
        { letter: 'e', partOfWords: ['die', 'lie'] },
        null,
        null,
      ],
    ],
    placedWords: [
      'field',
      'devil',
      'filed',
      'five',
      'live',
      'file',
      'idle',
      'dive',
      'lied',
      'veil',
      'vile',
      'die',
      'lie',
      'lid',
    ],
  },
]
