export const combos = [
  {
    letters: 'eagxdn',
    words: ['aged', 'dean', 'and', 'end', 'age', 'den', 'axe'],
    grid: [
      [null, null, null, null, null, { letter: 'a', partOfWord: 'axe' }],
      [null, null, null, null, null, { letter: 'x', partOfWord: 'axe' }],
      [
        { letter: 'd', partOfWord: 'dean' },
        null,
        null,
        { letter: 'a', partOfWord: 'age' },
        { letter: 'g', partOfWord: 'age' },
        { letter: 'e', partOfWord: 'axe' },
      ],
      [
        { letter: 'e', partOfWord: 'dean' },
        null,
        null,
        { letter: 'n', partOfWord: 'and' },
        null,
        null,
      ],
      [
        { letter: 'a', partOfWord: 'dean' },
        { letter: 'g', partOfWord: 'aged' },
        { letter: 'e', partOfWord: 'end' },
        { letter: 'd', partOfWord: 'and' },
        null,
        null,
      ],
      [
        { letter: 'n', partOfWord: 'dean' },
        null,
        { letter: 'n', partOfWord: 'end' },
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'd', partOfWord: 'den' },
        { letter: 'e', partOfWord: 'den' },
        { letter: 'n', partOfWord: 'den' },
        null,
      ],
    ],
    placedWords: 7,
  },
  {
    letters: 'oapbdt',
    words: [
      'adopt',
      'boat',
      'atop',
      'toad',
      'top',
      'bad',
      'pat',
      'tap',
      'dot',
      'pot',
      'bat',
      'opt',
      'pad',
      'apt',
      'tab',
      'pod',
      'dab',
      'ado',
      'oat',
      'bot',
    ],
    grid: [
      [
        null,
        null,
        null,
        { letter: 'b', partOfWord: 'bot' },
        { letter: 'o', partOfWord: 'bot' },
        { letter: 't', partOfWord: 'bot' },
      ],
      [null, null, null, null, { letter: 'a', partOfWord: 'oat' }, null],
      [
        { letter: 'b', partOfWord: 'boat' },
        null,
        { letter: 'a', partOfWord: 'apt' },
        { letter: 'p', partOfWord: 'apt' },
        { letter: 't', partOfWord: 'oat' },
        null,
      ],
      [
        { letter: 'o', partOfWord: 'boat' },
        null,
        { letter: 't', partOfWord: 'atop' },
        null,
        null,
        null,
      ],
      [
        { letter: 'a', partOfWord: 'boat' },
        { letter: 'd', partOfWord: 'adopt' },
        { letter: 'o', partOfWord: 'atop' },
        { letter: 'p', partOfWord: 'adopt' },
        { letter: 't', partOfWord: 'toad' },
        null,
      ],
      [
        { letter: 't', partOfWord: 'boat' },
        null,
        { letter: 'p', partOfWord: 'atop' },
        null,
        { letter: 'o', partOfWord: 'toad' },
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'b', partOfWord: 'bad' },
        { letter: 'a', partOfWord: 'bad' },
        { letter: 'd', partOfWord: 'bad' },
      ],
      [null, null, null, null, { letter: 'd', partOfWord: 'toad' }, null],
    ],
    placedWords: 8,
  },
  {
    letters: 'oexphn',
    words: ['phone', 'open', 'hope', 'oxen', 'one', 'pen', 'hop', 'hen'],
    grid: [
      [
        null,
        null,
        null,
        { letter: 'h', partOfWord: 'hop' },
        { letter: 'o', partOfWord: 'hop' },
        { letter: 'p', partOfWord: 'hop' },
        null,
      ],
      [null, null, null, null, null, { letter: 'e', partOfWord: 'pen' }, null],
      [
        null,
        null,
        null,
        null,
        { letter: 'o', partOfWord: 'one' },
        { letter: 'n', partOfWord: 'pen' },
        { letter: 'e', partOfWord: 'one' },
      ],
      [
        { letter: 'o', partOfWord: 'open' },
        null,
        { letter: 'h', partOfWord: 'hope' },
        null,
        { letter: 'x', partOfWord: 'oxen' },
        null,
        null,
      ],
      [
        { letter: 'p', partOfWord: 'open' },
        { letter: 'h', partOfWord: 'phone' },
        { letter: 'o', partOfWord: 'hope' },
        { letter: 'n', partOfWord: 'phone' },
        { letter: 'e', partOfWord: 'oxen' },
        null,
        null,
      ],
      [
        { letter: 'e', partOfWord: 'open' },
        null,
        { letter: 'p', partOfWord: 'hope' },
        null,
        { letter: 'n', partOfWord: 'oxen' },
        null,
        null,
      ],
      [
        { letter: 'n', partOfWord: 'open' },
        null,
        { letter: 'e', partOfWord: 'hope' },
        null,
        null,
        null,
        null,
      ],
    ],
    placedWords: 7,
  },
  {
    letters: 'eehrtp',
    words: [
      'there',
      'three',
      'ether',
      'here',
      'tree',
      'peer',
      'thee',
      'the',
      'her',
      'per',
      'pet',
      'tee',
    ],
    grid: [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'p', partOfWord: 'pet' },
        { letter: 'e', partOfWord: 'pet' },
        { letter: 't', partOfWord: 'tee' },
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'e', partOfWord: 'per' },
        null,
        { letter: 'e', partOfWord: 'tee' },
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'h', partOfWord: 'her' },
        { letter: 'e', partOfWord: 'her' },
        { letter: 'r', partOfWord: 'per' },
        null,
        { letter: 'e', partOfWord: 'tee' },
      ],
      [
        { letter: 't', partOfWord: 'three' },
        { letter: 'h', partOfWord: 'there' },
        { letter: 'e', partOfWord: 'ether' },
        { letter: 'r', partOfWord: 'there' },
        { letter: 'e', partOfWord: 'here' },
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'h', partOfWord: 'three' },
        null,
        { letter: 't', partOfWord: 'ether' },
        null,
        { letter: 'r', partOfWord: 'here' },
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'r', partOfWord: 'three' },
        null,
        { letter: 'h', partOfWord: 'ether' },
        null,
        { letter: 'e', partOfWord: 'here' },
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'e', partOfWord: 'three' },
        null,
        { letter: 'e', partOfWord: 'ether' },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'e', partOfWord: 'three' },
        null,
        { letter: 'r', partOfWord: 'ether' },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    ],
    placedWords: 8,
  },
  {
    letters: 'uotpvw',
    words: ['out', 'two', 'put', 'top', 'pot', 'opt', 'tow', 'vow'],
    grid: [
      [null, null, null, null, null, { letter: 'v', partOfWord: 'vow' }],
      [null, null, null, null, null, { letter: 'o', partOfWord: 'vow' }],
      [
        null,
        null,
        null,
        { letter: 't', partOfWord: 'tow' },
        { letter: 'o', partOfWord: 'tow' },
        { letter: 'w', partOfWord: 'vow' },
      ],
      [null, null, null, null, { letter: 'p', partOfWord: 'opt' }, null],
      [
        { letter: 't', partOfWord: 'two' },
        null,
        { letter: 'p', partOfWord: 'pot' },
        { letter: 'o', partOfWord: 'pot' },
        { letter: 't', partOfWord: 'opt' },
        null,
      ],
      [
        { letter: 'w', partOfWord: 'two' },
        null,
        { letter: 'u', partOfWord: 'put' },
        null,
        null,
        null,
      ],
      [
        { letter: 'o', partOfWord: 'two' },
        { letter: 'u', partOfWord: 'out' },
        { letter: 't', partOfWord: 'put' },
        null,
        null,
        null,
      ],
    ],
    placedWords: 7,
  },
  {
    letters: 'oetnjg',
    words: [
      'note',
      'gone',
      'tone',
      'not',
      'one',
      'get',
      'got',
      'net',
      'ten',
      'jet',
      'ton',
      'ego',
      'toe',
    ],
    grid: [
      [
        null,
        null,
        { letter: 't', partOfWord: 'ton' },
        { letter: 'o', partOfWord: 'ton' },
        { letter: 'n', partOfWord: 'ton' },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'e', partOfWord: 'ego' },
        { letter: 'g', partOfWord: 'ego' },
        { letter: 'o', partOfWord: 'ego' },
      ],
      [
        { letter: 'g', partOfWord: 'gone' },
        null,
        { letter: 'g', partOfWord: 'got' },
        { letter: 'o', partOfWord: 'got' },
        { letter: 't', partOfWord: 'net' },
        null,
        null,
      ],
      [
        { letter: 'o', partOfWord: 'gone' },
        null,
        null,
        { letter: 'n', partOfWord: 'one' },
        null,
        null,
        null,
      ],
      [
        { letter: 'n', partOfWord: 'gone' },
        { letter: 'o', partOfWord: 'note' },
        { letter: 't', partOfWord: 'tone' },
        { letter: 'e', partOfWord: 'one' },
        null,
        null,
        null,
      ],
      [
        { letter: 'e', partOfWord: 'gone' },
        null,
        { letter: 'o', partOfWord: 'tone' },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'n', partOfWord: 'not' },
        { letter: 'o', partOfWord: 'not' },
        { letter: 't', partOfWord: 'ten' },
        null,
        null,
      ],
      [
        { letter: 't', partOfWord: 'toe' },
        { letter: 'o', partOfWord: 'toe' },
        { letter: 'e', partOfWord: 'toe' },
        null,
        { letter: 'e', partOfWord: 'ten' },
        null,
        null,
      ],
      [null, null, null, null, { letter: 'n', partOfWord: 'ten' }, null, null],
    ],
    placedWords: 11,
  },
  {
    letters: 'eorrlw',
    words: ['lower', 'role', 'wore', 'lore', 'low', 'row', 'ore', 'owl', 'woe'],
    grid: [
      [null, null, null, null, null, { letter: 'o', partOfWord: 'owl' }, null],
      [
        null,
        null,
        null,
        { letter: 'l', partOfWord: 'low' },
        { letter: 'o', partOfWord: 'low' },
        { letter: 'w', partOfWord: 'owl' },
        null,
      ],
      [
        { letter: 'r', partOfWord: 'role' },
        null,
        null,
        { letter: 'o', partOfWord: 'lore' },
        null,
        { letter: 'l', partOfWord: 'owl' },
        null,
      ],
      [
        { letter: 'o', partOfWord: 'role' },
        null,
        null,
        { letter: 'r', partOfWord: 'lore' },
        null,
        null,
        null,
      ],
      [
        { letter: 'l', partOfWord: 'role' },
        { letter: 'o', partOfWord: 'lower' },
        { letter: 'w', partOfWord: 'wore' },
        { letter: 'e', partOfWord: 'lore' },
        { letter: 'r', partOfWord: 'row' },
        null,
        null,
      ],
      [
        { letter: 'e', partOfWord: 'role' },
        null,
        { letter: 'o', partOfWord: 'wore' },
        null,
        { letter: 'o', partOfWord: 'row' },
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'r', partOfWord: 'wore' },
        null,
        { letter: 'w', partOfWord: 'woe' },
        { letter: 'o', partOfWord: 'woe' },
        { letter: 'e', partOfWord: 'woe' },
      ],
      [
        { letter: 'o', partOfWord: 'ore' },
        { letter: 'r', partOfWord: 'ore' },
        { letter: 'e', partOfWord: 'ore' },
        null,
        null,
        null,
        null,
      ],
    ],
    placedWords: 9,
  },
  {
    letters: 'oakwht',
    words: [
      'what',
      'hawk',
      'oath',
      'thaw',
      'who',
      'two',
      'how',
      'hot',
      'hat',
      'oak',
      'tow',
      'oat',
    ],
    grid: [
      [
        { letter: 'h', partOfWord: 'hawk' },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'a', partOfWord: 'hawk' },
        null,
        { letter: 'o', partOfWord: 'oath' },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'w', partOfWord: 'hawk' },
        { letter: 'h', partOfWord: 'what' },
        { letter: 'a', partOfWord: 'oath' },
        { letter: 't', partOfWord: 'what' },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'k', partOfWord: 'hawk' },
        null,
        { letter: 't', partOfWord: 'oath' },
        null,
        null,
        null,
        { letter: 't', partOfWord: 'tow' },
        null,
        null,
      ],
      [
        null,
        { letter: 't', partOfWord: 'two' },
        { letter: 'h', partOfWord: 'thaw' },
        { letter: 'a', partOfWord: 'thaw' },
        { letter: 'w', partOfWord: 'who' },
        null,
        { letter: 'o', partOfWord: 'oat' },
        { letter: 'a', partOfWord: 'oat' },
        { letter: 't', partOfWord: 'oat' },
      ],
      [
        null,
        { letter: 'w', partOfWord: 'two' },
        null,
        null,
        { letter: 'h', partOfWord: 'how' },
        { letter: 'o', partOfWord: 'how' },
        { letter: 'w', partOfWord: 'tow' },
        null,
        null,
      ],
      [
        { letter: 'h', partOfWord: 'hat' },
        { letter: 'o', partOfWord: 'hot' },
        { letter: 't', partOfWord: 'hot' },
        null,
        { letter: 'o', partOfWord: 'who' },
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'a', partOfWord: 'hat' },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 't', partOfWord: 'hat' },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    ],
    placedWords: 11,
  },
  {
    letters: 'aicxrs',
    words: [
      'axis',
      'scar',
      'arcs',
      'airs',
      'cars',
      'six',
      'air',
      'car',
      'sir',
      'arc',
    ],
    grid: [
      [
        null,
        null,
        null,
        null,
        { letter: 'a', partOfWord: 'arc' },
        null,
        { letter: 's', partOfWord: 'sir' },
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'r', partOfWord: 'arc' },
        null,
        { letter: 'i', partOfWord: 'sir' },
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'c', partOfWord: 'arc' },
        { letter: 'a', partOfWord: 'car' },
        { letter: 'r', partOfWord: 'sir' },
      ],
      [null, null, null, null, null, { letter: 'i', partOfWord: 'air' }, null],
      [
        null,
        null,
        null,
        { letter: 'a', partOfWord: 'airs' },
        { letter: 'i', partOfWord: 'airs' },
        { letter: 'r', partOfWord: 'air' },
        { letter: 's', partOfWord: 'airs' },
      ],
      [
        { letter: 's', partOfWord: 'scar' },
        null,
        null,
        { letter: 'r', partOfWord: 'arcs' },
        null,
        null,
        null,
      ],
      [
        { letter: 'c', partOfWord: 'scar' },
        null,
        null,
        { letter: 'c', partOfWord: 'cars' },
        { letter: 'a', partOfWord: 'cars' },
        { letter: 'r', partOfWord: 'cars' },
        { letter: 's', partOfWord: 'six' },
      ],
      [
        { letter: 'a', partOfWord: 'scar' },
        { letter: 'x', partOfWord: 'axis' },
        { letter: 'i', partOfWord: 'axis' },
        { letter: 's', partOfWord: 'arcs' },
        null,
        null,
        { letter: 'i', partOfWord: 'six' },
      ],
      [
        { letter: 'r', partOfWord: 'scar' },
        null,
        null,
        null,
        null,
        null,
        { letter: 'x', partOfWord: 'six' },
      ],
    ],
    placedWords: 10,
  },
  {
    letters: 'aiwnrk',
    words: [
      'rain',
      'rank',
      'warn',
      'akin',
      'wink',
      'air',
      'war',
      'win',
      'ran',
      'raw',
      'ink',
      'kin',
    ],
    grid: [
      [
        null,
        { letter: 'r', partOfWord: 'raw' },
        { letter: 'a', partOfWord: 'raw' },
        { letter: 'w', partOfWord: 'raw' },
        null,
        { letter: 'w', partOfWord: 'wink' },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'a', partOfWord: 'akin' },
        { letter: 'k', partOfWord: 'akin' },
        { letter: 'i', partOfWord: 'wink' },
        { letter: 'n', partOfWord: 'akin' },
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'r', partOfWord: 'warn' },
        null,
        { letter: 'n', partOfWord: 'wink' },
        null,
        null,
      ],
      [
        { letter: 'r', partOfWord: 'rank' },
        { letter: 'a', partOfWord: 'rain' },
        { letter: 'i', partOfWord: 'ink' },
        { letter: 'n', partOfWord: 'warn' },
        null,
        { letter: 'k', partOfWord: 'kin' },
        { letter: 'i', partOfWord: 'kin' },
        { letter: 'n', partOfWord: 'kin' },
      ],
      [
        { letter: 'a', partOfWord: 'rank' },
        null,
        { letter: 'n', partOfWord: 'ink' },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'n', partOfWord: 'rank' },
        null,
        { letter: 'k', partOfWord: 'ink' },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'k', partOfWord: 'rank' },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    ],
    placedWords: 8,
  },
  {
    letters: 'eivjfl',
    words: [
      'life',
      'five',
      'live',
      'file',
      'evil',
      'veil',
      'vile',
      'lie',
      'vie',
    ],
    grid: [
      [null, null, null, null, { letter: 'v', partOfWord: 'vile' }, null, null],
      [null, null, null, null, { letter: 'i', partOfWord: 'vile' }, null, null],
      [null, null, null, null, { letter: 'l', partOfWord: 'vile' }, null, null],
      [
        null,
        { letter: 'f', partOfWord: 'file' },
        { letter: 'i', partOfWord: 'file' },
        { letter: 'l', partOfWord: 'file' },
        { letter: 'e', partOfWord: 'vile' },
        null,
        null,
      ],
      [null, null, null, { letter: 'i', partOfWord: 'live' }, null, null, null],
      [
        null,
        { letter: 'f', partOfWord: 'five' },
        null,
        { letter: 'v', partOfWord: 'veil' },
        { letter: 'e', partOfWord: 'veil' },
        { letter: 'i', partOfWord: 'veil' },
        { letter: 'l', partOfWord: 'veil' },
      ],
      [
        { letter: 'l', partOfWord: 'life' },
        { letter: 'i', partOfWord: 'five' },
        { letter: 'f', partOfWord: 'life' },
        { letter: 'e', partOfWord: 'live' },
        null,
        null,
        null,
      ],
      [null, { letter: 'v', partOfWord: 'five' }, null, null, null, null, null],
      [
        null,
        { letter: 'e', partOfWord: 'evil' },
        { letter: 'v', partOfWord: 'vie' },
        { letter: 'i', partOfWord: 'evil' },
        { letter: 'l', partOfWord: 'lie' },
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'i', partOfWord: 'vie' },
        null,
        { letter: 'i', partOfWord: 'lie' },
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'e', partOfWord: 'vie' },
        null,
        { letter: 'e', partOfWord: 'lie' },
        null,
        null,
      ],
    ],
    placedWords: 9,
  },
  {
    letters: 'eowxfd',
    words: [
      'owed',
      'few',
      'fox',
      'fed',
      'owe',
      'wed',
      'foe',
      'dew',
      'woe',
      'ode',
    ],
    grid: [
      [
        null,
        { letter: 'f', partOfWord: 'fox' },
        { letter: 'o', partOfWord: 'fox' },
        { letter: 'x', partOfWord: 'fox' },
        null,
        null,
      ],
      [null, { letter: 'e', partOfWord: 'few' }, null, null, null, null],
      [
        { letter: 'o', partOfWord: 'owe' },
        { letter: 'w', partOfWord: 'few' },
        { letter: 'e', partOfWord: 'owed' },
        { letter: 'd', partOfWord: 'dew' },
        null,
        null,
      ],
      [
        { letter: 'w', partOfWord: 'owe' },
        null,
        null,
        { letter: 'e', partOfWord: 'dew' },
        null,
        null,
      ],
      [
        { letter: 'e', partOfWord: 'owe' },
        null,
        null,
        { letter: 'w', partOfWord: 'woe' },
        { letter: 'o', partOfWord: 'ode' },
        { letter: 'e', partOfWord: 'woe' },
      ],
      [null, null, null, null, { letter: 'd', partOfWord: 'ode' }, null],
      [null, null, null, null, { letter: 'e', partOfWord: 'ode' }, null],
    ],
    placedWords: 7,
  },
  {
    letters: 'aefszc',
    words: ['cafes', 'faces', 'case', 'face', 'safe', 'cafe', 'sea', 'ace'],
    grid: [
      [null, null, null, null, { letter: 's', partOfWord: 'sea' }, null, null],
      [null, null, null, null, { letter: 'e', partOfWord: 'sea' }, null, null],
      [
        null,
        null,
        null,
        { letter: 'c', partOfWord: 'cafe' },
        { letter: 'a', partOfWord: 'sea' },
        { letter: 'f', partOfWord: 'cafe' },
        { letter: 'e', partOfWord: 'cafe' },
      ],
      [
        { letter: 'f', partOfWord: 'faces' },
        null,
        null,
        { letter: 'a', partOfWord: 'case' },
        null,
        null,
        null,
      ],
      [
        { letter: 'a', partOfWord: 'faces' },
        null,
        null,
        { letter: 's', partOfWord: 'case' },
        null,
        null,
        null,
      ],
      [
        { letter: 'c', partOfWord: 'faces' },
        { letter: 'a', partOfWord: 'cafes' },
        { letter: 'f', partOfWord: 'face' },
        { letter: 'e', partOfWord: 'case' },
        { letter: 's', partOfWord: 'safe' },
        null,
        null,
      ],
      [
        { letter: 'e', partOfWord: 'faces' },
        null,
        { letter: 'a', partOfWord: 'face' },
        null,
        { letter: 'a', partOfWord: 'ace' },
        { letter: 'c', partOfWord: 'ace' },
        { letter: 'e', partOfWord: 'ace' },
      ],
      [
        { letter: 's', partOfWord: 'faces' },
        null,
        { letter: 'c', partOfWord: 'face' },
        null,
        { letter: 'f', partOfWord: 'safe' },
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'e', partOfWord: 'face' },
        null,
        { letter: 'e', partOfWord: 'safe' },
        null,
        null,
      ],
    ],
    placedWords: 8,
  },
  {
    letters: 'aigdfp',
    words: ['paid', 'aid', 'gap', 'dip', 'pad', 'dig', 'fig', 'pig', 'fad'],
    grid: [
      [{ letter: 'g', partOfWord: 'gap' }, null, null, null, null, null],
      [{ letter: 'a', partOfWord: 'gap' }, null, null, null, null, null],
      [
        { letter: 'p', partOfWord: 'gap' },
        { letter: 'a', partOfWord: 'aid' },
        { letter: 'i', partOfWord: 'paid' },
        { letter: 'd', partOfWord: 'dip' },
        null,
        null,
      ],
      [
        null,
        { letter: 'i', partOfWord: 'aid' },
        null,
        { letter: 'i', partOfWord: 'dip' },
        null,
        null,
      ],
      [
        null,
        { letter: 'd', partOfWord: 'aid' },
        null,
        { letter: 'p', partOfWord: 'pad' },
        { letter: 'a', partOfWord: 'pad' },
        { letter: 'd', partOfWord: 'dig' },
      ],
      [null, null, null, null, null, { letter: 'i', partOfWord: 'dig' }],
      [
        null,
        null,
        null,
        { letter: 'f', partOfWord: 'fad' },
        { letter: 'i', partOfWord: 'fig' },
        { letter: 'g', partOfWord: 'fig' },
      ],
      [null, null, null, { letter: 'a', partOfWord: 'fad' }, null, null],
      [null, null, null, { letter: 'd', partOfWord: 'fad' }, null, null],
    ],
    placedWords: 8,
  },
  {
    letters: 'aessxp',
    words: [
      'pass',
      'apex',
      'axes',
      'seas',
      'peas',
      'apes',
      'sea',
      'spa',
      'sap',
      'axe',
      'pea',
      'ape',
    ],
    grid: [
      [{ letter: 's', partOfWord: 'sap' }, null, null, null, null, null, null],
      [{ letter: 'a', partOfWord: 'sap' }, null, null, null, null, null, null],
      [
        { letter: 'p', partOfWord: 'sap' },
        { letter: 'e', partOfWord: 'peas' },
        { letter: 'a', partOfWord: 'peas' },
        { letter: 's', partOfWord: 'peas' },
        null,
        null,
        null,
      ],
      [null, null, { letter: 'x', partOfWord: 'axes' }, null, null, null, null],
      [
        { letter: 'a', partOfWord: 'apex' },
        null,
        { letter: 'e', partOfWord: 'axes' },
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'p', partOfWord: 'apex' },
        { letter: 'a', partOfWord: 'pass' },
        { letter: 's', partOfWord: 'axes' },
        { letter: 's', partOfWord: 'seas' },
        null,
        null,
        null,
      ],
      [
        { letter: 'e', partOfWord: 'apex' },
        null,
        null,
        { letter: 'e', partOfWord: 'seas' },
        null,
        { letter: 's', partOfWord: 'sea' },
        null,
      ],
      [
        { letter: 'x', partOfWord: 'apex' },
        null,
        null,
        { letter: 'a', partOfWord: 'apes' },
        { letter: 'p', partOfWord: 'apes' },
        { letter: 'e', partOfWord: 'sea' },
        { letter: 's', partOfWord: 'apes' },
      ],
      [
        null,
        null,
        null,
        { letter: 's', partOfWord: 'seas' },
        null,
        { letter: 'a', partOfWord: 'sea' },
        null,
      ],
    ],
    placedWords: 8,
  },
  {
    letters: 'aoxgft',
    words: [
      'goat',
      'got',
      'ago',
      'tax',
      'fax',
      'fox',
      'fat',
      'tag',
      'fog',
      'oat',
    ],
    grid: [
      [
        null,
        null,
        { letter: 'f', partOfWord: 'fat' },
        { letter: 'a', partOfWord: 'fat' },
        { letter: 't', partOfWord: 'tag' },
      ],
      [
        null,
        null,
        { letter: 'o', partOfWord: 'fox' },
        null,
        { letter: 'a', partOfWord: 'tag' },
      ],
      [
        { letter: 'f', partOfWord: 'fax' },
        { letter: 'a', partOfWord: 'fax' },
        { letter: 'x', partOfWord: 'fox' },
        null,
        { letter: 'g', partOfWord: 'tag' },
      ],
      [null, { letter: 'g', partOfWord: 'ago' }, null, null, null],
      [
        { letter: 'g', partOfWord: 'got' },
        { letter: 'o', partOfWord: 'ago' },
        { letter: 'a', partOfWord: 'goat' },
        { letter: 't', partOfWord: 'tax' },
        null,
      ],
      [
        { letter: 'o', partOfWord: 'got' },
        null,
        null,
        { letter: 'a', partOfWord: 'tax' },
        null,
      ],
      [
        { letter: 't', partOfWord: 'got' },
        null,
        null,
        { letter: 'x', partOfWord: 'tax' },
        null,
      ],
    ],
    placedWords: 8,
  },
  {
    letters: 'eicdbh',
    words: ['hide', 'dice', 'bed', 'die', 'bid', 'ice', 'hid'],
    grid: [
      [null, null, null, null, null, { letter: 'h', partOfWord: 'hid' }],
      [null, null, null, null, null, { letter: 'i', partOfWord: 'hid' }],
      [
        null,
        { letter: 'd', partOfWord: 'dice' },
        null,
        { letter: 'b', partOfWord: 'bid' },
        { letter: 'i', partOfWord: 'bid' },
        { letter: 'd', partOfWord: 'hid' },
      ],
      [
        { letter: 'h', partOfWord: 'hide' },
        { letter: 'i', partOfWord: 'dice' },
        { letter: 'd', partOfWord: 'hide' },
        { letter: 'e', partOfWord: 'bed' },
        null,
        null,
      ],
      [
        null,
        { letter: 'c', partOfWord: 'dice' },
        null,
        { letter: 'd', partOfWord: 'die' },
        { letter: 'i', partOfWord: 'ice' },
        { letter: 'e', partOfWord: 'die' },
      ],
      [
        null,
        { letter: 'e', partOfWord: 'dice' },
        null,
        null,
        { letter: 'c', partOfWord: 'ice' },
        null,
      ],
      [null, null, null, null, { letter: 'e', partOfWord: 'ice' }, null],
    ],
    placedWords: 7,
  },
  {
    letters: 'eaxvrh',
    words: [
      'have',
      'hear',
      'hare',
      'vera',
      'are',
      'her',
      'era',
      'ear',
      'axe',
      'var',
    ],
    grid: [
      [null, null, null, null, null, { letter: 'e', partOfWord: 'ear' }],
      [null, null, null, null, null, { letter: 'a', partOfWord: 'ear' }],
      [
        null,
        { letter: 'v', partOfWord: 'vera' },
        null,
        { letter: 'h', partOfWord: 'her' },
        { letter: 'e', partOfWord: 'her' },
        { letter: 'r', partOfWord: 'ear' },
      ],
      [
        null,
        { letter: 'e', partOfWord: 'vera' },
        null,
        { letter: 'a', partOfWord: 'hare' },
        null,
        null,
      ],
      [
        null,
        { letter: 'r', partOfWord: 'vera' },
        null,
        { letter: 'r', partOfWord: 'hare' },
        null,
        null,
      ],
      [
        { letter: 'h', partOfWord: 'hear' },
        { letter: 'a', partOfWord: 'vera' },
        { letter: 'v', partOfWord: 'have' },
        { letter: 'e', partOfWord: 'hare' },
        null,
        null,
      ],
      [{ letter: 'e', partOfWord: 'hear' }, null, null, null, null, null],
      [
        { letter: 'a', partOfWord: 'are' },
        { letter: 'r', partOfWord: 'are' },
        { letter: 'e', partOfWord: 'era' },
        null,
        null,
        null,
      ],
      [
        { letter: 'r', partOfWord: 'hear' },
        null,
        { letter: 'r', partOfWord: 'era' },
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'a', partOfWord: 'axe' },
        { letter: 'x', partOfWord: 'axe' },
        { letter: 'e', partOfWord: 'axe' },
        null,
      ],
    ],
    placedWords: 9,
  },
  {
    letters: 'audsnm',
    words: [
      'sand',
      'dams',
      'and',
      'man',
      'sun',
      'sum',
      'sad',
      'mad',
      'mud',
      'dam',
    ],
    grid: [
      [null, null, null, null, { letter: 'm', partOfWord: 'mud' }],
      [
        { letter: 'd', partOfWord: 'dams' },
        null,
        null,
        null,
        { letter: 'u', partOfWord: 'mud' },
      ],
      [
        { letter: 'a', partOfWord: 'dams' },
        null,
        { letter: 'm', partOfWord: 'mad' },
        { letter: 'a', partOfWord: 'mad' },
        { letter: 'd', partOfWord: 'mud' },
      ],
      [
        { letter: 'm', partOfWord: 'dams' },
        null,
        { letter: 'a', partOfWord: 'man' },
        null,
        null,
      ],
      [
        { letter: 's', partOfWord: 'dams' },
        { letter: 'a', partOfWord: 'and' },
        { letter: 'n', partOfWord: 'man' },
        { letter: 'd', partOfWord: 'dam' },
        null,
      ],
      [
        null,
        { letter: 'n', partOfWord: 'and' },
        null,
        { letter: 'a', partOfWord: 'dam' },
        null,
      ],
      [
        null,
        { letter: 'd', partOfWord: 'and' },
        null,
        { letter: 'm', partOfWord: 'dam' },
        null,
      ],
    ],
    placedWords: 7,
  },
  {
    letters: 'aerxhz',
    words: ['hear', 'hare', 'haze', 'are', 'her', 'era', 'ear', 'axe'],
    grid: [
      [null, { letter: 'h', partOfWord: 'haze' }, null, null, null, null],
      [
        null,
        { letter: 'a', partOfWord: 'haze' },
        null,
        { letter: 'h', partOfWord: 'her' },
        null,
        null,
      ],
      [
        null,
        { letter: 'z', partOfWord: 'haze' },
        null,
        { letter: 'e', partOfWord: 'ear' },
        { letter: 'a', partOfWord: 'ear' },
        { letter: 'r', partOfWord: 'ear' },
      ],
      [
        { letter: 'h', partOfWord: 'hare' },
        { letter: 'e', partOfWord: 'haze' },
        { letter: 'a', partOfWord: 'are' },
        { letter: 'r', partOfWord: 'her' },
        null,
        null,
      ],
      [
        { letter: 'a', partOfWord: 'hare' },
        null,
        { letter: 'r', partOfWord: 'are' },
        null,
        null,
        null,
      ],
      [
        { letter: 'r', partOfWord: 'hare' },
        null,
        { letter: 'e', partOfWord: 'era' },
        { letter: 'r', partOfWord: 'era' },
        { letter: 'a', partOfWord: 'axe' },
        null,
      ],
      [
        { letter: 'e', partOfWord: 'hare' },
        null,
        null,
        null,
        { letter: 'x', partOfWord: 'axe' },
        null,
      ],
      [null, null, null, null, { letter: 'e', partOfWord: 'axe' }, null],
    ],
    placedWords: 8,
  },
  {
    letters: 'iakrzm',
    words: ['mark', 'air', 'arm', 'aim', 'ram', 'rim', 'mar'],
    grid: [
      [null, null, { letter: 'r', partOfWord: 'rim' }, null],
      [null, null, { letter: 'i', partOfWord: 'rim' }, null],
      [
        { letter: 'a', partOfWord: 'aim' },
        { letter: 'i', partOfWord: 'aim' },
        { letter: 'm', partOfWord: 'rim' },
        null,
      ],
      [{ letter: 'r', partOfWord: 'arm' }, null, null, null],
      [
        { letter: 'm', partOfWord: 'arm' },
        { letter: 'a', partOfWord: 'air' },
        { letter: 'r', partOfWord: 'mark' },
        { letter: 'k', partOfWord: 'mark' },
      ],
      [null, { letter: 'i', partOfWord: 'air' }, null, null],
      [
        null,
        { letter: 'r', partOfWord: 'ram' },
        { letter: 'a', partOfWord: 'ram' },
        { letter: 'm', partOfWord: 'mar' },
      ],
      [null, null, null, { letter: 'a', partOfWord: 'mar' }],
      [null, null, null, { letter: 'r', partOfWord: 'mar' }],
    ],
    placedWords: 7,
  },
  {
    letters: 'aibxdl',
    words: [
      'laid',
      'dial',
      'bail',
      'bald',
      'bad',
      'aid',
      'bid',
      'lab',
      'lid',
      'lad',
      'dab',
    ],
    grid: [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'b', partOfWord: 'bid' },
      ],
      [
        null,
        null,
        null,
        { letter: 'l', partOfWord: 'lab' },
        { letter: 'a', partOfWord: 'lab' },
        { letter: 'b', partOfWord: 'lab' },
        null,
        { letter: 'i', partOfWord: 'bid' },
      ],
      [
        { letter: 'd', partOfWord: 'dial' },
        null,
        null,
        null,
        null,
        { letter: 'a', partOfWord: 'aid' },
        { letter: 'i', partOfWord: 'aid' },
        { letter: 'd', partOfWord: 'bid' },
      ],
      [
        { letter: 'i', partOfWord: 'dial' },
        null,
        { letter: 'b', partOfWord: 'bald' },
        { letter: 'a', partOfWord: 'bald' },
        { letter: 'l', partOfWord: 'bald' },
        { letter: 'd', partOfWord: 'bad' },
        null,
        null,
      ],
      [
        { letter: 'a', partOfWord: 'dial' },
        null,
        { letter: 'a', partOfWord: 'bail' },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'l', partOfWord: 'dial' },
        { letter: 'a', partOfWord: 'laid' },
        { letter: 'i', partOfWord: 'bail' },
        { letter: 'd', partOfWord: 'laid' },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'l', partOfWord: 'bail' },
        null,
        null,
        null,
        null,
        null,
      ],
    ],
    placedWords: 8,
  },
  {
    letters: 'oanfdv',
    words: ['fond', 'nova', 'and', 'van', 'fan', 'nod', 'fad', 'ado'],
    grid: [
      [
        null,
        null,
        { letter: 'f', partOfWord: 'fan' },
        { letter: 'a', partOfWord: 'fan' },
        { letter: 'n', partOfWord: 'fan' },
      ],
      [
        null,
        { letter: 'n', partOfWord: 'nova' },
        null,
        { letter: 'n', partOfWord: 'and' },
        null,
      ],
      [
        { letter: 'f', partOfWord: 'fond' },
        { letter: 'o', partOfWord: 'nova' },
        { letter: 'n', partOfWord: 'fond' },
        { letter: 'd', partOfWord: 'and' },
        null,
      ],
      [null, { letter: 'v', partOfWord: 'nova' }, null, null, null],
      [
        { letter: 'v', partOfWord: 'van' },
        { letter: 'a', partOfWord: 'van' },
        { letter: 'n', partOfWord: 'nod' },
        null,
        null,
      ],
      [null, null, { letter: 'o', partOfWord: 'nod' }, null, null],
      [
        { letter: 'f', partOfWord: 'fad' },
        { letter: 'a', partOfWord: 'ado' },
        { letter: 'd', partOfWord: 'fad' },
        null,
        null,
      ],
      [null, { letter: 'd', partOfWord: 'ado' }, null, null, null],
      [null, { letter: 'o', partOfWord: 'ado' }, null, null, null],
    ],
    placedWords: 8,
  },
  {
    letters: 'eaqsyl',
    words: [
      'easy',
      'sale',
      'seal',
      'slay',
      'lays',
      'say',
      'yes',
      'sea',
      'lay',
      'ale',
      'sly',
    ],
    grid: [
      [
        { letter: 's', partOfWord: 'sale' },
        null,
        null,
        { letter: 's', partOfWord: 'say' },
        { letter: 'a', partOfWord: 'say' },
        { letter: 'y', partOfWord: 'yes' },
        null,
        null,
      ],
      [
        { letter: 'a', partOfWord: 'sale' },
        null,
        null,
        { letter: 'l', partOfWord: 'slay' },
        null,
        { letter: 'e', partOfWord: 'yes' },
        null,
        null,
      ],
      [
        { letter: 'l', partOfWord: 'sale' },
        null,
        null,
        { letter: 'a', partOfWord: 'slay' },
        null,
        { letter: 's', partOfWord: 'sly' },
        { letter: 'l', partOfWord: 'sly' },
        { letter: 'y', partOfWord: 'sly' },
      ],
      [
        { letter: 'e', partOfWord: 'sale' },
        { letter: 'a', partOfWord: 'easy' },
        { letter: 's', partOfWord: 'seal' },
        { letter: 'y', partOfWord: 'slay' },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'e', partOfWord: 'seal' },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 'l', partOfWord: 'lays' },
        { letter: 'a', partOfWord: 'lays' },
        { letter: 'y', partOfWord: 'lays' },
        { letter: 's', partOfWord: 'sea' },
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'l', partOfWord: 'seal' },
        null,
        { letter: 'e', partOfWord: 'sea' },
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'l', partOfWord: 'lay' },
        { letter: 'a', partOfWord: 'lay' },
        { letter: 'y', partOfWord: 'lay' },
        null,
        null,
      ],
    ],
    placedWords: 10,
  },
  {
    letters: 'oeprkk',
    words: ['poker', 'rope', 'pork', 'poke', 'pore', 'per', 'ore'],
    grid: [
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 'p', partOfWord: 'per' },
        { letter: 'e', partOfWord: 'per' },
        { letter: 'r', partOfWord: 'per' },
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 'o', partOfWord: 'pore' },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 'r', partOfWord: 'pore' },
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'p', partOfWord: 'poke' },
        { letter: 'o', partOfWord: 'poke' },
        { letter: 'k', partOfWord: 'poke' },
        { letter: 'e', partOfWord: 'pore' },
        null,
        null,
      ],
      [
        { letter: 'r', partOfWord: 'rope' },
        null,
        { letter: 'o', partOfWord: 'pork' },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'o', partOfWord: 'rope' },
        null,
        { letter: 'r', partOfWord: 'pork' },
        null,
        { letter: 'o', partOfWord: 'ore' },
        null,
        null,
        null,
      ],
      [
        { letter: 'p', partOfWord: 'rope' },
        { letter: 'o', partOfWord: 'poker' },
        { letter: 'k', partOfWord: 'pork' },
        { letter: 'e', partOfWord: 'poker' },
        { letter: 'r', partOfWord: 'ore' },
        null,
        null,
        null,
      ],
      [
        { letter: 'e', partOfWord: 'rope' },
        null,
        null,
        null,
        { letter: 'e', partOfWord: 'ore' },
        null,
        null,
        null,
      ],
    ],
    placedWords: 7,
  },
]
