export const combosHard = [
  {
    letters: 'iartpl',
    words: [
      'trial',
      'trail',
      'part',
      'trip',
      'pair',
      'rail',
      'tail',
      'trap',
      'liar',
      'air',
      'art',
      'pat',
      'tap',
      'par',
      'tip',
      'pit',
      'lit',
      'lap',
      'lip',
      'rat',
      'apt',
      'pal',
      'rap',
      'rip',
      'tar',
      'alt',
    ],
    grid: [
      [
        null,
        null,
        { letter: 'a', partOfWord: 'apt' },
        { letter: 'p', partOfWord: 'apt' },
        { letter: 't', partOfWord: 'apt' },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'i', partOfWord: 'pit' },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 'p', partOfWord: 'pat' },
        { letter: 'a', partOfWord: 'pat' },
        { letter: 't', partOfWord: 'pit' },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 'a', partOfWord: 'pair' },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 'i', partOfWord: 'pair' },
        null,
        { letter: 'p', partOfWord: 'part' },
        null,
        null,
        { letter: 't', partOfWord: 'trap' },
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 't', partOfWord: 'trail' },
        { letter: 'r', partOfWord: 'pair' },
        { letter: 'i', partOfWord: 'trial' },
        { letter: 'a', partOfWord: 'part' },
        { letter: 'l', partOfWord: 'trial' },
        null,
        { letter: 'r', partOfWord: 'trap' },
        null,
        { letter: 'a', partOfWord: 'art' },
        null,
        { letter: 'l', partOfWord: 'lip' },
      ],
      [
        { letter: 'r', partOfWord: 'trail' },
        null,
        null,
        { letter: 'r', partOfWord: 'part' },
        null,
        null,
        { letter: 'a', partOfWord: 'air' },
        { letter: 'i', partOfWord: 'air' },
        { letter: 'r', partOfWord: 'art' },
        null,
        { letter: 'i', partOfWord: 'lip' },
      ],
      [
        { letter: 'a', partOfWord: 'trail' },
        null,
        null,
        { letter: 't', partOfWord: 'trip' },
        { letter: 'r', partOfWord: 'rail' },
        { letter: 'i', partOfWord: 'trip' },
        { letter: 'p', partOfWord: 'trap' },
        null,
        { letter: 't', partOfWord: 'tip' },
        { letter: 'i', partOfWord: 'tip' },
        { letter: 'p', partOfWord: 'lip' },
      ],
      [
        { letter: 'i', partOfWord: 'trail' },
        null,
        null,
        null,
        { letter: 'a', partOfWord: 'rail' },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'l', partOfWord: 'trail' },
        null,
        { letter: 't', partOfWord: 'tap' },
        { letter: 'a', partOfWord: 'tail' },
        { letter: 'i', partOfWord: 'tail' },
        { letter: 'l', partOfWord: 'tail' },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'a', partOfWord: 'tap' },
        null,
        { letter: 'l', partOfWord: 'rail' },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'l', partOfWord: 'lap' },
        { letter: 'a', partOfWord: 'alt' },
        { letter: 'p', partOfWord: 'lap' },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 'l', partOfWord: 'alt' },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 't', partOfWord: 'alt' },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    ],
    placedWords: 18,
  },
  {
    letters: 'aeztsn',
    words: [
      'east',
      'seat',
      'neat',
      'nest',
      'eats',
      'sane',
      'ante',
      'zest',
      'ants',
      'nets',
      'tens',
      'set',
      'net',
      'ten',
      'sea',
      'sat',
      'eat',
      'tea',
      'ate',
      'tan',
      'ant',
      'zen',
    ],
    grid: [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'a', partOfWord: 'ants' },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 't', partOfWord: 'tens' },
        { letter: 'e', partOfWord: 'tens' },
        { letter: 'n', partOfWord: 'tens' },
        { letter: 's', partOfWord: 'tens' },
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 't', partOfWord: 'ants' },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'z', partOfWord: 'zest' },
        { letter: 'e', partOfWord: 'zest' },
        { letter: 's', partOfWord: 'ants' },
        { letter: 't', partOfWord: 'ten' },
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 'a', partOfWord: 'eats' },
        null,
        { letter: 'e', partOfWord: 'ten' },
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 't', partOfWord: 'eats' },
        null,
        { letter: 'n', partOfWord: 'ten' },
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'n', partOfWord: 'nest' },
        { letter: 'e', partOfWord: 'nest' },
        { letter: 's', partOfWord: 'eats' },
        { letter: 't', partOfWord: 'nest' },
        null,
        null,
      ],
      [
        null,
        { letter: 'a', partOfWord: 'ate' },
        { letter: 't', partOfWord: 'ate' },
        { letter: 'e', partOfWord: 'ate' },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 's', partOfWord: 'seat' },
        null,
        null,
        { letter: 'a', partOfWord: 'ante' },
        { letter: 'n', partOfWord: 'ante' },
        { letter: 't', partOfWord: 'ante' },
        { letter: 'e', partOfWord: 'eat' },
        null,
        null,
      ],
      [
        { letter: 'e', partOfWord: 'seat' },
        { letter: 'a', partOfWord: 'east' },
        { letter: 's', partOfWord: 'sane' },
        { letter: 't', partOfWord: 'neat' },
        null,
        null,
        { letter: 'a', partOfWord: 'eat' },
        null,
        { letter: 't', partOfWord: 'tan' },
      ],
      [
        { letter: 'a', partOfWord: 'seat' },
        null,
        { letter: 'a', partOfWord: 'sane' },
        null,
        null,
        null,
        { letter: 't', partOfWord: 'tea' },
        { letter: 'e', partOfWord: 'tea' },
        { letter: 'a', partOfWord: 'tan' },
      ],
      [
        { letter: 't', partOfWord: 'seat' },
        null,
        { letter: 'n', partOfWord: 'nets' },
        { letter: 'e', partOfWord: 'nets' },
        { letter: 't', partOfWord: 'nets' },
        { letter: 's', partOfWord: 'set' },
        null,
        null,
        { letter: 'n', partOfWord: 'tan' },
      ],
      [
        null,
        null,
        { letter: 'e', partOfWord: 'sane' },
        null,
        null,
        { letter: 'e', partOfWord: 'set' },
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'n', partOfWord: 'net' },
        { letter: 'e', partOfWord: 'net' },
        { letter: 't', partOfWord: 'net' },
        null,
        null,
        null,
      ],
    ],
    placedWords: 18,
  },
  {
    letters: 'eaycps',
    words: [
      'space',
      'paces',
      'case',
      'easy',
      'pace',
      'cape',
      'spec',
      'pays',
      'caps',
      'apes',
      'peas',
      'say',
      'pay',
      'yes',
      'sea',
      'ace',
      'spa',
      'sap',
      'spy',
      'pea',
      'ape',
    ],
    grid: [
      [
        null,
        null,
        null,
        null,
        { letter: 's', partOfWord: 'say' },
        { letter: 'a', partOfWord: 'say' },
        { letter: 'y', partOfWord: 'say' },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 'p', partOfWord: 'apes' },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'c', partOfWord: 'cape' },
        null,
        { letter: 'e', partOfWord: 'apes' },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'p', partOfWord: 'pays' },
        { letter: 'a', partOfWord: 'pays' },
        { letter: 'y', partOfWord: 'pays' },
        { letter: 's', partOfWord: 'apes' },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'p', partOfWord: 'cape' },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'p', partOfWord: 'pace' },
        { letter: 'a', partOfWord: 'pace' },
        { letter: 'c', partOfWord: 'pace' },
        { letter: 'e', partOfWord: 'cape' },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'a', partOfWord: 'paces' },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'c', partOfWord: 'paces' },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'e', partOfWord: 'paces' },
        null,
        { letter: 'c', partOfWord: 'case' },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 's', partOfWord: 'paces' },
        { letter: 'p', partOfWord: 'space' },
        { letter: 'a', partOfWord: 'case' },
        { letter: 'c', partOfWord: 'space' },
        { letter: 'e', partOfWord: 'easy' },
        null,
        { letter: 'a', partOfWord: 'ape' },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 's', partOfWord: 'case' },
        null,
        { letter: 'a', partOfWord: 'easy' },
        null,
        { letter: 'p', partOfWord: 'ape' },
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'a', partOfWord: 'ace' },
        { letter: 'c', partOfWord: 'ace' },
        { letter: 'e', partOfWord: 'ace' },
        null,
        { letter: 's', partOfWord: 'spec' },
        { letter: 'p', partOfWord: 'spec' },
        { letter: 'e', partOfWord: 'ape' },
        { letter: 'c', partOfWord: 'caps' },
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'y', partOfWord: 'easy' },
        null,
        null,
        { letter: 'a', partOfWord: 'caps' },
        null,
        { letter: 'p', partOfWord: 'pay' },
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'p', partOfWord: 'peas' },
        { letter: 'e', partOfWord: 'peas' },
        { letter: 'a', partOfWord: 'pay' },
        { letter: 's', partOfWord: 'peas' },
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 'y', partOfWord: 'yes' },
        { letter: 'e', partOfWord: 'yes' },
        { letter: 's', partOfWord: 'yes' },
        null,
        { letter: 'y', partOfWord: 'pay' },
        null,
      ],
    ],
    placedWords: 16,
  },
  {
    letters: 'aognyr',
    words: [
      'angry',
      'organ',
      'agony',
      'groan',
      'argon',
      'gray',
      'rang',
      'yarn',
      'yoga',
      'any',
      'ago',
      'nor',
      'ran',
      'ray',
      'rag',
      'oar',
    ],
    grid: [
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 'r', partOfWord: 'ray' },
        { letter: 'a', partOfWord: 'ray' },
        { letter: 'y', partOfWord: 'ray' },
        null,
        null,
      ],
      [
        { letter: 'o', partOfWord: 'organ' },
        null,
        { letter: 'r', partOfWord: 'rag' },
        { letter: 'a', partOfWord: 'rag' },
        { letter: 'g', partOfWord: 'rag' },
        null,
        null,
        { letter: 'o', partOfWord: 'oar' },
        { letter: 'a', partOfWord: 'oar' },
        { letter: 'r', partOfWord: 'oar' },
      ],
      [
        { letter: 'r', partOfWord: 'organ' },
        null,
        null,
        null,
        { letter: 'r', partOfWord: 'rang' },
        { letter: 'a', partOfWord: 'rang' },
        { letter: 'n', partOfWord: 'rang' },
        { letter: 'g', partOfWord: 'yoga' },
        null,
        null,
      ],
      [
        { letter: 'g', partOfWord: 'organ' },
        null,
        { letter: 'a', partOfWord: 'agony' },
        null,
        { letter: 'a', partOfWord: 'gray' },
        null,
        null,
        { letter: 'a', partOfWord: 'ago' },
        { letter: 'g', partOfWord: 'ago' },
        { letter: 'o', partOfWord: 'ago' },
      ],
      [
        { letter: 'a', partOfWord: 'organ' },
        { letter: 'n', partOfWord: 'angry' },
        { letter: 'g', partOfWord: 'agony' },
        { letter: 'r', partOfWord: 'angry' },
        { letter: 'y', partOfWord: 'gray' },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'n', partOfWord: 'organ' },
        null,
        { letter: 'o', partOfWord: 'agony' },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'n', partOfWord: 'agony' },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'y', partOfWord: 'yarn' },
        { letter: 'a', partOfWord: 'any' },
        { letter: 'r', partOfWord: 'yarn' },
        { letter: 'n', partOfWord: 'nor' },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'n', partOfWord: 'any' },
        null,
        { letter: 'o', partOfWord: 'nor' },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'y', partOfWord: 'any' },
        null,
        { letter: 'r', partOfWord: 'ran' },
        { letter: 'a', partOfWord: 'ran' },
        { letter: 'n', partOfWord: 'ran' },
        null,
        null,
      ],
    ],
    placedWords: 14,
  },
  {
    letters: 'aemtss',
    words: [
      'asset',
      'steam',
      'masse',
      'seams',
      'seats',
      'stems',
      'mates',
      'teams',
      'meats',
      'same',
      'team',
      'mass',
      'seat',
      'meat',
      'mess',
      'stem',
      'mate',
      'mesa',
      'eats',
      'mast',
      'tame',
      'seam',
      'sets',
      'meta',
      'seas',
      'mats',
      'set',
      'met',
      'sea',
      'sat',
      'eat',
      'tea',
      'ate',
      'mat',
    ],
    grid: [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'e', partOfWord: 'eat' },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'm', partOfWord: 'meta' },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'a', partOfWord: 'eat' },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 't', partOfWord: 'tea' },
        { letter: 'e', partOfWord: 'tea' },
        { letter: 'a', partOfWord: 'tea' },
        null,
        null,
        null,
        null,
        { letter: 'm', partOfWord: 'mats' },
        { letter: 'a', partOfWord: 'mats' },
        { letter: 't', partOfWord: 'eat' },
        { letter: 's', partOfWord: 'mats' },
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 't', partOfWord: 'meta' },
        null,
        { letter: 's', partOfWord: 'seat' },
        null,
        null,
        null,
        { letter: 'e', partOfWord: 'mesa' },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 'm', partOfWord: 'mate' },
        { letter: 'a', partOfWord: 'meta' },
        { letter: 't', partOfWord: 'mate' },
        { letter: 'e', partOfWord: 'mate' },
        null,
        { letter: 'm', partOfWord: 'mess' },
        { letter: 'e', partOfWord: 'mess' },
        { letter: 's', partOfWord: 'mesa' },
        { letter: 's', partOfWord: 'mess' },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 's', partOfWord: 'steam' },
        null,
        null,
        null,
        { letter: 'a', partOfWord: 'seat' },
        null,
        { letter: 'a', partOfWord: 'mass' },
        null,
        { letter: 'a', partOfWord: 'mesa' },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 't', partOfWord: 'steam' },
        null,
        { letter: 'm', partOfWord: 'mates' },
        { letter: 'a', partOfWord: 'mates' },
        { letter: 't', partOfWord: 'seat' },
        { letter: 'e', partOfWord: 'mates' },
        { letter: 's', partOfWord: 'mass' },
        null,
        null,
        null,
        { letter: 'm', partOfWord: 'met' },
        { letter: 'e', partOfWord: 'met' },
        { letter: 't', partOfWord: 'met' },
        null,
        null,
      ],
      [
        { letter: 'e', partOfWord: 'steam' },
        null,
        { letter: 'a', partOfWord: 'masse' },
        null,
        null,
        null,
        { letter: 's', partOfWord: 'mass' },
        null,
        null,
        null,
        { letter: 'a', partOfWord: 'mast' },
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'a', partOfWord: 'steam' },
        { letter: 's', partOfWord: 'asset' },
        { letter: 's', partOfWord: 'masse' },
        { letter: 'e', partOfWord: 'asset' },
        { letter: 't', partOfWord: 'asset' },
        null,
        null,
        null,
        { letter: 't', partOfWord: 'team' },
        null,
        { letter: 's', partOfWord: 'sets' },
        { letter: 'e', partOfWord: 'sets' },
        { letter: 't', partOfWord: 'sets' },
        { letter: 's', partOfWord: 'sea' },
        null,
      ],
      [
        { letter: 'm', partOfWord: 'steam' },
        null,
        { letter: 's', partOfWord: 'masse' },
        null,
        null,
        null,
        null,
        { letter: 'm', partOfWord: 'meat' },
        { letter: 'e', partOfWord: 'meat' },
        { letter: 'a', partOfWord: 'meat' },
        { letter: 't', partOfWord: 'mast' },
        null,
        null,
        { letter: 'e', partOfWord: 'sea' },
        null,
      ],
      [
        null,
        { letter: 's', partOfWord: 'seats' },
        { letter: 'e', partOfWord: 'seams' },
        { letter: 'a', partOfWord: 'seams' },
        { letter: 'm', partOfWord: 'seams' },
        { letter: 's', partOfWord: 'stems' },
        null,
        null,
        { letter: 'a', partOfWord: 'team' },
        null,
        null,
        null,
        null,
        { letter: 'a', partOfWord: 'sea' },
        null,
      ],
      [
        null,
        { letter: 'e', partOfWord: 'seats' },
        null,
        null,
        null,
        { letter: 't', partOfWord: 'teams' },
        { letter: 'e', partOfWord: 'teams' },
        { letter: 'a', partOfWord: 'teams' },
        { letter: 'm', partOfWord: 'team' },
        { letter: 's', partOfWord: 'teams' },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 's', partOfWord: 'same' },
        { letter: 'a', partOfWord: 'same' },
        { letter: 'm', partOfWord: 'same' },
        { letter: 'e', partOfWord: 'eats' },
        null,
        { letter: 'e', partOfWord: 'stems' },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 't', partOfWord: 'seats' },
        null,
        { letter: 'a', partOfWord: 'eats' },
        null,
        { letter: 'm', partOfWord: 'meats' },
        { letter: 'e', partOfWord: 'meats' },
        { letter: 'a', partOfWord: 'meats' },
        { letter: 't', partOfWord: 'meats' },
        { letter: 's', partOfWord: 'stem' },
        null,
        null,
        { letter: 's', partOfWord: 'sat' },
        { letter: 'a', partOfWord: 'sat' },
        { letter: 't', partOfWord: 'sat' },
      ],
      [
        null,
        { letter: 's', partOfWord: 'seats' },
        null,
        { letter: 't', partOfWord: 'eats' },
        null,
        { letter: 's', partOfWord: 'stems' },
        null,
        null,
        null,
        { letter: 't', partOfWord: 'tame' },
        { letter: 'a', partOfWord: 'tame' },
        { letter: 'm', partOfWord: 'tame' },
        { letter: 'e', partOfWord: 'seas' },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 's', partOfWord: 'eats' },
        null,
        null,
        null,
        null,
        null,
        { letter: 'e', partOfWord: 'stem' },
        null,
        null,
        { letter: 'a', partOfWord: 'seas' },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 's', partOfWord: 'set' },
        { letter: 'e', partOfWord: 'seam' },
        { letter: 'a', partOfWord: 'ate' },
        { letter: 'm', partOfWord: 'seam' },
        null,
        null,
        { letter: 's', partOfWord: 'seas' },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'e', partOfWord: 'set' },
        null,
        { letter: 't', partOfWord: 'ate' },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'm', partOfWord: 'mat' },
        { letter: 'a', partOfWord: 'mat' },
        { letter: 't', partOfWord: 'mat' },
        null,
        { letter: 'e', partOfWord: 'ate' },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    ],
    placedWords: 34,
  },
  {
    letters: 'aeqtry',
    words: [
      'year',
      'rate',
      'tear',
      'tray',
      'are',
      'yet',
      'art',
      'try',
      'eat',
      'era',
      'tea',
      'ray',
      'ear',
      'ate',
      'rat',
      'rye',
      'tar',
    ],
    grid: [
      [
        null,
        null,
        null,
        null,
        { letter: 'e', partOfWord: 'ear' },
        null,
        { letter: 't', partOfWord: 'try' },
        null,
        { letter: 'r', partOfWord: 'rye' },
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'a', partOfWord: 'ear' },
        null,
        { letter: 'r', partOfWord: 'ray' },
        { letter: 'a', partOfWord: 'ray' },
        { letter: 'y', partOfWord: 'rye' },
      ],
      [
        null,
        { letter: 'r', partOfWord: 'rate' },
        null,
        { letter: 't', partOfWord: 'tray' },
        { letter: 'r', partOfWord: 'ear' },
        { letter: 'a', partOfWord: 'tray' },
        { letter: 'y', partOfWord: 'try' },
        null,
        { letter: 'e', partOfWord: 'rye' },
      ],
      [
        null,
        { letter: 'a', partOfWord: 'rate' },
        null,
        { letter: 'e', partOfWord: 'tear' },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 't', partOfWord: 'rate' },
        null,
        { letter: 'a', partOfWord: 'art' },
        { letter: 'r', partOfWord: 'art' },
        { letter: 't', partOfWord: 'tea' },
        null,
        null,
        null,
      ],
      [
        { letter: 'y', partOfWord: 'yet' },
        { letter: 'e', partOfWord: 'rate' },
        { letter: 'a', partOfWord: 'are' },
        { letter: 'r', partOfWord: 'tear' },
        null,
        { letter: 'e', partOfWord: 'tea' },
        null,
        null,
        null,
      ],
      [
        { letter: 'e', partOfWord: 'yet' },
        null,
        { letter: 'r', partOfWord: 'are' },
        null,
        null,
        { letter: 'a', partOfWord: 'tea' },
        null,
        null,
        null,
      ],
      [
        { letter: 't', partOfWord: 'yet' },
        null,
        { letter: 'e', partOfWord: 'eat' },
        { letter: 'a', partOfWord: 'ate' },
        { letter: 't', partOfWord: 'eat' },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 't', partOfWord: 'ate' },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'e', partOfWord: 'ate' },
        null,
        null,
        null,
        null,
        null,
      ],
    ],
    placedWords: 14,
  },
  {
    letters: 'ietpfl',
    words: [
      'life',
      'left',
      'felt',
      'file',
      'lift',
      'pile',
      'flip',
      'tile',
      'fit',
      'lie',
      'tie',
      'tip',
      'pet',
      'pit',
      'lit',
      'pie',
      'lip',
    ],
    grid: [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'l', partOfWord: 'lip' },
        { letter: 'i', partOfWord: 'lip' },
        { letter: 'p', partOfWord: 'lip' },
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'i', partOfWord: 'lit' },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'p', partOfWord: 'pit' },
        { letter: 'i', partOfWord: 'pit' },
        { letter: 't', partOfWord: 'lit' },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 't', partOfWord: 'tie' },
        { letter: 'i', partOfWord: 'tie' },
        { letter: 'e', partOfWord: 'pet' },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 'i', partOfWord: 'tile' },
        null,
        { letter: 't', partOfWord: 'pet' },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'f', partOfWord: 'file' },
        null,
        { letter: 'l', partOfWord: 'tile' },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'p', partOfWord: 'pile' },
        { letter: 'i', partOfWord: 'pile' },
        { letter: 'l', partOfWord: 'pile' },
        { letter: 'e', partOfWord: 'tile' },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'l', partOfWord: 'file' },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'l', partOfWord: 'left' },
        { letter: 'i', partOfWord: 'life' },
        { letter: 'f', partOfWord: 'felt' },
        { letter: 'e', partOfWord: 'file' },
        null,
        { letter: 'f', partOfWord: 'fit' },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'e', partOfWord: 'left' },
        null,
        { letter: 'e', partOfWord: 'felt' },
        null,
        null,
        { letter: 'i', partOfWord: 'fit' },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'f', partOfWord: 'left' },
        null,
        { letter: 'l', partOfWord: 'lift' },
        { letter: 'i', partOfWord: 'lift' },
        { letter: 'f', partOfWord: 'flip' },
        { letter: 't', partOfWord: 'fit' },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 't', partOfWord: 'left' },
        null,
        { letter: 't', partOfWord: 'felt' },
        null,
        { letter: 'l', partOfWord: 'flip' },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'l', partOfWord: 'lie' },
        { letter: 'i', partOfWord: 'lie' },
        { letter: 'e', partOfWord: 'lie' },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'p', partOfWord: 'flip' },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    ],
    placedWords: 15,
  },
  {
    letters: 'eospdn',
    words: [
      'spend',
      'nodes',
      'ponds',
      'posed',
      'opens',
      'does',
      'open',
      'done',
      'send',
      'nose',
      'dose',
      'pose',
      'pond',
      'node',
      'sped',
      'dope',
      'pens',
      'nods',
      'pods',
      'ends',
      'ones',
      'one',
      'end',
      'son',
      'pen',
      'nod',
      'den',
      'pod',
      'ode',
    ],
    grid: [
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 's', partOfWord: 'son' },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 'o', partOfWord: 'son' },
        null,
        null,
        { letter: 'p', partOfWord: 'pen' },
        { letter: 'e', partOfWord: 'pen' },
        { letter: 'n', partOfWord: 'pen' },
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 'n', partOfWord: 'son' },
        { letter: 'o', partOfWord: 'nose' },
        { letter: 's', partOfWord: 'nose' },
        { letter: 'e', partOfWord: 'pens' },
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'p', partOfWord: 'open' },
        null,
        { letter: 'n', partOfWord: 'nods' },
        { letter: 'o', partOfWord: 'nods' },
        { letter: 'd', partOfWord: 'den' },
        { letter: 's', partOfWord: 'nods' },
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'e', partOfWord: 'open' },
        null,
        { letter: 's', partOfWord: 'pens' },
        null,
        { letter: 'e', partOfWord: 'den' },
        null,
      ],
      [
        { letter: 'n', partOfWord: 'nodes' },
        null,
        null,
        { letter: 'o', partOfWord: 'opens' },
        { letter: 'p', partOfWord: 'opens' },
        { letter: 'e', partOfWord: 'opens' },
        { letter: 'n', partOfWord: 'open' },
        { letter: 's', partOfWord: 'opens' },
        null,
        null,
        { letter: 'n', partOfWord: 'den' },
        null,
      ],
      [
        { letter: 'o', partOfWord: 'nodes' },
        null,
        { letter: 'd', partOfWord: 'done' },
        null,
        { letter: 'o', partOfWord: 'posed' },
        null,
        null,
        null,
        null,
        { letter: 'o', partOfWord: 'ode' },
        null,
        null,
      ],
      [
        { letter: 'd', partOfWord: 'nodes' },
        null,
        { letter: 'o', partOfWord: 'done' },
        null,
        { letter: 's', partOfWord: 'send' },
        { letter: 'e', partOfWord: 'send' },
        { letter: 'n', partOfWord: 'send' },
        { letter: 'd', partOfWord: 'dose' },
        null,
        { letter: 'd', partOfWord: 'ode' },
        null,
        null,
      ],
      [
        { letter: 'e', partOfWord: 'nodes' },
        null,
        { letter: 'n', partOfWord: 'done' },
        null,
        { letter: 'e', partOfWord: 'posed' },
        null,
        null,
        { letter: 'o', partOfWord: 'ones' },
        { letter: 'n', partOfWord: 'ones' },
        { letter: 'e', partOfWord: 'ode' },
        { letter: 's', partOfWord: 'ones' },
        null,
      ],
      [
        { letter: 's', partOfWord: 'nodes' },
        { letter: 'p', partOfWord: 'ponds' },
        { letter: 'e', partOfWord: 'done' },
        { letter: 'n', partOfWord: 'spend' },
        { letter: 'd', partOfWord: 'posed' },
        null,
        null,
        { letter: 's', partOfWord: 'dose' },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 'o', partOfWord: 'ponds' },
        null,
        null,
        null,
        null,
        null,
        { letter: 'e', partOfWord: 'ends' },
        { letter: 'n', partOfWord: 'ends' },
        { letter: 'd', partOfWord: 'ends' },
        { letter: 's', partOfWord: 'ends' },
        null,
      ],
      [
        null,
        { letter: 'n', partOfWord: 'ponds' },
        null,
        null,
        null,
        null,
        { letter: 'n', partOfWord: 'nod' },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 'd', partOfWord: 'does' },
        { letter: 'o', partOfWord: 'does' },
        { letter: 'e', partOfWord: 'does' },
        { letter: 's', partOfWord: 'sped' },
        null,
        { letter: 'o', partOfWord: 'nod' },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 's', partOfWord: 'ponds' },
        null,
        null,
        { letter: 'p', partOfWord: 'pods' },
        { letter: 'o', partOfWord: 'pods' },
        { letter: 'd', partOfWord: 'nod' },
        { letter: 's', partOfWord: 'pods' },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'o', partOfWord: 'one' },
        { letter: 'n', partOfWord: 'one' },
        { letter: 'e', partOfWord: 'one' },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'd', partOfWord: 'dope' },
        { letter: 'o', partOfWord: 'dope' },
        { letter: 'p', partOfWord: 'dope' },
        { letter: 'e', partOfWord: 'end' },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'n', partOfWord: 'end' },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 'p', partOfWord: 'pod' },
        { letter: 'o', partOfWord: 'pod' },
        { letter: 'd', partOfWord: 'pod' },
        null,
        null,
        null,
        null,
      ],
    ],
    placedWords: 26,
  },
  {
    letters: 'oedrnv',
    words: [
      'vendor',
      'drove',
      'over',
      'done',
      'oven',
      'node',
      'rode',
      'dove',
      'one',
      'end',
      'red',
      'nor',
      'ore',
      'rod',
      'nod',
      'doe',
      'den',
      'ode',
    ],
    grid: [
      [
        null,
        null,
        null,
        null,
        { letter: 'd', partOfWord: 'den' },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'e', partOfWord: 'den' },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'n', partOfWord: 'den' },
        { letter: 'o', partOfWord: 'nod' },
        { letter: 'd', partOfWord: 'nod' },
        null,
        null,
      ],
      [
        { letter: 'd', partOfWord: 'drove' },
        null,
        null,
        null,
        null,
        { letter: 'r', partOfWord: 'ore' },
        null,
        null,
        null,
      ],
      [
        { letter: 'r', partOfWord: 'drove' },
        null,
        { letter: 'd', partOfWord: 'dove' },
        { letter: 'o', partOfWord: 'dove' },
        { letter: 'v', partOfWord: 'dove' },
        { letter: 'e', partOfWord: 'ore' },
        null,
        null,
        null,
      ],
      [
        { letter: 'o', partOfWord: 'drove' },
        null,
        { letter: 'o', partOfWord: 'done' },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'v', partOfWord: 'drove' },
        { letter: 'e', partOfWord: 'vendor' },
        { letter: 'n', partOfWord: 'done' },
        { letter: 'd', partOfWord: 'vendor' },
        { letter: 'o', partOfWord: 'over' },
        { letter: 'r', partOfWord: 'vendor' },
        null,
        null,
        null,
      ],
      [
        { letter: 'e', partOfWord: 'drove' },
        null,
        { letter: 'e', partOfWord: 'done' },
        null,
        { letter: 'v', partOfWord: 'over' },
        null,
        { letter: 'e', partOfWord: 'end' },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'e', partOfWord: 'over' },
        null,
        { letter: 'n', partOfWord: 'end' },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'r', partOfWord: 'rode' },
        { letter: 'o', partOfWord: 'one' },
        { letter: 'd', partOfWord: 'end' },
        { letter: 'e', partOfWord: 'rode' },
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { letter: 'n', partOfWord: 'one' },
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'r', partOfWord: 'rod' },
        { letter: 'e', partOfWord: 'red' },
        { letter: 'd', partOfWord: 'doe' },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'o', partOfWord: 'rod' },
        null,
        { letter: 'o', partOfWord: 'ode' },
        { letter: 'd', partOfWord: 'ode' },
        { letter: 'e', partOfWord: 'ode' },
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'd', partOfWord: 'rod' },
        null,
        { letter: 'e', partOfWord: 'doe' },
        null,
        null,
      ],
    ],
    placedWords: 15,
  },
  {
    letters: 'iewdhn',
    words: [
      'widen',
      'when',
      'wide',
      'wind',
      'wine',
      'hide',
      'dine',
      'hind',
      'new',
      'end',
      'win',
      'die',
      'den',
      'wed',
      'hid',
      'hen',
      'dew',
    ],
    grid: [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'w', partOfWord: 'win' },
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'i', partOfWord: 'win' },
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'h', partOfWord: 'hind' },
        { letter: 'i', partOfWord: 'hind' },
        { letter: 'n', partOfWord: 'win' },
        { letter: 'd', partOfWord: 'hind' },
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'i', partOfWord: 'hide' },
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'd', partOfWord: 'die' },
        { letter: 'i', partOfWord: 'die' },
        { letter: 'e', partOfWord: 'die' },
        null,
      ],
      [
        { letter: 'd', partOfWord: 'dew' },
        { letter: 'e', partOfWord: 'dew' },
        { letter: 'w', partOfWord: 'dew' },
        null,
        { letter: 'w', partOfWord: 'wine' },
        { letter: 'i', partOfWord: 'wine' },
        { letter: 'n', partOfWord: 'wine' },
        { letter: 'e', partOfWord: 'hide' },
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'i', partOfWord: 'wide' },
        null,
        { letter: 'i', partOfWord: 'wind' },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'w', partOfWord: 'when' },
        { letter: 'i', partOfWord: 'widen' },
        { letter: 'd', partOfWord: 'wide' },
        { letter: 'e', partOfWord: 'widen' },
        { letter: 'n', partOfWord: 'wind' },
        null,
        { letter: 'e', partOfWord: 'end' },
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'h', partOfWord: 'when' },
        null,
        { letter: 'e', partOfWord: 'wide' },
        null,
        { letter: 'd', partOfWord: 'dine' },
        { letter: 'i', partOfWord: 'dine' },
        { letter: 'n', partOfWord: 'end' },
        { letter: 'e', partOfWord: 'dine' },
        null,
        null,
        null,
      ],
      [
        { letter: 'e', partOfWord: 'when' },
        null,
        null,
        null,
        null,
        null,
        { letter: 'd', partOfWord: 'end' },
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'n', partOfWord: 'new' },
        { letter: 'e', partOfWord: 'new' },
        { letter: 'w', partOfWord: 'wed' },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'e', partOfWord: 'wed' },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'h', partOfWord: 'hen' },
        { letter: 'i', partOfWord: 'hid' },
        { letter: 'd', partOfWord: 'hid' },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'e', partOfWord: 'hen' },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'n', partOfWord: 'hen' },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    ],
    placedWords: 16,
  },
  {
    letters: 'eamdtt',
    words: [
      'made',
      'team',
      'date',
      'meat',
      'mate',
      'mead',
      'tame',
      'meta',
      'met',
      'eat',
      'tea',
      'mad',
      'ted',
      'ate',
      'dam',
      'mat',
    ],
    grid: [
      [
        null,
        null,
        null,
        null,
        { letter: 'a', partOfWord: 'ate' },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 't', partOfWord: 'ate' },
        null,
        { letter: 'm', partOfWord: 'mat' },
        { letter: 'a', partOfWord: 'mat' },
        { letter: 't', partOfWord: 'mat' },
      ],
      [
        { letter: 't', partOfWord: 'team' },
        null,
        null,
        { letter: 'm', partOfWord: 'meta' },
        { letter: 'e', partOfWord: 'ate' },
        { letter: 't', partOfWord: 'meta' },
        { letter: 'a', partOfWord: 'mad' },
        null,
        null,
      ],
      [
        { letter: 'e', partOfWord: 'team' },
        null,
        null,
        { letter: 'a', partOfWord: 'mate' },
        null,
        null,
        { letter: 'd', partOfWord: 'dam' },
        { letter: 'a', partOfWord: 'dam' },
        { letter: 'm', partOfWord: 'dam' },
      ],
      [
        { letter: 'a', partOfWord: 'team' },
        null,
        null,
        { letter: 't', partOfWord: 'tea' },
        { letter: 'e', partOfWord: 'tea' },
        { letter: 'a', partOfWord: 'tea' },
        null,
        null,
        null,
      ],
      [
        { letter: 'm', partOfWord: 'team' },
        { letter: 'a', partOfWord: 'made' },
        { letter: 'd', partOfWord: 'date' },
        { letter: 'e', partOfWord: 'mate' },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'a', partOfWord: 'date' },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 't', partOfWord: 'date' },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 'm', partOfWord: 'mead' },
        { letter: 'e', partOfWord: 'meat' },
        { letter: 'a', partOfWord: 'meat' },
        { letter: 't', partOfWord: 'tame' },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 'e', partOfWord: 'mead' },
        null,
        null,
        { letter: 'a', partOfWord: 'tame' },
        null,
        null,
        null,
        null,
      ],
      [
        { letter: 'e', partOfWord: 'eat' },
        { letter: 'a', partOfWord: 'eat' },
        { letter: 't', partOfWord: 'eat' },
        null,
        { letter: 'm', partOfWord: 'met' },
        { letter: 'e', partOfWord: 'met' },
        { letter: 't', partOfWord: 'ted' },
        null,
        null,
      ],
      [
        null,
        { letter: 'd', partOfWord: 'mead' },
        null,
        null,
        { letter: 'e', partOfWord: 'tame' },
        null,
        { letter: 'e', partOfWord: 'ted' },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'd', partOfWord: 'ted' },
        null,
        null,
      ],
    ],
    placedWords: 16,
  },
  {
    letters: 'eifldv',
    words: [
      'field',
      'devil',
      'filed',
      'lived',
      'life',
      'five',
      'live',
      'file',
      'evil',
      'fled',
      'idle',
      'dive',
      'lied',
      'veil',
      'vile',
      'led',
      'die',
      'lie',
      'fed',
      'lid',
    ],
    grid: [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'd', partOfWord: 'dive' },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'v', partOfWord: 'veil' },
        { letter: 'e', partOfWord: 'veil' },
        { letter: 'i', partOfWord: 'veil' },
        { letter: 'l', partOfWord: 'veil' },
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        { letter: 'v', partOfWord: 'dive' },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { letter: 'f', partOfWord: 'file' },
        { letter: 'i', partOfWord: 'file' },
        { letter: 'l', partOfWord: 'file' },
        { letter: 'e', partOfWord: 'dive' },
        null,
        null,
      ],
      [
        null,
        { letter: 'd', partOfWord: 'devil' },
        null,
        null,
        null,
        { letter: 'i', partOfWord: 'live' },
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 'e', partOfWord: 'devil' },
        null,
        { letter: 'f', partOfWord: 'five' },
        { letter: 'i', partOfWord: 'five' },
        { letter: 'v', partOfWord: 'live' },
        { letter: 'e', partOfWord: 'five' },
        null,
        null,
      ],
      [
        null,
        { letter: 'v', partOfWord: 'devil' },
        null,
        { letter: 'i', partOfWord: 'filed' },
        null,
        { letter: 'e', partOfWord: 'live' },
        null,
        null,
        null,
      ],
      [
        { letter: 'f', partOfWord: 'field' },
        { letter: 'i', partOfWord: 'devil' },
        { letter: 'e', partOfWord: 'field' },
        { letter: 'l', partOfWord: 'filed' },
        { letter: 'd', partOfWord: 'field' },
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { letter: 'l', partOfWord: 'devil' },
        null,
        { letter: 'e', partOfWord: 'filed' },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        { letter: 'i', partOfWord: 'idle' },
        { letter: 'd', partOfWord: 'idle' },
        { letter: 'l', partOfWord: 'lied' },
        { letter: 'e', partOfWord: 'idle' },
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'i', partOfWord: 'lied' },
        null,
        { letter: 'l', partOfWord: 'lid' },
        { letter: 'i', partOfWord: 'lid' },
        { letter: 'd', partOfWord: 'lid' },
      ],
      [
        null,
        { letter: 'v', partOfWord: 'vile' },
        { letter: 'i', partOfWord: 'vile' },
        { letter: 'l', partOfWord: 'vile' },
        { letter: 'e', partOfWord: 'vile' },
        null,
        { letter: 'i', partOfWord: 'lie' },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { letter: 'd', partOfWord: 'die' },
        { letter: 'i', partOfWord: 'die' },
        { letter: 'e', partOfWord: 'lie' },
        null,
        null,
      ],
    ],
    placedWords: 14,
  },
]
